<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Serial Number_chequeBookCO.ctschqbook_a1b49d</name>
   <tag></tag>
   <elementGuidId>f65ec400-ddca-409e-aec9-d4b13dad5241</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#alphabetical_series_Q000MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='alphabetical_series_Q000MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>28cf687e-0a6b-4df8-9b84-bbf2d5b0b3cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2bf62ca6-0fbf-40f8-b16c-3fd74fbd98d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>02730399-b1a8-44be-929b-914f0d8e9bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chequeBookCO.ctschqbookVO.ALPHABETICAL_SERIES</value>
      <webElementGuid>1cf04bd3-bcd1-4ca2-a70b-12fad09d2ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>cab1a340-c024-423e-874b-5522147d0863</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>99546165-534e-4b7f-96db-40cf56135715</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>alphabetical_series_Q000MT</value>
      <webElementGuid>ef3c0bef-8e3c-4002-a66e-fca5701f7e00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;alphabetical_series_Q000MT&quot;)</value>
      <webElementGuid>2dff925c-7254-44bf-bb12-428978dc33f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='alphabetical_series_Q000MT']</value>
      <webElementGuid>2e166ebe-7d09-429c-8661-ebb12d02e59e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chequeBookInfo']/div[2]/table/tbody/tr/td[3]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>1ff9126c-efe3-443c-a857-fb30047af83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>5ba0a573-c6c3-4c8a-8d5d-e04f709e55f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'chequeBookCO.ctschqbookVO.ALPHABETICAL_SERIES' and @id = 'alphabetical_series_Q000MT']</value>
      <webElementGuid>7ee6e9bf-abad-4a59-813f-44245a20978b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
