<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__chequeBookCO.ctschqbookVO.NUM_OF_CHQBOOKS</name>
   <tag></tag>
   <elementGuidId>a33f62e8-c6be-4af6-b94d-82593efcd22e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#num_of_chqbooks_Q000MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='num_of_chqbooks_Q000MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10bdd78f-21e5-46fd-adc9-aca7e41ae5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>492cac90-4081-4760-b978-07ceb457e542</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f292a7e9-ed45-4d14-9375-2a33fa0e94dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chequeBookCO.ctschqbookVO.NUM_OF_CHQBOOKS</value>
      <webElementGuid>bf7d3f2f-9ffa-4180-a406-3b1f396711b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>fe7da5fe-5481-43a5-8c9c-9345afd3fe00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>8138245d-75d7-4337-8278-09e5111be253</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>num_of_chqbooks_Q000MT</value>
      <webElementGuid>725c1adf-d93b-4142-9e04-b80c773c4346</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a9aa8de1-c521-4a79-a466-a91a03adedce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>####</value>
      <webElementGuid>a520da23-91a3-4783-bea0-dd82d624e211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>noformat</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>3233c29a-17c4-4bdd-a378-8af3bb43e2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zeronotallowed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e2fff914-05b0-417a-b899-7ae5a2ab9a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalsepa</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>078594ee-5703-4c14-9157-3eba047df3a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>groupsepa</name>
      <type>Main</type>
      <value>,</value>
      <webElementGuid>a4dae04a-608c-48ac-bf76-b2fc9cc52dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>adde6edf-7650-4f49-befd-41e7446afca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>numOfChqbooksChange()</value>
      <webElementGuid>d8bccdce-2a83-4679-9e77-97c12d6dc65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>num_of_chqbooks_Q000MT:chequeBookCO.ctschqbookVO.NUM_OF_CHQBOOKS</value>
      <webElementGuid>76490516-1592-409d-987b-bd18c76afaf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/chequeBook/ChequeBookMaintAction_dependencyByNumOfChequebooks</value>
      <webElementGuid>19249b8f-e2a4-4186-9831-8f118f41d9bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>ctschqbookVO.CHEQUE_CODE:lookuptxt_CHEQUE_CODE_Q000MT,ctschqbookVO.NUM_OF_CHQBOOKS:num_of_chqbooks_Q000MT,ctschqbookVO.NUMBER_OF_CHEQUES:number_of_cheques_Q000MT,ctschqbookVO.FROM_NUMBER:from_number_Q000MT,ctschqbookVO.NUMBER_TO:number_to_Q000MT,ctschqbookVO.BRANCH_CODE:BRANCH_CODE_Q000MT,ctschqbookVO.ACC_BR:acc_br_Q000MT,ctschqbookVO.ACC_CY:acc_cy_Q000MT,ctschqbookVO.ACC_GL:acc_gl_Q000MT,ctschqbookVO.ACC_CIF:acc_cif_Q000MT,ctschqbookVO.ACC_SL:lookuptxt_acc_sl_Q000MT,ctschqbookVO.CODE:code_Q000MT,ctschqbookVO.LEAVES:lookuptxt_leaves_code_Q000MT,chqserial_type:chqserial_type_Q000MT,crud:crud_Q000MT,iv_crud:iv_crud_Q000MT</value>
      <webElementGuid>e6ed3e55-7316-4e8f-b9be-2f5967dcff2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Number of ChequeBooks</value>
      <webElementGuid>b932c98b-00f3-4792-8ada-4e56995a7b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>number_of_chequebooks_key</value>
      <webElementGuid>fa988556-540c-4a93-9976-4b06d91752b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Number of ChequeBooks</value>
      <webElementGuid>813e6e76-0460-4040-97b5-b4f73a83b50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;num_of_chqbooks_Q000MT&quot;)</value>
      <webElementGuid>db7b58ea-70ab-4d64-b2f3-89f1b1709735</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='num_of_chqbooks_Q000MT']</value>
      <webElementGuid>d54cd24b-4f5a-44ce-ac6f-7d78f203316f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='chequeBookDefFormId_Q000MT']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>ee39d0c7-b8e9-4406-8298-09b50587bd09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr/td[2]/div/input</value>
      <webElementGuid>4aa3c384-47f0-4e5d-87dd-b17eca2be2e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'chequeBookCO.ctschqbookVO.NUM_OF_CHQBOOKS' and @id = 'num_of_chqbooks_Q000MT' and @title = 'Number of ChequeBooks']</value>
      <webElementGuid>2a98f6ad-1ae2-4b4e-8219-0fe99c3bf4f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
