<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_amfVO.CIF_SUB_NO</name>
   <tag></tag>
   <elementGuidId>c09b44a5-2cae-4672-a8e2-83a73d1b5ead</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_acc_sl_Q000MT_gs_amfVO.CIF_SUB_NO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>92ba6092-1ac3-4405-abb3-f20816f3a12d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f73b6d4a-2ca7-47b9-8f53-ad2da8c7e2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amfVO.CIF_SUB_NO</value>
      <webElementGuid>cf81acf5-fad8-45ed-a7b4-44501ecbda6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_acc_sl_Q000MT_gs_amfVO.CIF_SUB_NO</value>
      <webElementGuid>5f4429ef-d06b-4341-994c-3f97c9cad4f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_acc_sl_Q000MT_gs_amfVO.CIF_SUB_NO&quot;)</value>
      <webElementGuid>c65b00e9-7184-4845-b4b7-c7a0e8e8418b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_acc_sl_Q000MT_gs_amfVO.CIF_SUB_NO']</value>
      <webElementGuid>654607e9-21e2-4d46-81b6-bf9c5511c32d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_acc_sl_Q000MT']/div[2]/div/table/thead/tr[2]/th[5]/div/input</value>
      <webElementGuid>eda24b7d-9f80-49bf-b9d0-c114bc9e5676</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[3]/div[2]/div/table/thead/tr[2]/th[5]/div/input</value>
      <webElementGuid>0bbe2f1b-041e-4ff0-9790-857911b9bb70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'amfVO.CIF_SUB_NO' and @id = 'gridtab_acc_sl_Q000MT_gs_amfVO.CIF_SUB_NO']</value>
      <webElementGuid>c5a652a1-df76-4d0a-86ad-960313f57a0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
