<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_3037 GL Code not specified for this c_c34c59</name>
   <tag></tag>
   <elementGuidId>c5975a83-dbd4-48ce-9093-d2128e8b3025</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_popup_path_sol_ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_popup_path_sol_ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74f6666f-ceab-4b8b-9b37-e7786539d8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4cd49a34-7f79-4d24-8bf5-a778421b9e44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_popup_path_sol_ok</value>
      <webElementGuid>1266038a-b791-4472-8390-7468d940b8a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text fg-button ui-button ui-corner-all ui-widget ui-state-default ui-button-text-only</value>
      <webElementGuid>643bf0cc-3ede-41b0-9c2b-0cea7166ebd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>ba1d55a2-cdfb-4022-8207-ace14a7ab6b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_popup_path_sol_ok&quot;)</value>
      <webElementGuid>6ce1f559-1f01-467e-b15b-e6cf4513351a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_popup_path_sol_ok']</value>
      <webElementGuid>bd7b04db-6380-47a0-894b-634dfc924243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div__popup_path_sol_ok']/center/input</value>
      <webElementGuid>18e9762b-8a6a-468c-bdc4-6586fa0f04e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/input</value>
      <webElementGuid>3f10f73e-767d-49e2-81bd-5b6d87e3d8fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_popup_path_sol_ok']</value>
      <webElementGuid>f32e6ad0-f0d8-4874-af97-9ada492e1916</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
