<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BRIEF_NAME_ENG</name>
   <tag></tag>
   <elementGuidId>a3771520-c337-4b7d-bd2e-1c667d4fbaef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridtab_CHEQUE_CODE_Q000MT_gs_BRIEF_NAME_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_CHEQUE_CODE_Q000MT_gs_BRIEF_NAME_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d04da654-34c9-45b1-9e9f-182ef3c40359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0efb7673-36fc-497e-b5c3-5ea9d7bc1b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRIEF_NAME_ENG</value>
      <webElementGuid>09595976-5384-4f92-99f5-beb85a5b7749</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_CHEQUE_CODE_Q000MT_gs_BRIEF_NAME_ENG</value>
      <webElementGuid>96e293c5-00ff-4e35-a8bc-a83476c0301a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_CHEQUE_CODE_Q000MT_gs_BRIEF_NAME_ENG&quot;)</value>
      <webElementGuid>649e77c3-42ac-449f-ab67-57f3ecbb2a85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_CHEQUE_CODE_Q000MT_gs_BRIEF_NAME_ENG']</value>
      <webElementGuid>62a8925d-87c3-46e2-9631-0468ac7873cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_CHEQUE_CODE_Q000MT']/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>82bdb278-44d3-467b-a8d9-536552e61a07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div[3]/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>3e0e75de-9cef-40f6-ad8f-ab410e1bdd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRIEF_NAME_ENG' and @id = 'gridtab_CHEQUE_CODE_Q000MT_gs_BRIEF_NAME_ENG']</value>
      <webElementGuid>660ec2d3-fc33-4cad-bee3-e0c1be204720</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
