<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Save</name>
   <tag></tag>
   <elementGuidId>116fb8ed-8742-45eb-b2fd-b6f8a228f31b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chequeBookDefFormId_Q000MT_btn_save</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='chequeBookDefFormId_Q000MT_btn_save']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>d5fce4e5-df3f-4041-960d-0f6ba7d7bb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chequeBookDefFormId_Q000MT_btn_save</value>
      <webElementGuid>cb88b70b-1d38-4a2e-b56a-38c000cdffe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chequeBook_save_Q000MT</value>
      <webElementGuid>e064c8e7-92d4-4e75-97f5-bb974e959b84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>btn.save</value>
      <webElementGuid>16fdab5e-72bd-4f69-891e-84c4110dd60a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>022df564-9cb0-4449-85a4-69a02b564b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save </value>
      <webElementGuid>5a8f3bd4-1d95-42c4-8398-a171fea2a4b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chequeBookDefFormId_Q000MT_btn_save&quot;)</value>
      <webElementGuid>50df72ad-5d9d-4297-8657-0b58468ec7cd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='chequeBookDefFormId_Q000MT_btn_save']</value>
      <webElementGuid>768d5f9c-1629-4484-8450-90048e6fad55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='chequeBook_save_Q000MT']/span/label</value>
      <webElementGuid>6e6cd355-c7a2-4120-b66b-c4a30550c082</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges'])[1]/following::label[1]</value>
      <webElementGuid>863282a9-e271-4288-aaa1-9a035fb91b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::label[1]</value>
      <webElementGuid>f42ba3b5-a5b0-46b6-a18f-5ddb73a6e5c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright'])[1]/preceding::label[1]</value>
      <webElementGuid>c992c282-a39e-40cf-b880-3d363f5f1814</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>18b9484a-6681-4992-bea3-5974a4f6f4d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>840eaa56-e96c-4631-9a59-d53b6fe3c408</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'chequeBookDefFormId_Q000MT_btn_save' and (text() = 'Save ' or . = 'Save ')]</value>
      <webElementGuid>f217408b-d457-4060-a595-8838e89d2c68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
