<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_50 leaves Individual</name>
   <tag></tag>
   <elementGuidId>e993eace-c666-419b-8f25-35bbb7940069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_CHEQUE_CODE_Q000MT_1_BRIEF_NAME_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_CHEQUE_CODE_Q000MT_3_BRIEF_NAME_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>758594da-7173-47d6-92a9-1bf6ed944578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>cd543831-7b49-4187-8fe9-9035c227d973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>25 leaves Individual</value>
      <webElementGuid>f0fece1d-9d09-4155-abcd-58b91e01c980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>70523a25-6661-4c0a-b58e-a76c96d090a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_CHEQUE_CODE_Q000MT_BRIEF_NAME_ENG</value>
      <webElementGuid>9e4ccc47-e70e-4f63-801f-63fc62ff3291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_CHEQUE_CODE_Q000MT_1_BRIEF_NAME_ENG</value>
      <webElementGuid>c790ea61-b249-4f53-8319-83032a6ceffd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>25 leaves Individual</value>
      <webElementGuid>85945a40-4c40-48ad-8267-1e0695efc6ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_CHEQUE_CODE_Q000MT_1_BRIEF_NAME_ENG&quot;)</value>
      <webElementGuid>785f73f0-2bb7-4f3d-86be-cf1dcd76b542</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_CHEQUE_CODE_Q000MT_1_BRIEF_NAME_ENG']</value>
      <webElementGuid>c0ab6f0b-61d0-4516-b62d-b8fd55e332ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[2]</value>
      <webElementGuid>f615452d-fd93-4837-9218-adbe63495c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف المختصر'])[1]/following::td[6]</value>
      <webElementGuid>783eace0-d817-4d82-a749-cf4b245336f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Long Description'])[1]/following::td[6]</value>
      <webElementGuid>73e8f847-da21-43a2-b0c4-2e1182700790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[2]/preceding::td[22]</value>
      <webElementGuid>7c130f60-4570-4afb-91e2-813c2b6a7c4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[2]/preceding::td[24]</value>
      <webElementGuid>2cc17f6f-4de1-4b81-ba73-95552a3cce89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='25 leaves Individual']/parent::*</value>
      <webElementGuid>57e7e0ae-2a1b-479a-b84e-204f76c49762</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>2facb56d-98f3-4de8-a7ea-362793c22536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '25 leaves Individual' and @id = 'td_gridtab_CHEQUE_CODE_Q000MT_1_BRIEF_NAME_ENG' and (text() = '25 leaves Individual' or . = '25 leaves Individual')]</value>
      <webElementGuid>7faa7519-5f12-475f-87b1-b8e29d68f7fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
