<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Current Account</name>
   <tag></tag>
   <elementGuidId>a9845086-e75b-403f-b4fd-5b5dd2162efe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_acc_sl_Q000MT_2_glVO.BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>98912ac4-08a4-4e51-84ec-25eb2591a99e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>15980fe2-613a-4048-a30e-70f402081d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Current Account</value>
      <webElementGuid>939387d5-9906-4a3d-a1c1-130d182c89df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>GL Brief Name</value>
      <webElementGuid>d6a107ed-68c1-405b-a6dc-657a2f1ba7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_acc_sl_Q000MT_glVO.BRIEF_DESC_ENG</value>
      <webElementGuid>eab2794b-e42c-48bb-b957-e90bcfe97a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_acc_sl_Q000MT_2_glVO.BRIEF_DESC_ENG</value>
      <webElementGuid>03f25e89-2a9d-4893-a768-c726ab2eac30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Current Account</value>
      <webElementGuid>5f310439-8148-479c-a55f-76cff41ab5ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_acc_sl_Q000MT_2_glVO.BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>da297796-e70e-4b6f-8db2-ac75b010bfb0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_acc_sl_Q000MT_2_glVO.BRIEF_DESC_ENG']</value>
      <webElementGuid>e1b54589-0c6b-4342-bf80-3590044e4fe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='2']/td[4])[2]</value>
      <webElementGuid>ef7e24e1-7030-429d-a654-757c81a273ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/following::td[4]</value>
      <webElementGuid>c02211d3-ed0b-428e-891a-28d87c0e1ada</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEV PATEL P P'])[6]/following::td[5]</value>
      <webElementGuid>9529fc9e-5ebd-409b-a138-6d7487158f51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEV PATEL P P'])[7]/preceding::td[3]</value>
      <webElementGuid>672745a2-e61f-42fe-9e7a-06d34a7f9fd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DEV PATEL P P'])[8]/preceding::td[4]</value>
      <webElementGuid>4d82a006-10e4-4133-91d7-0fcf2651b035</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Current Account']/parent::*</value>
      <webElementGuid>41a28231-23eb-45a8-a4b1-f6843cf19326</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[3]/div[3]/div/table/tbody/tr[3]/td[4]</value>
      <webElementGuid>b381801c-e28b-49b6-a9be-afa10e95f39d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Current Account' and @id = 'td_gridtab_acc_sl_Q000MT_2_glVO.BRIEF_DESC_ENG' and (text() = 'Current Account' or . = 'Current Account')]</value>
      <webElementGuid>5d4bff9e-2a1b-49f2-bf4f-c9a04c1149fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
