<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_To Be Reversed</name>
   <tag></tag>
   <elementGuidId>73822648-575b-402f-a6c4-0ca0ad04911e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#submit_1778074920 > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='submit_1778074920']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>0ac5caf1-45ca-4ac8-a976-0fa20b638214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>c6abc485-93c4-4aaf-b66a-c97dd8a4c56f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> To Be Reversed 
</value>
      <webElementGuid>50d1ffab-d66a-4352-91ee-e2da19087892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;submit_1778074920&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>62ae4050-530c-4fa3-a522-caad324054d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='submit_1778074920']/span</value>
      <webElementGuid>88d35d8b-bbfe-4ab2-a86c-c77e094e76d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records to view'])[1]/following::span[1]</value>
      <webElementGuid>cc64b92c-bb6c-4adc-afde-fe78b24d9f98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[2]/following::span[1]</value>
      <webElementGuid>0c2e3b51-6df1-4e1b-a7cd-4b4c3cc618fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright'])[1]/preceding::span[1]</value>
      <webElementGuid>6f4bb5be-6fce-43bd-a958-c5232181e547</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='To Be Reversed']/parent::*</value>
      <webElementGuid>75b9ea6c-c3a2-4ca8-91e8-72714d0f5272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>1fe00bb4-7d4c-483b-8a21-d9fe8c0fe720</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' To Be Reversed 
' or . = ' To Be Reversed 
')]</value>
      <webElementGuid>5b02d5d2-6396-4070-aa7b-8d399658e852</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
