<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_7133</name>
   <tag></tag>
   <elementGuidId>cebcfb39-b11e-432a-bab5-fe1869aa7ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_transferCashGridTbl_Id_L0VVTR_1_trxNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_transferCashGridTbl_Id_L0VVTR_1_trxNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5e78381b-532b-4f7a-bcde-ffcd768671e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>c407012f-3c5a-4d11-a626-884e1ab4adf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>b8157765-33ff-4e7a-9cef-fdba9d88eeb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>7133</value>
      <webElementGuid>c0383274-ddc0-4486-bf82-cf863dca4594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Trx No</value>
      <webElementGuid>87773583-5b7f-4d5c-9834-24582fd6fe2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>transferCashGridTbl_Id_L0VVTR_trxNo</value>
      <webElementGuid>dc744cde-1800-4935-be11-68e76d9dd0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_transferCashGridTbl_Id_L0VVTR_1_trxNo</value>
      <webElementGuid>a4b1187d-9d6d-418c-b6dd-0e382a861916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7133</value>
      <webElementGuid>a2fc9f30-f31c-4af2-b523-5835294737a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_transferCashGridTbl_Id_L0VVTR_1_trxNo&quot;)</value>
      <webElementGuid>d30d3a4f-e19d-4dd0-885e-cf3ad558e1d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_transferCashGridTbl_Id_L0VVTR_1_trxNo']</value>
      <webElementGuid>d745e5fc-6bc9-4193-8146-2d0596acce4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td)[8]</value>
      <webElementGuid>4a08b4d9-b4ee-493e-9554-a837e3e217b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trade Date'])[2]/following::td[8]</value>
      <webElementGuid>e56d6cdb-df46-4dfc-8270-19f5fbb7a9ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::td[8]</value>
      <webElementGuid>62e7668e-64a0-4894-b25f-43334886f9dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[3]/preceding::td[2]</value>
      <webElementGuid>66bc5806-9a1b-4298-b1ea-18c4b98cdbfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[4]/preceding::td[4]</value>
      <webElementGuid>b74272aa-85f9-43aa-bde7-ddc3efff7124</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7133']/parent::*</value>
      <webElementGuid>aa303ebc-ba75-4ddd-9ee6-91e35aed4e52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/table/tbody/tr/td/div/div[3]/div[3]/div/table/tbody/tr[2]/td</value>
      <webElementGuid>6ab3415d-5734-4cc8-ac7c-6684d56104d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '7133' and @id = 'td_transferCashGridTbl_Id_L0VVTR_1_trxNo' and (text() = '7133' or . = '7133')]</value>
      <webElementGuid>89318b8d-c571-45ca-88ca-6a6983690137</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
