<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Maintenance</name>
   <tag></tag>
   <elementGuidId>46c02cfc-c228-4ed6-b7cb-10c8b059ea29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L0VVMT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='L0VVMT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f0bc6dd8-31c9-455f-a648-da902a0bfcf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>L0VVMT</value>
      <webElementGuid>029233fa-5e77-4471-b911-edf718f1db34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6376ddb9-6329-4440-a8d4-610eee11458e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:addMenuTab('L0VVMT','Maintenance','RET','L0VV' )</value>
      <webElementGuid>ddff462c-391d-4697-bd9a-1728108edab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-selected-menu-cupertino path-selected-menu</value>
      <webElementGuid>c5316e89-0bb5-4eea-a088-88423bf93506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maintenance	</value>
      <webElementGuid>6c983f08-9ddf-4945-acb7-d21ab94fc4d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L0VVMT&quot;)</value>
      <webElementGuid>459636f0-e0a6-479e-a3c4-8ca594683ac9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='L0VVMT']</value>
      <webElementGuid>00ffb335-4292-41a1-87bd-6a75aaad7b9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_selenuimL0VVMT']/li/a</value>
      <webElementGuid>f04bdf98-017d-4ddb-a1f4-a62f7561df6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Cash From Vault to Vault'])[1]/following::a[1]</value>
      <webElementGuid>8c591391-b78f-41fa-a219-196926094bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Teller Cash Balance'])[2]/following::a[2]</value>
      <webElementGuid>3ffb70d7-bb4b-438f-81f4-f8609a7448d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reverse'])[1]/preceding::a[1]</value>
      <webElementGuid>35191a51-7336-417d-86a0-051b82aab14e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>c4748156-b485-428c-bdad-1c42e696489d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/div/li/a</value>
      <webElementGuid>5071811b-5fbb-48a9-8724-e9b0c21dbf6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'L0VVMT' and @href = '#' and (text() = 'Maintenance	' or . = 'Maintenance	')]</value>
      <webElementGuid>24592303-8829-44ad-80c5-91748dc85413</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
