<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Available Bills_1_ctstellerCashBalanc_902eb5</name>
   <tag></tag>
   <elementGuidId>cf0dfaa7-715b-46ea-bc1b-55bbc46e88a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4a9ab838-660e-4b98-a2bb-d400bed7b494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3812bcfa-72c0-4eaa-b7bc-195e4a16e0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colmodel</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>13f4f4a2-48f2-49c6-b1fd-fc82825ab4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>644f57b5-c2a0-44e9-94d7-456f9dc3c538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT</value>
      <webElementGuid>d02a381d-4499-4685-a2eb-11f9ea4f1dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gridid</name>
      <type>Main</type>
      <value>trsfrCashcyDenomGridTbl_Id_L0VVMT</value>
      <webElementGuid>b280df85-9502-4527-b718-d90f2fe7763e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>e48caa2c-5f80-460d-8754-286254c86ebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>1674e2b4-4e32-4a02-aedb-11f13e0312ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cyDenomCommonCO.trsCurrencyDetCO.ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS:ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS,cyDenomCommonCO.trsCurrencyDetCO.comp_amt:comp_amt</value>
      <webElementGuid>bebaffd6-3739-475f-a689-64928f35fefc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/transfercash/transferCashCyDenomAction_dependencyByCountedNbBills?iv_crud=&amp;amp;_pageRef=L0VVMT</value>
      <webElementGuid>046558fd-3046-4914-a79a-e2555dce132c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>params</name>
      <type>Main</type>
      <value>cyDenomCommonCO.trsCurrencyDetCO.ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS:ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS,cyDenomCommonCO.trsCurrencyDetCO.avail_bills:avail_bills,cyDenomCommonCO.trsCurrencyDetCO.ctstellerCashBalanceCyNomVO.VALUE:ctstellerCashBalanceCyNomVO.VALUE,cyDenomCommonCO.trsfrType:cyDenomTrsfrType_L0VVMT</value>
      <webElementGuid>d88a47fd-ae6c-4864-9817-5cb10cb6ffe5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>recalculateTotalAmount()</value>
      <webElementGuid>b239ea3d-6205-486b-ba3e-359f61237584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT&quot;)</value>
      <webElementGuid>7be5d6d4-d827-486c-b1c3-952525088b11</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT']</value>
      <webElementGuid>285508ba-46e1-4336-bc5a-2114d6244804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS']/div/input</value>
      <webElementGuid>c5305040-29ca-4ef1-9a27-bbde8b815b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>fb082e99-ff58-42d6-b6c9-24a32c24e365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT']</value>
      <webElementGuid>c3f7991f-ec73-429a-9bdc-c8dc6bdb389c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
