<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1048 Withdrawal amount exceeds availa_6a5caa</name>
   <tag></tag>
   <elementGuidId>b27ca5c9-409d-4b92-a7d2-34c4217798e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_popup_path_sol_ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_popup_path_sol_ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d02e9ce2-21af-47fb-9428-76cba0568953</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>26442e71-e411-4409-8435-130cee5c36a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_popup_path_sol_ok</value>
      <webElementGuid>2099e139-19de-4266-b5c8-5950427ff145</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text fg-button ui-button ui-corner-all ui-widget ui-state-default ui-button-text-only</value>
      <webElementGuid>5e36ab1e-827a-456a-a6e8-4617bb9467a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>d657d15e-4edf-44cb-93b7-a240aecf6cd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_popup_path_sol_ok&quot;)</value>
      <webElementGuid>0ab7a78f-3450-452e-b587-efb5a9fd0191</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_popup_path_sol_ok']</value>
      <webElementGuid>abcf3e38-91e0-4b66-be2b-b4cac47e89b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div__popup_path_sol_ok']/center/input</value>
      <webElementGuid>da4ce33f-2497-4237-92db-fb6273feba9a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/input</value>
      <webElementGuid>04231d13-3619-4b10-b474-afbfd16eb7fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_popup_path_sol_ok']</value>
      <webElementGuid>19059df7-3b68-4ec8-9fed-8dece7847d19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
