<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Available Bills_8_ctstellerCashBalanc_9e9fc9</name>
   <tag></tag>
   <elementGuidId>37d5d248-6e1e-4848-986a-f9c8fffcc03c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d8a7f41-c17e-4b02-a710-acef631afaec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4632253e-648c-4d1e-8077-2a5be0a50b91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colmodel</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>ce71e5d4-82b7-4901-aa8e-08df08c2ec16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>19dee242-f702-4769-a24b-6c07e17bb094</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT</value>
      <webElementGuid>2876998a-34bf-40c7-a8cb-dc36419b16f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gridid</name>
      <type>Main</type>
      <value>trsfrCashcyDenomGridTbl_Id_L0VVMT</value>
      <webElementGuid>c1999d23-1873-40b8-b45e-4259525d5d51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>2ab33296-717d-4ee9-b110-2b38e388b012</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>22bb7fed-c0af-4dfb-8d43-1f5793522e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cyDenomCommonCO.trsCurrencyDetCO.ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS:ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS,cyDenomCommonCO.trsCurrencyDetCO.comp_amt:comp_amt</value>
      <webElementGuid>3f5a6eec-c8c7-48bf-9476-2258dfb45770</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/transfercash/transferCashCyDenomAction_dependencyByCountedNbBills?iv_crud=&amp;amp;_pageRef=L0VVMT</value>
      <webElementGuid>174e3f9c-7f3a-4cd9-be07-b4a984596b65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>params</name>
      <type>Main</type>
      <value>cyDenomCommonCO.trsCurrencyDetCO.ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS:ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS,cyDenomCommonCO.trsCurrencyDetCO.avail_bills:avail_bills,cyDenomCommonCO.trsCurrencyDetCO.ctstellerCashBalanceCyNomVO.VALUE:ctstellerCashBalanceCyNomVO.VALUE,cyDenomCommonCO.trsfrType:cyDenomTrsfrType_L0VVMT</value>
      <webElementGuid>3bed394b-63e9-48cc-93cd-a487c0066a1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>recalculateTotalAmount()</value>
      <webElementGuid>74c1e0c2-6a22-4875-8756-9533d71e9fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT&quot;)</value>
      <webElementGuid>65c6e893-a49f-4a5d-af9e-e44594659bc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT']</value>
      <webElementGuid>096d8db4-2df8-4b1c-893c-586774af0199</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='td_trsfrCashcyDenomGridTbl_Id_L0VVMT_8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS']/div/input</value>
      <webElementGuid>62abecbc-ebc3-4189-9192-af242efd44e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>b1522ee2-5a0c-4b0b-816d-dc863dd7ece4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT']</value>
      <webElementGuid>8340aebb-a04f-40bb-9c98-08dd1bef55d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
