<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit_BRIEF_DESC_ENG_1</name>
   <tag></tag>
   <elementGuidId>4ee77d09-a074-4a87-a351-0a20fc99bb08</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf3809e9-0d40-4f2b-8ac0-2e44fbb30976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>cf19e02f-8e44-4d43-a876-52b720f37c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRIEF_DESC_ENG</value>
      <webElementGuid>bb011c85-6585-4a4a-a93d-e2e7603cf520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG</value>
      <webElementGuid>7c5fe999-7972-4cd5-bc15-7fe2e1bec914</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>b0d5508a-5e9d-4130-8289-fa35403cf65d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>86cb4dd4-1b51-4b85-b8dd-d0e0329449e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT']/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>bb96cae8-0288-4800-aaeb-958822c45cbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]/div/div[3]/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>59c4a7c8-1de9-4b21-b42d-70b4ea69691f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRIEF_DESC_ENG' and @id = 'gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>97be22aa-50e4-4c5c-a006-47f61d725a75</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
