<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit_BRIEF_DESC_ENG</name>
   <tag></tag>
   <elementGuidId>487d4593-eb0b-4858-aaa3-e6bc1afcab99</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bed773ef-51d7-433a-b9ad-05a810008cc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>117013c8-a771-410e-9f30-3c3b635749ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRIEF_DESC_ENG</value>
      <webElementGuid>e2481433-cba6-422a-9b92-116869ede25d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG</value>
      <webElementGuid>a7f4adf0-97c8-4a7d-a5cd-8472c0457e9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>18d2e3d6-8af0-4d9c-95fe-e664e178a269</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>da0e1e4a-19c4-4916-837e-d97f06d992f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT']/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>1438c16c-9af6-4ae2-8548-93200d9b5fd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div[3]/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>81832368-69fd-45eb-b82a-a6b30347f860</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRIEF_DESC_ENG' and @id = 'gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>d5f6d110-7ecd-4f46-9904-79bd58894938</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
