<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__ui-icon ui-icon-search live-search-ui_1_2</name>
   <tag></tag>
   <elementGuidId>e476522f-0d24-4f41-b5a1-160d0f884f33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spanLookup_trxTypeLookup_L0VVMT > span.ui-icon.ui-icon-search.live-search-ui</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanLookup_trxTypeLookup_L0VVMT']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>78d6bfc8-751d-48cb-99d8-3e26236d9127</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-search live-search-ui</value>
      <webElementGuid>d9e76592-c56b-4c23-858d-f97cac804b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanLookup_trxTypeLookup_L0VVMT&quot;)/span[@class=&quot;ui-icon ui-icon-search live-search-ui&quot;]</value>
      <webElementGuid>1a591900-7469-4c35-a6d4-ad6c980a0538</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='spanLookup_trxTypeLookup_L0VVMT']/span</value>
      <webElementGuid>697d805f-2034-4225-b979-27fac68a759f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/div/table/tbody/tr/td/div/span/span</value>
      <webElementGuid>69242ee6-87a5-48fa-81f3-bcf9c78fe574</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
