<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span__ui-icon ui-icon-search live-search-ui_1</name>
   <tag></tag>
   <elementGuidId>988db56f-a2a3-4254-a652-6790edae5469</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spanLookup_tellerLookup_L0VVMT > span.ui-icon.ui-icon-search.live-search-ui</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanLookup_tellerLookup_L0VVMT']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>90895478-19ec-41c6-9527-a5fa4fd17753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-search live-search-ui</value>
      <webElementGuid>dfa58ca1-5d74-456e-9e86-b111cd755ead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanLookup_tellerLookup_L0VVMT&quot;)/span[@class=&quot;ui-icon ui-icon-search live-search-ui&quot;]</value>
      <webElementGuid>07d1098e-2780-43b1-8b66-24b6e6245cc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='spanLookup_tellerLookup_L0VVMT']/span</value>
      <webElementGuid>02a4d3c2-3071-463a-b5d9-37db85c0734c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/table/tbody/tr/td/div/table/tbody/tr/td/div/span/span</value>
      <webElementGuid>bd6aed3b-b50c-4edb-b9d1-e052fe5b29e6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
