<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_</name>
   <tag></tag>
   <elementGuidId>87245236-fda0-4ec4-9231-506911bad344</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e4eb96a4-beb1-4715-8def-5660be72deba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>33d19d6e-49fc-44cb-bf29-b07513c729b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Currency</value>
      <webElementGuid>5e8ea8ff-c761-451b-a0ed-61d097ff9d40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>transferCashSubCashGridTbl_Id_L0VVMT_ctstellerCashBalanceDetVO.CURRENCY_CODE</value>
      <webElementGuid>aede7bd5-3ef8-4579-b8c0-3f5cf3dbc739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE</value>
      <webElementGuid>9f409264-59c6-41e1-816f-7793c63c0d4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>61c87290-4b79-455e-ad79-d81dbebe276b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE&quot;)</value>
      <webElementGuid>295ace5f-3eb9-4806-b598-487300ccacc8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE']</value>
      <webElementGuid>0a5ff7cd-4a4f-4da1-a6c2-9b4e2699b83c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='new_1655900372172']/td[2]</value>
      <webElementGuid>f3cbce6c-573c-42c5-bcaf-99d8e987d019</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decimal Points'])[1]/following::td[16]</value>
      <webElementGuid>202389be-5c49-4ae6-89cb-e24cbdd3ff2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JV OP.No'])[1]/following::td[16]</value>
      <webElementGuid>59b8e915-943d-4162-a918-3fd8082a5cae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::td[32]</value>
      <webElementGuid>dbf24804-1fb4-4433-889f-85aecf2c0ad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[34]</value>
      <webElementGuid>cb816917-827e-4219-9c6d-513478fd8685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>ca768fe5-eef4-4e59-92ee-78868b5a6f93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>88420094-941c-478e-92d7-6a2565e1b53c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
