<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Available Bills_td_trsfrCashcyDenomGridT_fdc918</name>
   <tag></tag>
   <elementGuidId>f24a92a4-feb3-47ab-b4f8-cb86ac7c2d05</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>36b3d600-1016-44cd-b973-850a355000c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>cc3e0e7f-1207-410a-b4c1-09e662a1b3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>62febd83-7abf-4384-8731-fcd222f14561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Number Of Bills</value>
      <webElementGuid>42d78f9e-a250-4852-9df6-8fdbfc79331e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>trsfrCashcyDenomGridTbl_Id_L0VVMT_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS</value>
      <webElementGuid>85d27b4a-dcde-478b-a2f5-adaa0f1350e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS</value>
      <webElementGuid>2b95566b-ec15-4465-a936-711821b8e093</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS&quot;)</value>
      <webElementGuid>561ee259-c7d5-4422-a90c-e31dac70d671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS']</value>
      <webElementGuid>f29c7dc9-dde5-494b-a0b2-8e5545a96561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[8])[4]</value>
      <webElementGuid>e59d9d7e-4868-45c5-a099-03e2f377e743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Bills'])[1]/following::td[18]</value>
      <webElementGuid>8e5d46ac-2a3c-4957-bc4d-de758f0ff14b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[2]/following::td[18]</value>
      <webElementGuid>5bd361eb-940c-4397-92d1-7a348ad37b12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[7]/preceding::td[88]</value>
      <webElementGuid>75f16064-b905-4038-ad7e-51c638191c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[7]/preceding::td[90]</value>
      <webElementGuid>27eceda3-d70d-46a3-ac21-ab65d3af40ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div[3]/div/table/tbody/tr[2]/td[8]</value>
      <webElementGuid>e9d2fbb4-ed33-4ca1-9d27-97e05ad67bb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS']</value>
      <webElementGuid>29dc1ace-1246-47e1-9b8a-1b8605c98544</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
