<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Available Bills_td_trsfrCashcyDenomGridT_0df559</name>
   <tag></tag>
   <elementGuidId>da448efd-992d-4b80-affa-69af9218075d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_trsfrCashcyDenomGridTbl_Id_L0VVMT_8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>883b0016-cc72-4943-9f9a-949ba544ac70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>37d6e811-f7a9-4b81-99c1-95fc23c73bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>a265d788-c4d1-4e4e-95fa-3b776f1da95d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Number Of Bills</value>
      <webElementGuid>b2826691-2b9f-4110-a5a5-82fbcb6db872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>trsfrCashcyDenomGridTbl_Id_L0VVMT_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS</value>
      <webElementGuid>2e973bab-5b9e-42d4-8f24-63f6526244f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_trsfrCashcyDenomGridTbl_Id_L0VVMT_8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS</value>
      <webElementGuid>c4a372cf-7fe3-4426-84b1-79940d857b8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_trsfrCashcyDenomGridTbl_Id_L0VVMT_8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS&quot;)</value>
      <webElementGuid>b70b0901-418b-4583-b6b8-347d4de2e07a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_trsfrCashcyDenomGridTbl_Id_L0VVMT_8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS']</value>
      <webElementGuid>3d8fe152-ec8b-4b2d-96e6-c89ffc8b2d35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='8']/td[8]</value>
      <webElementGuid>5911f718-222c-40f8-8136-16bf82f8cab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Bills'])[1]/following::td[88]</value>
      <webElementGuid>24e15053-f6c2-4984-b507-95bcd6980ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[2]/following::td[88]</value>
      <webElementGuid>3aa6456c-c969-4cbc-869f-2f113ddee0ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[7]/preceding::td[18]</value>
      <webElementGuid>e7764f4e-d353-42f9-96d5-14a3b2213846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[7]/preceding::td[20]</value>
      <webElementGuid>055de71c-2ae9-43c9-8f07-f67a8fb0e682</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[8]</value>
      <webElementGuid>a9ccfdcf-8b57-473b-aff2-59a1d24789e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'td_trsfrCashcyDenomGridTbl_Id_L0VVMT_8_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS']</value>
      <webElementGuid>e73bfa53-0268-468c-a633-091dd84a2b89</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
