<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AED_1</name>
   <tag></tag>
   <elementGuidId>f110db0a-66df-4f48-8f6b-7dd5ad805810</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@title=&quot;784&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9576cbd1-5272-4ddd-9baf-55a4d49da2db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>9a68ae2a-6b75-4354-9d51-58d67ce338b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AED</value>
      <webElementGuid>e2e1753e-74d7-4dae-9593-277386241fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>00d47c29-d5db-4250-af4a-9303d5ff865a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_BRIEF_DESC_ENG</value>
      <webElementGuid>0543b68b-7d20-45f4-8f0c-f20cdd9c4602</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>c4d23095-0cb1-4cc7-940b-7a7d3f362b55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AED</value>
      <webElementGuid>f8d6bea3-9714-4c84-a4f5-952fff6c525f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>54ae5ae6-dbdb-4049-9fd6-1f008a9196d9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>14ad84ec-951c-4123-a029-6988f24d319f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[6]</value>
      <webElementGuid>f9352e6c-f772-499d-96e2-dddcf014c039</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit'])[2]/following::td[10]</value>
      <webElementGuid>62ba08a6-0152-4fa8-8038-bc84721b2c7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decimal Points'])[4]/following::td[10]</value>
      <webElementGuid>45a02943-281d-4918-b09a-76031df30568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='د.إ'])[2]/preceding::td[1]</value>
      <webElementGuid>173f581f-b72b-4899-adb8-2cc15556f4be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UAE Dirham'])[2]/preceding::td[2]</value>
      <webElementGuid>3c709749-de70-4e3c-9f38-e1b249af347e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[31]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>01ab7896-9cff-41d2-b83c-f950f1a13a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'AED' and @id = 'td_gridtab_new_1655900626013_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG' and (text() = 'AED' or . = 'AED')]</value>
      <webElementGuid>15a9755f-638b-4898-8c1a-9e4067c2e5bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
