<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_AED</name>
   <tag></tag>
   <elementGuidId>01f15240-1a6a-4f21-b7b3-c1f7abe0399b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5ce365d4-2e63-4413-9b4b-d65a70cb384b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>97c75e62-b76f-4dd0-8d37-95041ead6149</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>AED</value>
      <webElementGuid>f8e14cbd-26d6-4db1-847d-0cc55e5551c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>b5268a2e-d7fb-40eb-9de5-24246e199b87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_BRIEF_DESC_ENG</value>
      <webElementGuid>5f7b7b38-7216-45e6-adc3-c00850a1fcc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>f580600f-7162-415c-92d3-7477e74672ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AED</value>
      <webElementGuid>5b36a79b-8953-4ae5-9223-f503a96f0a3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>f40ec67f-1fdf-4d9c-a3f5-676c8278af93</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>c4b85109-1abc-4ca2-a6d1-3b4c77644b0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[5]</value>
      <webElementGuid>30f5acdf-df32-4ee4-8a3d-667029646618</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit'])[1]/following::td[10]</value>
      <webElementGuid>d2144fcf-b83e-4e5f-a6eb-db02554964c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decimal Points'])[3]/following::td[10]</value>
      <webElementGuid>fa6df777-3425-40c2-aae0-e55043ccafba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='د.إ'])[1]/preceding::td[1]</value>
      <webElementGuid>16f221f9-fc27-4f07-a96f-63bab285f9cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='UAE Dirham'])[1]/preceding::td[2]</value>
      <webElementGuid>ab2b69d7-bd4b-4990-a74f-79cd773dad90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='AED']/parent::*</value>
      <webElementGuid>3fd10dbe-f447-4ae4-8fdb-cb71a2f1412e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>75d1d79c-6011-4a05-b63f-f7625a2ff972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'AED' and @id = 'td_gridtab_new_1655900372172_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_1_BRIEF_DESC_ENG' and (text() = 'AED' or . = 'AED')]</value>
      <webElementGuid>9fe282d7-b55b-452f-b349-6b656b80d717</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
