<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_MUSCAT MAIN BRANCH</name>
   <tag></tag>
   <elementGuidId>b3bb9741-34fc-4909-be98-3287b12166bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>496e0917-893d-4324-acc6-09fb1f7974a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>431311fc-90b5-4b1e-add5-b47e11189b8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MUSCAT MAIN BRANCH</value>
      <webElementGuid>d2d765da-478d-492f-a573-5fc6aafd178b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>693b373e-2069-4226-9a46-030f61b41894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_vaultBranchLookup_L0VVMT_BRIEF_DESC_ENG</value>
      <webElementGuid>6a28ca80-5037-4602-99fc-ac4e49dfb846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>d5f747b3-8527-45ac-9c31-3cd7178bbff3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MUSCAT MAIN BRANCH</value>
      <webElementGuid>0762d2b7-97f5-4b4e-adf6-6ee530104c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>c4eea1ac-9c87-4a8a-b80d-d046a0eb9d83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>11d2ff5e-d1aa-4ecc-b380-b2fdc14b0f12</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[2]</value>
      <webElementGuid>00b553a4-27ed-4cb2-b572-507886318032</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark'])[1]/following::td[6]</value>
      <webElementGuid>f9efb200-5be6-4065-9a40-7dff2bca0ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Base Currency'])[1]/following::td[6]</value>
      <webElementGuid>cf0a2e4b-7fc3-4097-baed-09faee127fbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nizwa Branch'])[1]/preceding::td[4]</value>
      <webElementGuid>fa48ea74-d64d-4be5-91d5-80962c6fa6a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sohar Branch'])[1]/preceding::td[8]</value>
      <webElementGuid>f0e6b4f4-8d8e-478c-b538-a50398063fdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MUSCAT MAIN BRANCH']/parent::*</value>
      <webElementGuid>7f89bd1a-03a2-4faf-b4a8-7a26d9b49391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>1482ee76-87d2-4cca-9275-e4f35ead1b6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'MUSCAT MAIN BRANCH' and @id = 'td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG' and (text() = 'MUSCAT MAIN BRANCH' or . = 'MUSCAT MAIN BRANCH')]</value>
      <webElementGuid>f582b745-20a2-4089-a442-e1b7fdd5341c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
