<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Nizwa Branch</name>
   <tag></tag>
   <elementGuidId>cd5dc79a-2865-49c7-91ee-6d9214d7082f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_vaultBranchLookup_L0VVMT_2_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_vaultBranchLookup_L0VVMT_2_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6ccc8ac2-25cd-48e8-b75d-de48b1b343d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>6bcfb2c6-bfab-422e-8f17-05faf5cdaf9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Nizwa Branch</value>
      <webElementGuid>6bf875d6-daae-494f-8003-68ff82607a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>5c787f71-db4a-4a90-886f-4aecaa21b973</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_vaultBranchLookup_L0VVMT_BRIEF_DESC_ENG</value>
      <webElementGuid>ef4e942a-db00-432f-9d7e-5c8033a60fa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_vaultBranchLookup_L0VVMT_2_BRIEF_DESC_ENG</value>
      <webElementGuid>43b7b3d1-fbaa-4d2c-8b16-f4bf7152b0b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Nizwa Branch</value>
      <webElementGuid>01ea707d-38de-44fd-a4b0-f01c8393c9cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_vaultBranchLookup_L0VVMT_2_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>d79e8b76-3875-40e9-a23e-92225a20188c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_vaultBranchLookup_L0VVMT_2_BRIEF_DESC_ENG']</value>
      <webElementGuid>c5884c60-3c34-4d4d-9091-ded3aabdc222</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='2']/td[2])[4]</value>
      <webElementGuid>a3210c7f-dd56-4986-a9da-58622e052a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUSCAT MAIN BRANCH'])[1]/following::td[4]</value>
      <webElementGuid>a411736a-a54d-4a30-a41e-5ccea84b5b97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark'])[1]/following::td[10]</value>
      <webElementGuid>6757dc23-cd63-4c71-9a32-447c5affe345</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sohar Branch'])[1]/preceding::td[4]</value>
      <webElementGuid>4fe81412-4379-4748-a10c-02aa69348006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='AL KHOUDH BRANCH'])[1]/preceding::td[8]</value>
      <webElementGuid>753e9d8f-1930-4749-8739-f1bbc016974d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Nizwa Branch']/parent::*</value>
      <webElementGuid>4378098c-8fe1-41eb-8807-3ddfac3362bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[29]/div/div[3]/div[3]/div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>eb64574a-b6e1-4628-9573-6dbb859d5bbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Nizwa Branch' and @id = 'td_gridtab_vaultBranchLookup_L0VVMT_2_BRIEF_DESC_ENG' and (text() = 'Nizwa Branch' or . = 'Nizwa Branch')]</value>
      <webElementGuid>2fd5dfd4-b8d9-4068-90d5-3883b11da9b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
