<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Vault To Vault</name>
   <tag></tag>
   <elementGuidId>41244c98-1326-41c0-a0c9-6afaad5577a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f8206a28-29b4-448f-b20b-81881ddbac31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>152bf72a-0d94-4d5a-a83a-4fcdd22fbfbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Vault To Vault</value>
      <webElementGuid>b3873b79-0612-4b44-bdb8-4a61017b3269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>2c88f137-3a72-4722-8eba-d6f20233e518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_trxTypeLookup_L0VVMT_SHORT_DESC_ENG</value>
      <webElementGuid>ff80f08b-ead6-4b5f-a9b0-04c2fab8b584</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG</value>
      <webElementGuid>5878c095-9257-4209-a2ef-33af1db5f161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vault To Vault</value>
      <webElementGuid>2d433e0c-6612-49d0-821e-03c82727c3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG&quot;)</value>
      <webElementGuid>c7c0023f-e210-4a5b-a3a1-9817c000a63f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG']</value>
      <webElementGuid>a3a674d7-7a80-4cff-a6e4-4d1eb4b81bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='2']/td[2])[4]</value>
      <webElementGuid>ffa57453-9d03-427d-804f-7e3cc48d09bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحويل عام'])[2]/following::td[2]</value>
      <webElementGuid>33a89448-3f20-48b2-8c05-9edd2d4516d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحويل عام'])[1]/following::td[3]</value>
      <webElementGuid>7c0800de-d2b1-47e3-9f32-2974caab6e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vault To Vault'])[2]/preceding::td[1]</value>
      <webElementGuid>81439b63-48c6-4923-8521-b823f372862d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحويل من خزنة لأخرى'])[1]/preceding::td[2]</value>
      <webElementGuid>3d4b8f8d-98b5-4a5c-acd7-87641439559b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vault To Vault']/parent::*</value>
      <webElementGuid>7522829e-7999-42a7-a0bb-2cb25d47649e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div/div[3]/div[3]/div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>c35d68db-8d36-454b-a3a1-632ab4486e0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Vault To Vault' and @id = 'td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG' and (text() = 'Vault To Vault' or . = 'Vault To Vault')]</value>
      <webElementGuid>8cd187c3-6410-4100-a557-4a67d176ad9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
