<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reference3_key_TRS_AC_CIF</name>
   <tag></tag>
   <elementGuidId>34282e8a-8f51-4b8c-8a48-a16fefa48958</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_AC_CIF']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1b790816-7f2a-4996-ae4e-487fc4214add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>063d4ba2-fc0b-4d63-8af9-34126ba15761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TRS_AC_CIF</value>
      <webElementGuid>0e43a564-6342-47d5-83c0-59bd1d45ac87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_AC_CIF</value>
      <webElementGuid>be1a4dde-8f6a-446d-b3b1-1b2533f3f9ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_AC_CIF&quot;)</value>
      <webElementGuid>7e7e4b88-449b-49a2-9bcc-2f7732d6039b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_AC_CIF']</value>
      <webElementGuid>57cac96d-9a60-4d1c-9e36-c8372598d01c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_trxMgntGridTbl_Id_D001AU']/div[2]/div/table/thead/tr[2]/th[14]/div/input</value>
      <webElementGuid>ec582338-42ab-43a6-aca0-609a7bc6da91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[14]/div/input</value>
      <webElementGuid>e4c3f253-ccc8-457f-8cf2-488a061c96ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'TRS_AC_CIF' and @id = 'trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_AC_CIF']</value>
      <webElementGuid>7d9738e0-de6b-43f8-a031-7ff75bbc7177</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
