<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reference3_key_STATUS_DESC</name>
   <tag></tag>
   <elementGuidId>a14ee6db-8463-4207-9e22-b009df1efe02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='trxMgntGridTbl_Id_D001AU_gs_statusDesc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#trxMgntGridTbl_Id_D001AU_gs_statusDesc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9aaccafd-d39e-43d6-937f-48e6f83cf8c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6e555b2-841e-4db5-af39-37e3f0a3fc7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>STATUS_DESC</value>
      <webElementGuid>fa3c6688-a024-4676-b63b-8158fe1f664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trxMgntGridTbl_Id_D001AU_gs_statusDesc</value>
      <webElementGuid>317417d2-29ff-4c7c-b46e-f8c30735d9eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trxMgntGridTbl_Id_D001AU_gs_statusDesc&quot;)</value>
      <webElementGuid>156a73b5-459b-43e0-bd0f-9faa48b31901</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='trxMgntGridTbl_Id_D001AU_gs_statusDesc']</value>
      <webElementGuid>b0f411da-18d5-4484-9777-f598a6eed622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_trxMgntGridTbl_Id_D001AU']/div[2]/div/table/thead/tr[2]/th[7]/div/input</value>
      <webElementGuid>6f2df5de-eed6-4107-b765-17c81b899fb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/div/input</value>
      <webElementGuid>a316c78c-3461-4897-aacc-8cd0978fb971</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'STATUS_DESC' and @id = 'trxMgntGridTbl_Id_D001AU_gs_statusDesc']</value>
      <webElementGuid>c0ada0cc-07d7-469e-a799-120e81e116c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
