<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_reference3_key_TRS_NO</name>
   <tag></tag>
   <elementGuidId>3f9de5a6-e8b0-4cde-a516-2e6234cf569c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_NO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5242cf3e-0068-4a87-bd8c-bb9e9b0464ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40015bdd-cace-4396-9676-dc50b6025ffc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TRS_NO</value>
      <webElementGuid>afe2cb3a-7b99-454e-8b36-0c3ff18e1d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_NO</value>
      <webElementGuid>fd2a49a7-6776-4eb2-ae3a-03f3f5fd88a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_NO&quot;)</value>
      <webElementGuid>859efe49-944d-4507-88c5-94cfde54902a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_NO']</value>
      <webElementGuid>94368e7b-d75c-4bc1-8d81-6f716015bc49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_trxMgntGridTbl_Id_D001AU']/div[2]/div/table/thead/tr[2]/th[6]/div/input</value>
      <webElementGuid>883f797b-cc35-4662-87a7-bca91c3a01cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/div/input</value>
      <webElementGuid>52870366-86ee-44d3-9efb-d20c18201986</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'TRS_NO' and @id = 'trxMgntGridTbl_Id_D001AU_gs_ctstrsVO.TRS_NO']</value>
      <webElementGuid>c287e462-7f26-4439-b4cd-d24ffe360a73</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
