<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Active</name>
   <tag></tag>
   <elementGuidId>f256d4d3-f029-4662-a775-54e97b0d8a27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_trxMgntGridTbl_Id_D001AU_1_statusDesc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_trxMgntGridTbl_Id_D001AU_1_statusDesc</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0f4a2365-7b54-4e21-a099-d27ac97988e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>86f71184-b39c-4e1d-bde8-dfc44d6e7d5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>ec4a6dc1-99c1-46e4-8ffe-2bbcc7e7d070</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>d41d6fa6-48a0-4785-8b49-79b7a2778520</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>trxMgntGridTbl_Id_D001AU_statusDesc</value>
      <webElementGuid>41c2b126-367e-43d2-a24c-fb03890b2c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_trxMgntGridTbl_Id_D001AU_1_statusDesc</value>
      <webElementGuid>b6cee5fa-e5fb-4bc7-a637-2318720f494d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Active</value>
      <webElementGuid>66f02b7c-ffb9-4bbc-bc99-813d37cf8e21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_trxMgntGridTbl_Id_D001AU_1_statusDesc&quot;)</value>
      <webElementGuid>8b4c2556-9a38-4a30-8e7c-905716d7e01d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_trxMgntGridTbl_Id_D001AU_1_statusDesc']</value>
      <webElementGuid>945e35b4-aad1-4197-8f3d-201dc3d56ecf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[7]</value>
      <webElementGuid>0f3862c0-7fa6-44dd-86e1-b6d25b00b79b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='R'])[1]/following::td[3]</value>
      <webElementGuid>54d368b2-94b7-4b06-a092-0a07089eb3bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/following::td[4]</value>
      <webElementGuid>2c4bf206-6c7c-4b39-96cc-b34103735f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Deposit'])[1]/preceding::td[16]</value>
      <webElementGuid>ad9e7d79-30b2-4226-96e2-b3db7faed51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle'])[1]/preceding::td[26]</value>
      <webElementGuid>c3760cdc-edd9-437a-8c6b-492637a1c173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Active']/parent::*</value>
      <webElementGuid>af8352eb-f1e8-4e2d-91f6-2bf11a4a4025</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]</value>
      <webElementGuid>3e906294-cac7-409f-bf23-42684a48d437</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Active' and @id = 'td_trxMgntGridTbl_Id_D001AU_1_statusDesc' and (text() = 'Active' or . = 'Active')]</value>
      <webElementGuid>35d6e02f-fe0e-4b93-9897-634e04c9d4b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
