<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Log Out</name>
   <tag></tag>
   <elementGuidId>ba36a5ba-e832-45e5-979f-a3603fc7f4bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@onclick=&quot;document.getElementById('hder_logout_icon_id').click()&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>d73eb668-5616-43e9-b378-58818494593c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nowrap</name>
      <type>Main</type>
      <value>nowrap</value>
      <webElementGuid>a3f75e16-e9a1-402b-95ad-6160400a0023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('hder_logout_icon_id').click()</value>
      <webElementGuid>79062bdc-d4d2-41ed-98d7-0f17ec037920</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Log Out  </value>
      <webElementGuid>537c2522-a046-4bc6-98ae-2f5294845585</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui_bar_div&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;header-top-right&quot;]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[1]/td[8]/table[@class=&quot;whiteText&quot;]/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>82d482a6-e6d0-4c10-9f46-c0ae5909fd00</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick=&quot;document.getElementById('hder_logout_icon_id').click()&quot;]</value>
      <webElementGuid>3653edec-ced9-41ad-a18d-02b2f36481ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui_bar_div']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td[3]/table/tbody/tr/td[8]/table/tbody/tr/td[3]</value>
      <webElementGuid>66fa9e39-c4ca-403a-be64-e5d1ed3c0594</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::td[8]</value>
      <webElementGuid>cc73e0f9-b330-49ce-8096-a44d7a557e45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/following::td[16]</value>
      <webElementGuid>2411a657-2072-4573-bdfd-108450f39e74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::td[7]</value>
      <webElementGuid>2374bf5f-f604-462b-b497-2b3177ea39c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/table/tbody/tr/td[3]</value>
      <webElementGuid>2121a5bf-5f48-4242-93bc-af5542bc2b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Log Out  ' or . = ' Log Out  ')]</value>
      <webElementGuid>0167bc7a-c101-4cf6-a626-b2bd96388445</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
