<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Continue</name>
   <tag></tag>
   <elementGuidId>0b9b8319-ea86-4d44-9c7f-70c1b8b1a0e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ajaxlink</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ajaxlink']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9d0b5746-c21c-4c6e-a8d3-757a52b6bea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ajaxlink</value>
      <webElementGuid>24c116f1-de0d-4a2d-bd62-bfd171afaae5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>b17c2e50-30f2-4b33-91cd-00a4d3f104bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:submitFn()</value>
      <webElementGuid>0eb7f4b0-9ad5-4bda-aff8-b732f7f00df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only ui-state-hover ui-state-focus</value>
      <webElementGuid>22c775ff-dfac-4051-bbe5-a2d293509091</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>489887c1-f53a-49c2-97aa-a8e16e624907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue </value>
      <webElementGuid>cb99c4c5-9913-43f6-9f6a-8bc99dbda560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ajaxlink&quot;)</value>
      <webElementGuid>1a7a1b2f-61d2-4673-aaaf-c8649316eba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ajaxlink']</value>
      <webElementGuid>ce1a9abe-36f5-4985-9752-1e77ee9a649e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='compBrForm']/table/tbody/tr/td[2]/fieldset/table/tbody/tr[4]/td/a</value>
      <webElementGuid>ed60d3e0-7ba5-4cbb-a443-25696a6df173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch Code'])[1]/following::a[1]</value>
      <webElementGuid>db3fb691-acae-4066-ba1e-e9ff692a4bee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company Code'])[1]/following::a[1]</value>
      <webElementGuid>df969aa0-e095-4473-9218-c8a7806a6a2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[6]</value>
      <webElementGuid>9d27b840-ca98-414c-954b-a3b192aac1ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td/a</value>
      <webElementGuid>53ad333e-881f-46f1-b63d-c195e6a4d127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'ajaxlink' and @href = '#' and (text() = ' Continue ' or . = ' Continue ')]</value>
      <webElementGuid>c9442596-f242-42ca-afac-d3fc4fe5512f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
