<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Branch Code_branchesVO.BRANCH_CODE</name>
   <tag></tag>
   <elementGuidId>9adfa8d2-9600-428d-8050-0be8b4415d32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lookuptxt_BRANCH_CODE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookuptxt_BRANCH_CODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bcca2a52-8be9-448a-93de-5320926742b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4fd8230-0a9b-4cf6-af4a-702bb84438ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d5b5da51-fb2c-4689-a325-296e14add8a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookuptxt_BRANCH_CODE</value>
      <webElementGuid>a79b7376-7dcb-44ab-bfa2-e1cbbe978197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input liveSearchText liveSearchCompSize ui-state-focus liveSearchInputCorner</value>
      <webElementGuid>22a8808b-ef80-473a-8d1f-2ad636157979</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branchesVO.BRANCH_CODE</value>
      <webElementGuid>bd50b107-1d19-49be-89ed-0b0491b75e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>ab651b2a-2640-4807-b7f0-fea037af5aaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>90e4e38d-6b05-4967-976c-f2bfd068df0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>df191b69-029c-47f8-860c-0ac52ef30862</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>319dccbf-f13a-4ca5-addf-ae0cebd61484</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d8c34e7d-3432-4e47-9df0-e68c7e888157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>9999</value>
      <webElementGuid>c0443248-12d0-491d-9c69-fb117ab64480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>initialvalue</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f06c3f31-00b4-4d52-82e7-f8636fe5dd65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prevvalue</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>a8cac367-41b1-4ab7-a6d4-ce617c431983</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookuptxt_BRANCH_CODE&quot;)</value>
      <webElementGuid>ef1a97ec-9d51-4925-aa7b-5911ed071286</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookuptxt_BRANCH_CODE']</value>
      <webElementGuid>b6f3488a-4cc7-494e-b5bf-e0029a79a1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lookupid_BRANCH_CODE']/div/input</value>
      <webElementGuid>0e2f9614-dd90-446c-bcf9-88ca91bfefc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>bfaa37b0-ef0b-4545-babb-85c666100dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lookuptxt_BRANCH_CODE' and @name = 'branchesVO.BRANCH_CODE']</value>
      <webElementGuid>a6e91323-2e28-4cfd-8b56-f9fd127a25ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
