<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trade Date_statusDesc</name>
   <tag></tag>
   <elementGuidId>b10c4f4a-bd7f-4c12-a28d-791151b4939e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transferCashGridTbl_Id_L0VVTR_gs_statusDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transferCashGridTbl_Id_L0VVTR_gs_statusDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>56c4f99a-3895-4b9b-9c6c-a7ff8f7d1120</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4c691f80-443d-4137-b3cd-156857c7bee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statusDesc</value>
      <webElementGuid>6eb8c9d6-c667-475d-b611-f65f6aa9201b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transferCashGridTbl_Id_L0VVTR_gs_statusDesc</value>
      <webElementGuid>52a10714-140e-4db1-abb4-ab65d57519ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferCashGridTbl_Id_L0VVTR_gs_statusDesc&quot;)</value>
      <webElementGuid>2dfe987e-0661-4476-8f8f-bcb5b15c68cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transferCashGridTbl_Id_L0VVTR_gs_statusDesc']</value>
      <webElementGuid>cba796cd-50fd-44b0-8e1e-d9ad4bfd0996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_transferCashGridTbl_Id_L0VVTR']/div[2]/div/table/thead/tr[2]/th[6]/div/input</value>
      <webElementGuid>80ce884c-49a6-48c0-8318-ab3492ea6180</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/table/tbody/tr/td/div/div[3]/div[2]/div/table/thead/tr[2]/th[6]/div/input</value>
      <webElementGuid>b1607589-2508-4f69-8b67-9187c973f455</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'statusDesc' and @id = 'transferCashGridTbl_Id_L0VVTR_gs_statusDesc']</value>
      <webElementGuid>676b6cb4-c36e-4128-98e8-4a0179ff6a3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
