<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_19216</name>
   <tag></tag>
   <elementGuidId>160ad467-6923-418f-883d-fe89e81ef2bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_transferCashGridTbl_Id_L0VVTR_1_trxNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_transferCashGridTbl_Id_L0VVTR_1_trxNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>750e28dd-37c1-4f72-bac5-b45112e7422d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>2524e43c-a5e3-4c2e-ab23-78b2fdcede0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>43e62f43-bac6-450e-9d5c-f2dc54f21ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>19216</value>
      <webElementGuid>42c60af6-93c6-4c65-9c1f-280acb890992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Trx No</value>
      <webElementGuid>39055427-a1dd-4ea5-8404-a803ab95c721</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>transferCashGridTbl_Id_L0VVTR_trxNo</value>
      <webElementGuid>71f6af24-7027-4f5f-8155-d0eeb3a45de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_transferCashGridTbl_Id_L0VVTR_1_trxNo</value>
      <webElementGuid>25643c81-8925-4d31-976b-45882e6999de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>19216</value>
      <webElementGuid>6ae36a12-9fe8-499b-b4ae-61d43a589e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_transferCashGridTbl_Id_L0VVTR_1_trxNo&quot;)</value>
      <webElementGuid>c1b776e6-9aa3-490e-8882-f243d24f8e6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_transferCashGridTbl_Id_L0VVTR_1_trxNo']</value>
      <webElementGuid>3aa277b7-2a55-40b8-a2c1-ca5058368c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td)[8]</value>
      <webElementGuid>e204e83a-68ee-4f15-99b4-0a079e1ceca1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trade Date'])[2]/following::td[8]</value>
      <webElementGuid>c4a2df58-79d8-4576-9614-ad471d46b0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[2]/following::td[8]</value>
      <webElementGuid>dfd46f00-183a-4613-81c3-1be21d80f3f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[11]/preceding::td[2]</value>
      <webElementGuid>161d386b-5469-4031-b537-3ee770e4d887</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[12]/preceding::td[4]</value>
      <webElementGuid>0daab390-63de-46df-8d0a-588f23aaa02a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='19216']/parent::*</value>
      <webElementGuid>3b7a0f33-1644-4b1b-bf92-1c0fd6114da3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/table/tbody/tr/td/div/div[3]/div[3]/div/table/tbody/tr[2]/td</value>
      <webElementGuid>5c526c75-919b-431a-b631-56f4dcdcdeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '19216' and @id = 'td_transferCashGridTbl_Id_L0VVTR_1_trxNo' and (text() = '19216' or . = '19216')]</value>
      <webElementGuid>607b692e-c6db-484f-909a-ef542cbbd706</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
