<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Continue</name>
   <tag></tag>
   <elementGuidId>49748e82-37a4-494c-a12b-b08250fb7fee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='continueWelcBtn']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>9591bc38-96b6-4ad8-a150-162305a60712</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>c27ef59d-b7e5-4639-b7d4-f6a5c4f3f785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Continue </value>
      <webElementGuid>d15d4423-7558-41ee-b9f5-c46ce3ba9d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;continueWelcBtn&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>78de4f54-5342-4751-a8d8-2579e26306b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='continueWelcBtn']/span</value>
      <webElementGuid>c8022718-1525-4977-a106-c8e4568245ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Running Date 13/06/2022 Is Not Equal to System date 22/06/2022'])[1]/following::span[1]</value>
      <webElementGuid>276d5057-e5f9-4b02-b883-6e056af5b60b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Welcome'])[1]/following::span[1]</value>
      <webElementGuid>ef9ee34b-fba6-4c80-a764-b7093d28cc13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright'])[1]/preceding::span[1]</value>
      <webElementGuid>c0f380e4-c8c3-441b-a454-839561774fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continue']/parent::*</value>
      <webElementGuid>91491c18-47be-445b-972f-d43051ade57b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span</value>
      <webElementGuid>531e3c65-adb2-49d4-862d-5c02d31feaa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Continue ' or . = ' Continue ')]</value>
      <webElementGuid>0e45f27a-ffde-4bc0-aa62-e0a783f9dc61</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
