<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password_j_password_to_remove</name>
   <tag></tag>
   <elementGuidId>6ca8d362-e85a-4dc9-9663-d043e700d459</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwordInp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwordInp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>681399fc-cc64-4aa3-abb1-b9c034a16cf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ca38f409-f116-448d-bb43-6817e2ce1cc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>j_password_to_remove</value>
      <webElementGuid>d6948905-5b5d-45d4-b102-c92361ca976f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>906af397-32cd-43bc-ac98-5f15ad5a8df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwordInp</value>
      <webElementGuid>78fe1f76-2514-45e6-9430-f13d4645d2f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>texta keyboardInput</value>
      <webElementGuid>5c882784-ef94-48c1-83b3-7ea372d83dc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>if(event.keyCode==13) {login();}</value>
      <webElementGuid>b4544049-08d9-4e73-956e-56acb72cbe03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5008e1c-68ac-4f60-b7bb-be5086a2ac02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwordInp&quot;)</value>
      <webElementGuid>02c4dfab-e732-4743-9d08-a7bfb4a14ea8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwordInp']</value>
      <webElementGuid>ecbd1951-e8a8-4e71-95eb-af5fef2509f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/table/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr[2]/td[2]/table/tbody/tr[9]/td/input[3]</value>
      <webElementGuid>f6590438-36ff-400e-b948-80ebc94e4b8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input[3]</value>
      <webElementGuid>ebffbecb-d6f5-41c4-ae81-cfe155eeeb21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'j_password_to_remove' and @id = 'passwordInp']</value>
      <webElementGuid>57d22210-ae75-4e07-b249-f48399ef0a12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
