<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_</name>
   <tag></tag>
   <elementGuidId>5f3d3fc8-ab1a-458a-8b68-4549855ae9de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.jMsgbox-closeWrap</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div__popup_path_sol_confirm']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3ba45aa3-a75c-4891-aed8-5fcac0d3b45f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f5002567-0512-4997-8389-0289bdddc194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>jMsgbox-closeWrap</value>
      <webElementGuid>a48196a8-b373-4b59-a888-9b715d32b19c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>2b532487-5430-4e5a-97f6-1461691d50ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div__popup_path_sol_confirm&quot;)/div[@class=&quot;ui-widget-header ui-corner-top jMsgbox-headWrap&quot;]/div[2]/a[@class=&quot;jMsgbox-closeWrap&quot;]</value>
      <webElementGuid>cf8387d0-b2f2-4dbb-9771-cefae4c14c21</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div__popup_path_sol_confirm']/div/div[2]/a</value>
      <webElementGuid>8d9cfa6b-9d8b-4b2f-a05f-e06eb812fa11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'×')]</value>
      <webElementGuid>2ed26525-c205-4a0d-9427-dcfb9106154c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONFIRM'])[1]/following::a[1]</value>
      <webElementGuid>11d7dd70-a6cc-4447-82a7-ed3928d746b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please, select row'])[4]/following::a[1]</value>
      <webElementGuid>0cb96fea-9d85-4368-97aa-b430c542eff6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='[1908] Print Credit and Debit Advice?'])[1]/preceding::a[1]</value>
      <webElementGuid>8e1528da-5bf0-40c4-b4b4-f14184b11034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='×']/parent::*</value>
      <webElementGuid>f35b1f50-beef-49a6-92f7-45f69408f8b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[62]</value>
      <webElementGuid>57feecf4-0b38-48a1-8b14-31e3c31f4d93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/a</value>
      <webElementGuid>8e080ee7-a8e6-4aaf-a4a8-61a3b7160d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = '×' or . = '×')]</value>
      <webElementGuid>ca4fffcb-52fc-4857-9da1-ac2af2fb1239</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
