<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Apply To Reverse</name>
   <tag></tag>
   <elementGuidId>38cb8819-e199-44f4-acb8-2015f8d17c50</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L0VVTR</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='L0VVTR']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>531781c7-cdbb-4738-87f6-693d37a21741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>L0VVTR</value>
      <webElementGuid>9aa5d56b-c830-48bb-b68f-1bc979bead4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>761573d2-fa88-4ca6-83ea-51ff6cd13f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:addMenuTab('L0VVTR','Apply To Reverse','RET','L0VV' )</value>
      <webElementGuid>c8698d57-da7d-4274-935b-baa73edd0505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply To Reverse	</value>
      <webElementGuid>f41b9c04-a687-44fd-accb-204dd28ba30c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L0VVTR&quot;)</value>
      <webElementGuid>0f7b60a0-3176-4bbd-b9ed-4d388e7d082f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='L0VVTR']</value>
      <webElementGuid>485eb770-f954-44ee-baba-3fb168cb0734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_selenuimL0VVTR']/li/a</value>
      <webElementGuid>50e68a38-de0b-4244-b482-ed4f0ff63cfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reverse'])[1]/following::a[1]</value>
      <webElementGuid>5746c6d0-bbb3-4559-9674-f4921a7474dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance'])[1]/following::a[2]</value>
      <webElementGuid>23ca6e2e-25b7-4420-b27b-792026511555</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='List of Transfers From Vault to Vault'])[1]/preceding::a[1]</value>
      <webElementGuid>e7ad808a-73ff-4724-9ec0-8645ea381e0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[14]</value>
      <webElementGuid>dee38681-032e-4754-b6ad-dd7107e0cd44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/div[3]/li/a</value>
      <webElementGuid>6d6532f9-85ef-4100-8fdf-5c4be58217dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'L0VVTR' and @href = '#' and (text() = 'Apply To Reverse	' or . = 'Apply To Reverse	')]</value>
      <webElementGuid>65068b09-5d82-406b-b94c-3c47c1c0cd72</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
