<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Record Saved Successfully__popup_path_sol_ok</name>
   <tag></tag>
   <elementGuidId>9b381707-9c0d-4158-977a-0140feeb7da1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_popup_path_sol_ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_popup_path_sol_ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>860035a7-18cc-4e98-8d2c-acb99ce5562e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3b418156-514a-4de7-a66b-8d89b36c4783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_popup_path_sol_ok</value>
      <webElementGuid>53da0462-da77-433f-9c97-278972400e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text fg-button ui-button ui-corner-all ui-widget ui-state-default ui-button-text-only</value>
      <webElementGuid>4cec4724-c3a0-49d2-9aed-2e29c4f03ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>2fa5a135-8396-4aab-b725-f53097de31ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_popup_path_sol_ok&quot;)</value>
      <webElementGuid>e70ac1bb-7bfa-4089-bebd-56235686a41c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_popup_path_sol_ok']</value>
      <webElementGuid>ba71d02a-d107-4d9b-909a-b32b5333f910</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div__popup_path_sol_ok']/center/input</value>
      <webElementGuid>a5f35bcb-383f-410c-9009-e35309845739</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/input</value>
      <webElementGuid>7f24c09b-d67c-4765-9a3b-b6d3c4abf0f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_popup_path_sol_ok']</value>
      <webElementGuid>62d637f6-3caa-47b6-a952-d2611255e443</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
