<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BRIEF_DESC_ENG</name>
   <tag></tag>
   <elementGuidId>0cb394f1-8a42-4142-a78d-b0d02402b700</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridtab_currencyCode_A002MT_gs_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_glType_A002MT_gs_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fb87b362-6757-4b62-a5a8-06fea6dcf9e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>74189e8a-df58-4ebf-b06c-cd1b6e5b5877</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRIEF_DESC_ENG</value>
      <webElementGuid>3622f5d1-9ee0-49ef-be1e-8dc4577da928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_currencyCode_A002MT_gs_BRIEF_DESC_ENG</value>
      <webElementGuid>b75c29dd-02ee-499a-bcba-0e4c623290e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_currencyCode_A002MT_gs_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>73b46e36-e2b0-449d-bc5f-7a2c602f0037</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_currencyCode_A002MT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>59a3047f-66d8-48ed-bcb0-a8fe16867704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_currencyCode_A002MT']/div[2]/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>c98d1eb0-0029-4699-9309-2cd62bf4ffab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[18]/div/div[3]/div[2]/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>bb531cda-a848-41f8-bc35-e3563593fdfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRIEF_DESC_ENG' and @id = 'gridtab_currencyCode_A002MT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>8fdaac93-f702-4b0f-a51c-5d6a7c845e84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
