<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_CIF_NO</name>
   <tag></tag>
   <elementGuidId>13f66d38-d470-40f9-a66c-d0c37524a114</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridtab_cifNo_A002MT_gs_CIF_NO</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_cifNo_A002MT_gs_CIF_NO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fab5e561-1336-4ea1-b77c-91e96d8c345d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54c1a856-4926-4165-a34d-c6829c7bf1a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CIF_NO</value>
      <webElementGuid>dc9b339c-fd55-4f3c-968a-8150066c356e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_cifNo_A002MT_gs_CIF_NO</value>
      <webElementGuid>d02105ed-f59a-48b1-901b-dfad64821c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_cifNo_A002MT_gs_CIF_NO&quot;)</value>
      <webElementGuid>9eb21f2e-7be5-44cb-a823-0301c33d468e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_cifNo_A002MT_gs_CIF_NO']</value>
      <webElementGuid>1d58cb53-4ae0-4c2d-a77a-9b35e4d89cde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_cifNo_A002MT']/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>36dbe71b-5ee5-4777-905c-33d6db7e9110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[3]/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>da7e67cd-736a-48b0-8843-8e3732f83dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'CIF_NO' and @id = 'gridtab_cifNo_A002MT_gs_CIF_NO']</value>
      <webElementGuid>ec44f03e-6080-4aa3-b956-6c7a590faf3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
