<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BRIEF_DESC_ENG_1</name>
   <tag></tag>
   <elementGuidId>76fdb7ea-2eca-42f7-88bc-28e15303340c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridtab_glType_A002MT_gs_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ea45376-f2df-4f82-82f4-bc241ec8337d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>57239dd1-bed3-4226-8922-07c3eb233bdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRIEF_DESC_ENG</value>
      <webElementGuid>a6968aa4-a6a0-4755-b009-c475ae84c468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_glType_A002MT_gs_BRIEF_DESC_ENG</value>
      <webElementGuid>8fb15abf-f38e-48b1-a2e1-5cbe0cffacd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_glType_A002MT_gs_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>65be84a6-6e9d-4f97-a9c7-0334b8f024a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_glType_A002MT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>581790ba-eba3-4d4b-aa22-9669a5f6a57f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_glType_A002MT']/div[2]/div/table/thead/tr[2]/th[4]/div/input</value>
      <webElementGuid>e926c894-e72a-4100-9f57-8fadd7628761</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[3]/div[2]/div/table/thead/tr[2]/th[4]/div/input</value>
      <webElementGuid>1e0a1789-6346-4bfb-a0e7-9a7af3896c65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRIEF_DESC_ENG' and @id = 'gridtab_glType_A002MT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>8a8fb464-0c43-480c-9494-497e5cbeb5dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
