<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Save</name>
   <tag></tag>
   <elementGuidId>b7a5d1c8-a48a-4ba5-9e80-62cc717fc939</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generalAccountForm_A002MT_Save_key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='generalAccountForm_A002MT_Save_key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>2c6205c5-e45d-4c80-a68f-395eca22132c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generalAccountForm_A002MT_Save_key</value>
      <webElementGuid>b3a51d2b-58fd-4de0-9341-bb4339342932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>generalAccountSave_A002MT</value>
      <webElementGuid>0d6572c0-190e-4a09-80c5-6171f44ab416</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>Save_key</value>
      <webElementGuid>1a68b293-d6d9-437d-83cb-04e1e13124b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>ff10a2e4-c47d-4541-8951-5dbce6954363</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save </value>
      <webElementGuid>797d8f5d-8b10-442e-801f-5f24b56e48c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generalAccountForm_A002MT_Save_key&quot;)</value>
      <webElementGuid>e2e49755-3d05-42cb-b645-32ae9b04c97b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='generalAccountForm_A002MT_Save_key']</value>
      <webElementGuid>36abed4c-5c63-481f-ad38-5766d7fb194c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='generalAccountSave_A002MT']/span[2]/label</value>
      <webElementGuid>54424c00-cfa6-4d98-aa80-abfeb863eb96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges Waiver'])[1]/following::label[1]</value>
      <webElementGuid>9113e814-7bca-4569-93f9-e035c08133a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KYC Details'])[1]/following::label[2]</value>
      <webElementGuid>6f6e32f2-6274-4f4b-8bb4-15e28d7c1b8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright'])[1]/preceding::label[1]</value>
      <webElementGuid>e3ebe289-de50-47c4-a1a2-003804272efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>80ecb751-9097-4a29-9f82-7e7740afc1fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button/span[2]/label</value>
      <webElementGuid>ee1307c9-3e4b-4df5-8f59-8ba3da70ce54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'generalAccountForm_A002MT_Save_key' and (text() = 'Save ' or . = 'Save ')]</value>
      <webElementGuid>a666690c-cf3d-48da-90b4-427d74a04878</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
