<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dismiss</name>
   <tag></tag>
   <elementGuidId>b46dbff9-3892-48af-93eb-d79017a845f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dismissbut_A002MT > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dismissbut_A002MT']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d5adfd55-72eb-41f0-bc8f-b8e6ba61dcb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>32237a7d-d78f-4f8b-bec2-41c409d10293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dismiss </value>
      <webElementGuid>2a087b47-b093-4156-9c1c-098a27a334ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dismissbut_A002MT&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>461a31b5-a8ce-4e19-a80f-86615f26b8d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dismissbut_A002MT']/span</value>
      <webElementGuid>99d2e5e5-1f27-4371-a8e0-b3d2ad012a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/following::span[1]</value>
      <webElementGuid>e53b0bf3-4cf1-4c8e-b892-919c7c5b982d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records to view'])[2]/following::span[2]</value>
      <webElementGuid>9e90c02a-2b3b-45cb-9436-acd476895f0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning'])[5]/preceding::span[1]</value>
      <webElementGuid>b5e3ec0a-b9cd-4668-8dd2-98df99903ec8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please, select row'])[5]/preceding::span[3]</value>
      <webElementGuid>31315fba-6271-4f34-92c0-eec6bc70068a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dismiss']/parent::*</value>
      <webElementGuid>fdb6cf02-8dff-4a9f-a35a-4654650a9751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a[2]/span</value>
      <webElementGuid>859f39c9-76b4-45db-96ec-a532f39d8570</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Dismiss ' or . = ' Dismiss ')]</value>
      <webElementGuid>16187965-1d00-4a57-a42c-34615fe3d7eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
