<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_26</name>
   <tag></tag>
   <elementGuidId>1251ca56-52f4-4ec5-ab84-e28bac7a6968</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_currencyCode_A002MT_1_ADDITIONAL_REFERENCE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_currencyCode_A002MT_1_ADDITIONAL_REFERENCE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>e858ad89-bedb-4120-9530-e58fed728445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>02eeab59-3063-496f-9a94-633aafb36c15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>83e72ce2-6e14-4b6d-a8ae-b3942be33cf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Additional Ref</value>
      <webElementGuid>27e0d2fa-2026-4081-aa11-10e5567f1c40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_currencyCode_A002MT_ADDITIONAL_REFERENCE</value>
      <webElementGuid>c08293d7-af3a-4d07-8b78-1b8d7d7cd776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_currencyCode_A002MT_1_ADDITIONAL_REFERENCE</value>
      <webElementGuid>79604c47-af15-48fb-b4dc-dc707158209a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>26</value>
      <webElementGuid>aa8491dc-bd9a-4b17-9282-89af33475874</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_currencyCode_A002MT_1_ADDITIONAL_REFERENCE&quot;)</value>
      <webElementGuid>d3e152c3-f04b-49cf-ac53-b0212fb81828</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_currencyCode_A002MT_1_ADDITIONAL_REFERENCE']</value>
      <webElementGuid>9975d529-e547-4fef-90a6-b1d75316248d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[2]</value>
      <webElementGuid>7ab9b63d-05c8-4112-bbe4-34aa1acea95c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف الكامل'])[1]/following::td[8]</value>
      <webElementGuid>8009544e-0e17-4ac6-822a-ef3dd24d6aec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف المختصر'])[1]/following::td[8]</value>
      <webElementGuid>64790d67-9f45-4bf4-a70c-5982758a54a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OMR'])[1]/preceding::td[1]</value>
      <webElementGuid>ed8fc4ec-18c6-4875-90aa-77c916c81536</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Omani Rial'])[1]/preceding::td[2]</value>
      <webElementGuid>d00833dd-4411-477a-a07f-10e8a06d1eb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>e98aa386-7c03-452a-b9d5-fb084ea207a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '26' and @id = 'td_gridtab_currencyCode_A002MT_1_ADDITIONAL_REFERENCE' and (text() = '26' or . = '26')]</value>
      <webElementGuid>58c62051-0fbc-49d4-8ade-ce18c239c7c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
