<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Savings Account</name>
   <tag></tag>
   <elementGuidId>f630bfdb-d73a-4103-a02e-a7d1724ae231</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_glType_A002MT_1_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_glType_A002MT_1_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2d339600-594e-4a6a-a76e-76e02817f52e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>7a46c6c5-600b-490c-a7a5-2ea9b47ee3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Savings Account</value>
      <webElementGuid>f3c1ec6b-0ff0-4113-ba44-5233bed28393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>c6b7e562-0563-42cf-a529-28dbdaee65c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_glType_A002MT_BRIEF_DESC_ENG</value>
      <webElementGuid>a08de293-14d8-4b94-aff7-451435737a2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_glType_A002MT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>f2e8ca62-f55d-4b37-abc6-9b5a911f7421</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Savings Account</value>
      <webElementGuid>7d511712-975d-4176-935d-bec2489df7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_glType_A002MT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>21133829-2fe3-4db9-b6d5-aa612e41d6dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_glType_A002MT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>57537554-441b-45bf-8e2c-a132ce845a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[4])[2]</value>
      <webElementGuid>d571d6be-0afb-407f-a19c-dd778b99ab8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف المختصر'])[2]/following::td[12]</value>
      <webElementGuid>e54f6a42-cbf6-445a-ac3e-46a731d88c09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A/C Sign'])[1]/following::td[12]</value>
      <webElementGuid>8e799599-3776-4145-9854-f0872e54078f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B'])[1]/preceding::td[1]</value>
      <webElementGuid>2e9d32dc-b0ac-43a5-b18a-3364e5b5c387</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='C'])[1]/preceding::td[3]</value>
      <webElementGuid>ba0fe52e-fe2d-4443-89b2-0f6593f94807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Savings Account']/parent::*</value>
      <webElementGuid>76ec5935-2f51-426f-b68d-ca6adfcd8718</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[4]</value>
      <webElementGuid>d40bbb7a-533c-4934-822d-9876324642d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Savings Account' and @id = 'td_gridtab_glType_A002MT_1_BRIEF_DESC_ENG' and (text() = 'Savings Account' or . = 'Savings Account')]</value>
      <webElementGuid>81f9596c-9ad1-4054-b9cf-70bf71d4a60e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
