<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description_accountsManagementCO.a_ca0ebb</name>
   <tag></tag>
   <elementGuidId>fe585bcd-3d8e-43ad-b22f-5cab04b4d527</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#description_A002MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='description_A002MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>d89d79c8-55c4-442e-a1f7-92479c8e60bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>accountsManagementCO.amfVO.DESCRIPTION</value>
      <webElementGuid>70ea6a26-a240-4b4c-a547-857a11e092bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>b162954c-34a1-469d-8b5c-fc6206082a93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>6a900791-de4c-43ed-9f30-e4100ac8ebbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>description_A002MT</value>
      <webElementGuid>1060ed35-57ee-46e7-ad30-97ce13b14d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>81867aee-243d-44d4-aa3a-03723af761c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateDescription();</value>
      <webElementGuid>31637fbb-00cf-4352-a743-4e21228f6d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;description_A002MT&quot;)</value>
      <webElementGuid>a479f1ca-127c-403f-ae6a-36a5363b64a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='description_A002MT']</value>
      <webElementGuid>8421e129-bd70-4566-9aa1-a47f99d05a04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accountsMailingDetailsTab_A002MT']/div/div[2]/table/tbody/tr[3]/td[5]/textarea</value>
      <webElementGuid>c9ebb13c-8bb0-43cc-80d2-5c07a4589474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[5]/textarea</value>
      <webElementGuid>977359fb-f01c-4e25-87fa-4b48ae72aa3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'accountsManagementCO.amfVO.DESCRIPTION' and @id = 'description_A002MT']</value>
      <webElementGuid>d81f19de-7d60-4221-8542-e2d2daa0c12e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
