<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Brief Description_BRANCH_CODE</name>
   <tag></tag>
   <elementGuidId>5e2098b8-27f1-43ce-8c40-e4598389c775</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_BRANCH_CODE_gs_BRANCH_CODE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gridtab_BRANCH_CODE_gs_BRANCH_CODE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f0f96b8b-dcaa-410f-9839-1feadfc47b1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5f3eec80-58ba-4aa0-9dec-ecd38f8aea04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRANCH_CODE</value>
      <webElementGuid>50513100-a290-4bde-873d-45f9f9fc91b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_BRANCH_CODE_gs_BRANCH_CODE</value>
      <webElementGuid>cbdb1826-a204-437d-ac5d-36b9880d5247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_BRANCH_CODE_gs_BRANCH_CODE&quot;)</value>
      <webElementGuid>d64ed84c-df92-4245-bc53-8aa8e2c5eb85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_BRANCH_CODE_gs_BRANCH_CODE']</value>
      <webElementGuid>875a1b9e-17b3-45f7-bec7-ac000f157c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_BRANCH_CODE']/div[2]/div/table/thead/tr[2]/th/div/input</value>
      <webElementGuid>7890f068-7bd0-4968-afaa-ef41cb1fa70b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div/input</value>
      <webElementGuid>01c0b045-709f-41b6-bb54-54fc4413bbbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRANCH_CODE' and @id = 'gridtab_BRANCH_CODE_gs_BRANCH_CODE']</value>
      <webElementGuid>ebf5a23b-88fd-4086-ad31-7327a1a7179b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
