<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Branch Code_branchesVO.BRANCH_CODE</name>
   <tag></tag>
   <elementGuidId>94175f8a-13ac-41a2-81e3-01669bf4a356</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookuptxt_BRANCH_CODE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lookuptxt_BRANCH_CODE</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23078a11-e70b-4a0a-ba5a-6c60ec61d418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>26daa302-d013-476e-b084-fce6c324f0fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2ae82a0e-4f1a-4f33-8f83-fdbc6e362d0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookuptxt_BRANCH_CODE</value>
      <webElementGuid>902268ac-9eea-401c-ab23-637659bbe366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input liveSearchText liveSearchCompSize ui-state-focus liveSearchInputCorner</value>
      <webElementGuid>e55350d1-06ed-44f3-a4d9-d067845c43ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>branchesVO.BRANCH_CODE</value>
      <webElementGuid>9106ade2-e6d5-4d34-a875-f14ba5b99c29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9de9bee9-a794-4281-8863-20bd8cb34310</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>3c73fda1-925a-4a0d-b6ab-2698a37c8efe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>ab9b8718-80ac-4596-9111-11d312d08a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6af7be4e-01c9-45e1-bdb9-f6312c4d499f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>9231bd83-053d-4d38-904d-c3a3cca7917a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>9999</value>
      <webElementGuid>b149f574-2885-4407-b51d-f2f5329d9976</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>initialvalue</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>20c6628a-d986-4f54-a843-33d3f63c6c19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prevvalue</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>702f47f9-1ba8-43ad-a3da-a2f36bcc5c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookuptxt_BRANCH_CODE&quot;)</value>
      <webElementGuid>1bd4faf5-5484-4c80-8644-ab31e5e0b855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookuptxt_BRANCH_CODE']</value>
      <webElementGuid>56b0d764-b273-4571-aa30-3f8f89fac0bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lookupid_BRANCH_CODE']/div/input</value>
      <webElementGuid>2e8aae8a-1eaa-4929-97ae-d5d50de08db6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>3cb2e863-70c0-4d19-a7da-0c09ddb6b425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lookuptxt_BRANCH_CODE' and @name = 'branchesVO.BRANCH_CODE']</value>
      <webElementGuid>42881869-63a6-494e-960a-bfb120ecb5ff</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
