<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Branch Code_ui-icon ui-icon-search liv_80748e</name>
   <tag></tag>
   <elementGuidId>6579c4b2-73a1-416a-b44a-6d6b5d4df774</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanLookup_BRANCH_CODE']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spanLookup_BRANCH_CODE > span.ui-icon.ui-icon-search.live-search-ui</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>89fb0d86-36e9-41d0-a23c-6cc751298355</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-search live-search-ui</value>
      <webElementGuid>e23402f3-608f-405f-b905-8b5584639620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanLookup_BRANCH_CODE&quot;)/span[@class=&quot;ui-icon ui-icon-search live-search-ui&quot;]</value>
      <webElementGuid>bcac8989-0f46-4377-b982-358d0eaf55bc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='spanLookup_BRANCH_CODE']/span</value>
      <webElementGuid>3762cd26-a582-404d-ab20-a187cd1ab0e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[3]/div/table/tbody/tr/td/div/span/span</value>
      <webElementGuid>6d2f30af-5aff-468c-8d7f-72801d343b78</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
