<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Reverse</name>
   <tag></tag>
   <elementGuidId>72960044-441b-46ee-8781-b3acf9db6a1f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#L0VVRV</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='L0VVRV']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>973b4995-3314-402f-872b-100f801da32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>L0VVRV</value>
      <webElementGuid>f2315594-bb9e-4edd-99fc-e325f24c6c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>f33124cb-2866-44bf-9215-fddd7f67f161</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:addMenuTab('L0VVRV','Reverse','RET','L0VV' )</value>
      <webElementGuid>ae20b57d-048a-45c2-b245-63c77ab46fbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Reverse	</value>
      <webElementGuid>5be59438-7a9e-4eb8-a06a-8c8af482613b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;L0VVRV&quot;)</value>
      <webElementGuid>4b58d9e9-291c-49bd-a03f-f15d68ac71a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='L0VVRV']</value>
      <webElementGuid>b28f2475-a38e-4173-9f00-b24b70d84bc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_selenuimL0VVRV']/li/a</value>
      <webElementGuid>c395a12b-7fdd-4ee7-a60f-577327facdb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance'])[1]/following::a[1]</value>
      <webElementGuid>877c3475-98c6-4e5e-97f2-6eb3a7887cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Transfer Cash From Vault to Vault'])[1]/following::a[2]</value>
      <webElementGuid>567c2e2a-fa86-419e-8aa6-62030bf1b92f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply To Reverse'])[1]/preceding::a[1]</value>
      <webElementGuid>10c8a8bb-e0fc-4fed-8975-c62cf61bb008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>4e3df473-906a-432b-95a7-9eac3a7f91a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/ul/div[2]/li/a</value>
      <webElementGuid>b11b304a-5029-4c6a-b0d8-c85f10f8344d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'L0VVRV' and @href = '#' and (text() = 'Reverse	' or . = 'Reverse	')]</value>
      <webElementGuid>bda61f16-de71-4351-92e9-be2578f48eb7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
