<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Authorize</name>
   <tag></tag>
   <elementGuidId>a2bc0847-123b-416e-9872-64e5a14f7d3a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='A002AU']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>39f26b66-92ef-4827-a598-35f88a9b8554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorize</value>
      <webElementGuid>3e2c636b-8e46-49fc-9df0-03a45072def9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;A002AU&quot;)/span[2]</value>
      <webElementGuid>5457e3b9-c110-4c3c-aba0-6175a7444cd1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='A002AU']/span[2]</value>
      <webElementGuid>8114ebed-6812-49ca-9c4f-6004dc1c270c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Opening'])[1]/following::span[4]</value>
      <webElementGuid>411b1231-c7fd-4351-9a8e-8fb177b8dd2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='General Accounts'])[1]/following::span[8]</value>
      <webElementGuid>abf6ffa9-8b14-4266-9ea3-9440e654ff9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorize Close'])[1]/preceding::span[4]</value>
      <webElementGuid>157636c5-15b7-491a-9983-30ac0b5c87bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Authorize Close With Transfer'])[1]/preceding::span[8]</value>
      <webElementGuid>68c983c2-152a-4ac7-ac58-78eb5ac55e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Authorize']/parent::*</value>
      <webElementGuid>8bcc42d8-ceab-47c3-a678-1ddd36b2dfa9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/li/a/span[2]</value>
      <webElementGuid>4287ba70-50b9-4e96-96f5-c91ee7ac4e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Authorize' or . = 'Authorize')]</value>
      <webElementGuid>1050d5ef-2ae8-4893-9e86-1b73a4128c14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
