<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Denomination</name>
   <tag></tag>
   <elementGuidId>f11f4cbe-79b9-417f-9955-eea9b9b85ec8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_transferCashSubCashGridTbl_Id_L0VVMT_1_transferCashCyDenom > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick='transferCash_openCyDenomDialog(new_1655880641080);']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fcc18ad5-1e4d-4227-aea1-4346c3eea8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>bbc5053d-be7c-4202-aed7-181de98a2365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>transferCash_openCyDenomDialog(new_1655880641080);</value>
      <webElementGuid>e81721eb-5d71-492c-ad92-1c9d5606513f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Denomination</value>
      <webElementGuid>01cc0af4-5d59-41a4-98dc-d681fffce9bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_transferCashSubCashGridTbl_Id_L0VVMT_1_transferCashCyDenom&quot;)/a[1]</value>
      <webElementGuid>bb70eff1-5e00-4629-b3aa-ffd9527722f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick='transferCash_openCyDenomDialog(new_1655880641080);']</value>
      <webElementGuid>31a14c63-0e44-4737-b6bd-42aa140552c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='td_transferCashSubCashGridTbl_Id_L0VVMT_1_transferCashCyDenom']/a</value>
      <webElementGuid>19c2c9bc-de24-4d4b-8a68-23f579c4964d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Denomination')])[2]</value>
      <webElementGuid>760a8a4c-0499-4d69-af6a-bcbc95e78a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OMR'])[1]/following::a[1]</value>
      <webElementGuid>8f4b09f4-4d73-4e65-bc3e-dadd7de3d187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decimal Points'])[1]/following::a[1]</value>
      <webElementGuid>46c65577-a102-467d-b328-0e9c783f9fde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::a[1]</value>
      <webElementGuid>bed7d149-eb49-414c-8428-b32005738d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::a[1]</value>
      <webElementGuid>619e3aba-20fb-4ffb-af3d-00eec2ae3fe9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Denomination']/parent::*</value>
      <webElementGuid>4e6d0ae3-9e41-445b-a49a-94ee91c05b71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[24]</value>
      <webElementGuid>1ebd0637-d7f0-4d5a-ad58-e613f1a99edb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/a</value>
      <webElementGuid>df609e58-716f-4905-ab0f-57fcc89b6475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Denomination' or . = 'Denomination')]</value>
      <webElementGuid>b6e80f1c-ca74-47a1-9d24-2b6263ec5d5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
