<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Available Bills_1_ctstellerCashBalanc_902eb5</name>
   <tag></tag>
   <elementGuidId>08be5446-fad8-4028-914c-5773ee321d01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cf173c0b-6dd9-4487-b745-f3953d34d534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c7dd0066-c1fa-475a-b044-47d941d1adf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colmodel</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>85bbc354-c5ca-43e3-b526-2652319173f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>c0928564-07ee-4d09-968f-2458ba15933b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT</value>
      <webElementGuid>54e14b18-f4b4-47e2-9664-cc6ab7dd536d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gridid</name>
      <type>Main</type>
      <value>trsfrCashcyDenomGridTbl_Id_L0VVMT</value>
      <webElementGuid>903dc795-f6b4-4306-a808-ed320f580d91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>c7b8a300-e4ce-4d9e-96d9-695813ca9498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>editable</value>
      <webElementGuid>a440476d-80c0-4893-b2f4-786af14602a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cyDenomCommonCO.trsCurrencyDetCO.ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS:ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS,cyDenomCommonCO.trsCurrencyDetCO.comp_amt:comp_amt</value>
      <webElementGuid>c8c1046b-5df0-47ea-8efe-add1515a24a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/transfercash/transferCashCyDenomAction_dependencyByCountedNbBills?iv_crud=&amp;amp;_pageRef=L0VVMT</value>
      <webElementGuid>cfdd8b54-32b8-4d18-9f30-ee5969147aed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>params</name>
      <type>Main</type>
      <value>cyDenomCommonCO.trsCurrencyDetCO.ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS:ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS,cyDenomCommonCO.trsCurrencyDetCO.avail_bills:avail_bills,cyDenomCommonCO.trsCurrencyDetCO.ctstellerCashBalanceCyNomVO.VALUE:ctstellerCashBalanceCyNomVO.VALUE,cyDenomCommonCO.trsfrType:cyDenomTrsfrType_L0VVMT</value>
      <webElementGuid>5925a997-f4e6-4f31-98fa-9e466e19f694</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>recalculateTotalAmount()</value>
      <webElementGuid>c247a8ea-8021-4a2c-9ecf-ce28a97aefdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT&quot;)</value>
      <webElementGuid>23f8b3ee-ec63-4fbe-b648-bec624364e89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT']</value>
      <webElementGuid>3eaaa74e-f00d-464c-8127-9b90f83ae2b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//td[@id='td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS']/div/input</value>
      <webElementGuid>999aa217-a0e8-4944-8515-095b174df237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/div/input</value>
      <webElementGuid>2c2822fd-6979-4fa9-9610-06b3bdd4c026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = '1_ctstellerCashBalanceCyNomVO.COUNTED_NUMBER_OF_BILLS_trsfrCashcyDenomGridTbl_Id_L0VVMT']</value>
      <webElementGuid>171a4037-17f6-4ee5-b891-1cc24b0d44c1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
