<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Unit_BRIEF_DESC_ENG</name>
   <tag></tag>
   <elementGuidId>e80a7634-2dc8-473a-bf57-b24944552691</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridtab_new_1655880641080_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//input[@name='BRIEF_DESC_ENG'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e188cd83-6af4-4d8d-9cf8-7fe0f9ad7f24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>db93c094-f627-4846-951b-cbac0f2eef93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRIEF_DESC_ENG</value>
      <webElementGuid>21d5cd54-16e2-400f-b1ba-486718169e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_new_1655880641080_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG</value>
      <webElementGuid>b7e3a63e-85c0-4d0f-9ed6-a2d39cc0cb23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_new_1655880641080_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>db145048-1dac-4d06-a2ae-75771e7fdb67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_new_1655880641080_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>437605d8-5b1d-4580-bdfd-ac48ff69ebdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_new_1655880641080_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT']/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>e6ea6f98-e7ff-4593-bdcf-d1cc298f7dee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div[3]/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>d8091687-8002-4e67-b68a-75d2adcf6b40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRIEF_DESC_ENG' and @id = 'gridtab_new_1655880641080_ctstellerCashBalanceDetVO_CURRENCY_CODE_transferCashSubCashGridTbl_Id_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>387d99b1-b654-4b3f-ba23-c6ef996eaf40</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
