<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Decimal Points_lookupTxt_ctstellerCas_ca335e</name>
   <tag></tag>
   <elementGuidId>2cd1ef88-9b9d-4b86-b880-b567d0b75af7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new_1655880641080_ctstellerCashBalanceDetVO.CURRENCY_CODE_lookuptxt_transferCashSubCashGridTbl_Id_L0VVMT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9ffad382-c62f-4b6d-b394-d7b915693b1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>livesearch</value>
      <webElementGuid>381e0e82-445d-4e22-8428-3d1c6f01575f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>791005a7-797f-4154-bbf4-4d4fc2b785c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new_1655880641080_ctstellerCashBalanceDetVO.CURRENCY_CODE_lookuptxt_transferCashSubCashGridTbl_Id_L0VVMT</value>
      <webElementGuid>e343ee6d-c1b5-4ea7-9e69-57cb96795c79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>liveSearchText liveSearchCompSize ui-widget-content liveSearchInputCorner</value>
      <webElementGuid>cc407602-f6ed-4222-8247-5d63104c72fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>lookupTxt_ctstellerCashBalanceDetVO.CURRENCY_CODE</value>
      <webElementGuid>2f2807e8-066d-4ce0-8eab-d6af0ab9f7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colmodel</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>ebb8afcf-1647-4020-9d6e-d757998e94dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>32819252-ee5a-44f2-b374-1b53d25ee7c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>gridid</name>
      <type>Main</type>
      <value>transferCashSubCashGridTbl_Id_L0VVMT</value>
      <webElementGuid>49b88287-63d0-4d9e-a28a-f0fabf6dcb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new_1655880641080_ctstellerCashBalanceDetVO.CURRENCY_CODE_lookuptxt_transferCashSubCashGridTbl_Id_L0VVMT&quot;)</value>
      <webElementGuid>52b62d84-42cc-4260-8ab2-df608734dfdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new_1655880641080_ctstellerCashBalanceDetVO.CURRENCY_CODE_lookuptxt_transferCashSubCashGridTbl_Id_L0VVMT']</value>
      <webElementGuid>de5dfe33-8119-4841-a3fe-836677fdb758</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div_new_1655880641080_ctstellerCashBalanceDetVO.CURRENCY_CODE']/input</value>
      <webElementGuid>01941a2a-d801-465d-820c-9a8f772a52e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/table/tbody/tr/td/div/input</value>
      <webElementGuid>47c4fb03-0292-4d19-b46c-9dd78d0e1106</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'new_1655880641080_ctstellerCashBalanceDetVO.CURRENCY_CODE_lookuptxt_transferCashSubCashGridTbl_Id_L0VVMT' and @name = 'lookupTxt_ctstellerCashBalanceDetVO.CURRENCY_CODE']</value>
      <webElementGuid>16ba5988-2932-4679-a7e4-56b30d5c0851</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
