<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Remark_BRIEF_DESC_ENG</name>
   <tag></tag>
   <elementGuidId>64349554-fc1e-4245-b339-ed4e12d00569</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridtab_vaultBranchLookup_L0VVMT_gs_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_vaultBranchLookup_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>854a6968-ae4d-4f54-9603-2050b5063398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d28b63c9-a081-4a60-af8e-0ca5fe6cb793</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRIEF_DESC_ENG</value>
      <webElementGuid>a5763cbc-9f73-4e95-bfa0-48c6422e3498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_vaultBranchLookup_L0VVMT_gs_BRIEF_DESC_ENG</value>
      <webElementGuid>0115c9f4-5b59-404f-b660-f66925e7a345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_vaultBranchLookup_L0VVMT_gs_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>8da228c0-34fa-4a2f-b8cb-4ddf81a7dd15</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_vaultBranchLookup_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>b7c16e99-a113-4017-ac9d-5999d00d70d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_vaultBranchLookup_L0VVMT']/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>e453586a-2bac-49c2-97f7-2a6f258c0f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[3]/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>fd68ad2d-0fc0-4320-9a06-ee7f0b955a1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRIEF_DESC_ENG' and @id = 'gridtab_vaultBranchLookup_L0VVMT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>1118e86a-9e57-416a-a942-d8174c025d08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
