<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_To Branch Code_ui-icon ui-icon-search _94c493</name>
   <tag></tag>
   <elementGuidId>6f187a90-f198-489f-9086-8a2e99b5553f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#spanLookup_vaultBranchLookup_L0VVMT > span.ui-icon.ui-icon-search.live-search-ui</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanLookup_vaultBranchLookup_L0VVMT']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>32b707d0-3cf2-4a7b-82be-d78e2a8e4681</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-search live-search-ui</value>
      <webElementGuid>5e2b7961-6f8a-406b-8217-f8ee63811b53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanLookup_vaultBranchLookup_L0VVMT&quot;)/span[@class=&quot;ui-icon ui-icon-search live-search-ui&quot;]</value>
      <webElementGuid>5e557158-da97-4626-844c-3052a3fb88ba</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='spanLookup_vaultBranchLookup_L0VVMT']/span</value>
      <webElementGuid>f89ac872-1726-4cf5-a693-e47109f10a87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[5]/td[2]/table/tbody/tr/td/div/table/tbody/tr/td/div/span/span</value>
      <webElementGuid>0c9ec697-c126-4eb1-bc35-ec66a6d1ec14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
