<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_</name>
   <tag></tag>
   <elementGuidId>1ca8ac89-d77f-4241-b82b-3b41a33dbcb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_tellerLookup_L0VVMT_2_USER_ID</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_tellerLookup_L0VVMT_2_USER_ID']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>3620fabd-94a0-4d88-bc55-b2cfaf18127b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>2f045cfd-5cac-4b32-9f67-a133ca2604dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>User Id</value>
      <webElementGuid>b635020a-5b2b-4f87-b247-975743932132</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_tellerLookup_L0VVMT_USER_ID</value>
      <webElementGuid>3c56acc9-0967-4b69-ae89-e9bb5877f4fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_tellerLookup_L0VVMT_2_USER_ID</value>
      <webElementGuid>a9146676-88b4-49eb-8915-79f9d1f2a43e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>7f65a877-0ab0-40af-88dd-d1f731e5869a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_tellerLookup_L0VVMT_2_USER_ID&quot;)</value>
      <webElementGuid>dabb017f-1a33-4d65-bac0-20344cecc2d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_tellerLookup_L0VVMT_2_USER_ID']</value>
      <webElementGuid>bf9594d4-3923-4b15-82d3-e4212d006385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='2']/td[2])[2]</value>
      <webElementGuid>0cb86902-8fcb-41c8-86ed-b1f7661130ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[12]/following::td[2]</value>
      <webElementGuid>c0661a9d-8add-4f05-bee7-62ab91c29b8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[11]/following::td[3]</value>
      <webElementGuid>b4872998-4845-4923-bcac-c07065d21afb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[13]/preceding::td[6]</value>
      <webElementGuid>b1b599eb-93c1-4226-9045-618e5810854d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[14]/preceding::td[7]</value>
      <webElementGuid>35f686c0-4fb5-484e-a521-ac351f436f7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div[3]/div[3]/div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>fcba3295-a132-478d-af39-5b4729df3ab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'td_gridtab_tellerLookup_L0VVMT_2_USER_ID' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>2aaa7d27-c526-495f-a1b7-609f136956fc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
