<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_512</name>
   <tag></tag>
   <elementGuidId>8149bfa7-800c-4bd2-baa7-1fbcc6e86d33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ca0c8c04-f79d-4a61-bd2e-6b9f7903617a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>4894fec1-a638-4642-b5ec-361f94d9c231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Currency</value>
      <webElementGuid>55729a83-0acb-4543-b5a2-4627783919f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>transferCashSubCashGridTbl_Id_L0VVMT_ctstellerCashBalanceDetVO.CURRENCY_CODE</value>
      <webElementGuid>96331830-e501-4904-8ecf-be2f03489564</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>1463a218-da86-4c07-baa0-520aa592619b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE</value>
      <webElementGuid>511529b6-f7b2-484d-b777-b0488e67f5b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>f8b8a334-2d7a-413e-b5f6-993f45131537</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE&quot;)</value>
      <webElementGuid>567086ae-b90d-443e-b0b3-50ee769813c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE']</value>
      <webElementGuid>43821c1c-25da-463b-bc00-c63e7e544009</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='new_1655880641080']/td[2]</value>
      <webElementGuid>d82bd2cf-03d6-466b-970d-518f19e08ee8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decimal Points'])[1]/following::td[16]</value>
      <webElementGuid>e24961c1-ddc0-4bee-ac50-55a09aa91adb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JV OP.No'])[1]/following::td[16]</value>
      <webElementGuid>51df5df4-e6fc-4fbb-a04e-29fa7833eedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OMR'])[1]/preceding::td[3]</value>
      <webElementGuid>f73fa749-5db5-46bf-b883-871a04ae5f4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::td[32]</value>
      <webElementGuid>99b26cb7-5911-4cce-b2ea-e6e11b83841c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='512']/parent::*</value>
      <webElementGuid>392d79aa-72ca-4caa-a8ee-d2485767b245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>b55134cb-caf0-4323-9f91-0fb680c940a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '512' and @id = 'td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE' and (text() = '512' or . = '512')]</value>
      <webElementGuid>dad50b45-6180-46a0-ade4-69b9f504fe1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
