<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td__1</name>
   <tag></tag>
   <elementGuidId>b8c521e4-f90e-479a-b153-40f1049a8032</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9aa374c6-5780-49ad-8623-e09a63889b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>8c5649f8-5a76-4f1b-9a19-ba2e84b850ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Currency</value>
      <webElementGuid>68ff766f-58ae-4200-9553-b1757789cbea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>transferCashSubCashGridTbl_Id_L0VVMT_ctstellerCashBalanceDetVO.CURRENCY_CODE</value>
      <webElementGuid>b94541db-3b21-4697-959c-f626bd04c596</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE</value>
      <webElementGuid>6296046d-0122-4935-9265-b32e12b70d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> </value>
      <webElementGuid>5d8cf7f7-1269-4842-95d7-756f54867ddd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE&quot;)</value>
      <webElementGuid>1d47556a-d119-4047-8844-c4c465f260a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE']</value>
      <webElementGuid>c37c7d71-156c-4b93-b1c1-b6b00c3342b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='new_1655880641080']/td[2]</value>
      <webElementGuid>2daf1e8d-b86b-4779-a041-d83503ed29cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Decimal Points'])[1]/following::td[16]</value>
      <webElementGuid>fb4d2290-eaeb-46c6-bbc5-301f1602c3be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='JV OP.No'])[1]/following::td[16]</value>
      <webElementGuid>f2a70d9e-860b-4c8a-9157-4f028da97ac3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[1]/preceding::td[32]</value>
      <webElementGuid>3e49882b-33f0-4c28-a2b9-c35c5fc2496b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[1]/preceding::td[34]</value>
      <webElementGuid>34c13a95-d4a6-4abe-9ba6-c9b2d80c0c98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>c13f4949-1430-497a-8efc-7412394b9c3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'td_transferCashSubCashGridTbl_Id_L0VVMT_1_ctstellerCashBalanceDetVO.CURRENCY_CODE' and (text() = ' ' or . = ' ')]</value>
      <webElementGuid>dbbf6c43-cca6-4c56-b820-821ae0b88611</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
