<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Available Bills_td_trsfrCashcyDenomGridT_eccaf4</name>
   <tag></tag>
   <elementGuidId>2c30b0ef-55fd-448c-bfeb-e10af7a7660f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_trsfr_denom_checkBox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_trsfr_denom_checkBox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c8058a77-8b73-4f40-8863-be712d4670d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>4bb09733-c630-4e8e-bb95-d04bbea444d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>trsfrCashcyDenomGridTbl_Id_L0VVMT_trsfr_denom_checkBox</value>
      <webElementGuid>dbfb8052-7420-47f7-8fc2-7d500af25bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_trsfr_denom_checkBox</value>
      <webElementGuid>b4b9e88f-e41b-44fd-8e25-ffedbab38adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_trsfr_denom_checkBox&quot;)</value>
      <webElementGuid>68395beb-880c-4235-8a01-5c56c96de0a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_trsfr_denom_checkBox']</value>
      <webElementGuid>2092f6cf-fccc-466b-b5ca-77d48d1f00bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[6]</value>
      <webElementGuid>68be0f99-3576-4fbc-9c41-5b43cf3d11f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Available Bills'])[1]/following::td[12]</value>
      <webElementGuid>d7b58422-3939-4475-921b-70c95a18cf0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amount'])[2]/following::td[12]</value>
      <webElementGuid>4fbd223e-c76f-4f96-9162-d741a8f31bd1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View'])[7]/preceding::td[134]</value>
      <webElementGuid>65ca88b2-8e6a-4635-b750-2498a92033db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='-'])[7]/preceding::td[136]</value>
      <webElementGuid>05495164-d4f1-41b8-970e-39c44d827942</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>1567d00c-8aec-43b7-a0ff-9e7c5b34d2f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'td_trsfrCashcyDenomGridTbl_Id_L0VVMT_1_trsfr_denom_checkBox']</value>
      <webElementGuid>b7c99291-bbbb-4d82-a892-b6d3f5a78c51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
