<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_MUSCAT MAIN BRANCH</name>
   <tag></tag>
   <elementGuidId>5efe659e-41a1-417f-85e9-37a51098914d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>92aad41c-29f6-429b-8313-9efbf3be5c0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>c4a058dc-7821-4660-a00f-e0b7d13ddcfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>MUSCAT MAIN BRANCH</value>
      <webElementGuid>67440f2d-9184-4211-9376-d9bf8da15745</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>88fff982-6961-4371-9ca6-e12f14b958ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_vaultBranchLookup_L0VVMT_BRIEF_DESC_ENG</value>
      <webElementGuid>a880d1c4-80fd-473e-ad7a-2d7dd47615eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>ae6cf323-c913-4f3a-9f81-50faaf4d369e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>MUSCAT MAIN BRANCH</value>
      <webElementGuid>ff9eec68-1d66-463e-bc42-6de340adbdac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>3946a185-363d-4599-b8fe-faa89070c887</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>d524ffb5-2a1f-4f84-b50b-1f0de5cc95df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[2]</value>
      <webElementGuid>be4cf09d-890a-4af1-a9bb-e423012c122f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remark'])[1]/following::td[6]</value>
      <webElementGuid>cd53953d-720b-49dd-8105-6ce4e898ebac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Base Currency'])[1]/following::td[6]</value>
      <webElementGuid>d7f598a7-1999-466d-894e-642fc4bf6559</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Page'])[3]/preceding::td[10]</value>
      <webElementGuid>922d5949-b5c9-48ca-b674-3949e7b4edbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='of'])[4]/preceding::td[12]</value>
      <webElementGuid>ce16e7e7-278d-4772-ad8a-f71e99cabe82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='MUSCAT MAIN BRANCH']/parent::*</value>
      <webElementGuid>ffd442ea-a624-4b14-b388-c691fc6ee21c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>2bf008c2-9bf9-46fc-bbd3-8635a2667523</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'MUSCAT MAIN BRANCH' and @id = 'td_gridtab_vaultBranchLookup_L0VVMT_1_BRIEF_DESC_ENG' and (text() = 'MUSCAT MAIN BRANCH' or . = 'MUSCAT MAIN BRANCH')]</value>
      <webElementGuid>70167308-9096-4de1-a0b0-d5127b94d82d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
