<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Vault To Vault</name>
   <tag></tag>
   <elementGuidId>c9a9f7d6-9d79-43d0-953b-f539dfac0b77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>c108dfcc-9295-426a-b556-2f3889302c57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>1a61b017-9802-44eb-8d1f-c7902e0cb5f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Vault To Vault</value>
      <webElementGuid>5a8b9b4f-bb8d-4698-967c-38a81378a9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>715b59f8-0c65-494c-8f5c-e4dbd5e70d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_trxTypeLookup_L0VVMT_SHORT_DESC_ENG</value>
      <webElementGuid>2b0c4733-8815-4d0a-95ca-69b00d630c87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG</value>
      <webElementGuid>c309bfca-ae67-4bbb-a08a-a701d6b38b00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Vault To Vault</value>
      <webElementGuid>bbbe0309-0952-4bdc-b737-7695b3dfa255</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG&quot;)</value>
      <webElementGuid>33c106dc-c388-424f-8b6d-9f76d6718e78</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG']</value>
      <webElementGuid>2afd51ee-6e84-4a90-bbfa-c0d170750ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='2']/td[2])[3]</value>
      <webElementGuid>1017ca8e-e672-486d-8175-e3a72223dcf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحويل عام'])[2]/following::td[2]</value>
      <webElementGuid>ae642985-2c18-443c-8070-af7121f73340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحويل عام'])[1]/following::td[3]</value>
      <webElementGuid>005569ca-0970-4844-803d-b43d46d5bc2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vault To Vault'])[2]/preceding::td[1]</value>
      <webElementGuid>d6d243d3-a4be-47a4-8480-133de8622929</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='تحويل من خزنة لأخرى'])[1]/preceding::td[2]</value>
      <webElementGuid>b698f2ce-6738-442c-b850-989d3d2b490b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Vault To Vault']/parent::*</value>
      <webElementGuid>da38c983-ea70-4b6c-b350-05a5b902753e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[26]/div/div[3]/div[3]/div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>59136f9f-9c3d-48d1-9228-579b4b047fb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Vault To Vault' and @id = 'td_gridtab_trxTypeLookup_L0VVMT_2_SHORT_DESC_ENG' and (text() = 'Vault To Vault' or . = 'Vault To Vault')]</value>
      <webElementGuid>3dbddb42-8a68-4f2e-a52d-0cff7212bd0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
