<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Charges</name>
   <tag></tag>
   <elementGuidId>82367c6a-fe59-48f7-9537-600d3f1736ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chequeBookChargesDiv_Q000AP']/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cb056078-07dd-492a-9e94-841f04628577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>collapsibleContainerTitle ui-state-focus ui-corner-top</value>
      <webElementGuid>e35b483b-87e6-4a3f-9155-78d2e9b8d82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Charges </value>
      <webElementGuid>6c33f1bb-ebe4-47ed-88da-e29821d4cc4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chequeBookChargesDiv_Q000AP&quot;)/div[@class=&quot;collapsibleContainerTitle ui-state-focus ui-corner-top&quot;]</value>
      <webElementGuid>9587ba16-845d-42b8-aca8-f7798f0f0eb9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chequeBookChargesDiv_Q000AP']/div[2]</value>
      <webElementGuid>7425b220-2129-4f29-b6cd-c8875c5d6e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::div[3]</value>
      <webElementGuid>0ede9140-ed8f-4418-bdb6-8d2f4707bb22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Name'])[2]/following::div[3]</value>
      <webElementGuid>ea0ecbcf-1300-4eca-a65a-07e172c5235e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Approve'])[2]/preceding::div[3]</value>
      <webElementGuid>fe8f4050-2a53-404d-9388-5dce1b85cd77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[3]/table/tbody/tr[2]/td/div/div[2]</value>
      <webElementGuid>1c8705c8-7d54-45db-a099-277d7b912ed7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Charges ' or . = 'Charges ')]</value>
      <webElementGuid>163abc7e-fac6-4968-89b4-86f91b11ed3f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
