<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status Iden_ACC_CIF</name>
   <tag></tag>
   <elementGuidId>f82ea6f1-8c42-48f4-be87-1aacde0c934a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='chequeBookGridTbl_Id_Q000AP_gs_ctschqbookVO.ACC_CIF']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6facad5c-839f-4a68-a436-5ce8ec81416b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dfa13215-f61e-4d68-a07d-8f90a02194fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ACC_CIF</value>
      <webElementGuid>12ee10f5-36d9-4309-8e7d-07001e02de8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chequeBookGridTbl_Id_Q000AP_gs_ctschqbookVO.ACC_CIF</value>
      <webElementGuid>76bf1c6c-f775-4ad3-9591-4c695834f535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chequeBookGridTbl_Id_Q000AP_gs_ctschqbookVO.ACC_CIF&quot;)</value>
      <webElementGuid>fcae5ff1-e6b2-49c7-970e-8301638a7a5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chequeBookGridTbl_Id_Q000AP_gs_ctschqbookVO.ACC_CIF']</value>
      <webElementGuid>1e4927f4-a29e-464f-882b-d7d25c391f15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_chequeBookGridTbl_Id_Q000AP']/div[2]/div/table/thead/tr[2]/th[7]/div/input</value>
      <webElementGuid>68e5852d-589b-4508-9231-03c36124ae49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[7]/div/input</value>
      <webElementGuid>cd6f7187-9e2c-4b9f-b5c5-7f8d23eef195</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'ACC_CIF' and @id = 'chequeBookGridTbl_Id_Q000AP_gs_ctschqbookVO.ACC_CIF']</value>
      <webElementGuid>b5aad589-b460-4105-84d5-12f2e346e0b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
