<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Log Out</name>
   <tag></tag>
   <elementGuidId>5b8b46f9-cfea-4673-98b1-47b646ff7611</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>6112b5fb-8016-40c2-96f7-0bbfef983798</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>logout</value>
      <webElementGuid>489ef5bd-0bc2-49cc-bc82-448f71b287c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>logout</value>
      <webElementGuid>05d97954-577f-4975-bcab-709007b05e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Log Out </value>
      <webElementGuid>ccf6d39d-97e6-4ae2-a0b4-e3eb1e1ce59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;logout&quot;)</value>
      <webElementGuid>a2a61eb4-aafb-4962-881d-c49672c18941</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='logout']</value>
      <webElementGuid>c109ae34-ff66-4698-957c-aeb9570a9829</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui_bar_div']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td[3]/table/tbody/tr/td[8]/table/tbody/tr/td[3]/label</value>
      <webElementGuid>3fe5210f-4663-479d-b4df-6bbbef8da5e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::label[1]</value>
      <webElementGuid>a5885f37-95e1-44f9-a2eb-b09a8babf19f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/following::label[2]</value>
      <webElementGuid>23e2aadb-726c-4eac-9bf1-2a622b06331a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::label[1]</value>
      <webElementGuid>c2c4e6fc-8abb-468f-b05e-a813690c99f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[1]/preceding::label[2]</value>
      <webElementGuid>e1069e93-4dde-45cc-b526-8c8d23b0ef98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Log Out']/parent::*</value>
      <webElementGuid>1a25af80-08a1-4006-8e63-d08dca112b49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/table/tbody/tr/td[3]/label</value>
      <webElementGuid>d7e82040-f504-47ec-9bd3-fda4afab60b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'logout' and (text() = 'Log Out ' or . = 'Log Out ')]</value>
      <webElementGuid>a82fac67-3ff2-4a12-91ec-7e0518026be3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
