<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Approve</name>
   <tag></tag>
   <elementGuidId>f4afe2af-21ed-4d87-925a-8bf11e63d2c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#chequeBookDefFormId_Q000AP_Approve_key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='chequeBookDefFormId_Q000AP_Approve_key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ccc57b09-e760-455b-a72f-85c2bb1376d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chequeBookDefFormId_Q000AP_Approve_key</value>
      <webElementGuid>c3718716-fac4-4e52-a791-6ff24d4e9838</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>chequeBook_approve_Q000AP</value>
      <webElementGuid>9c0b9a85-339f-4aac-86ff-c37ca329076c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>Approve_key</value>
      <webElementGuid>45a36f9b-df1e-405a-b39c-2fd227c3eb4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>47c82068-a033-4310-ad23-988f8f7dbf3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve </value>
      <webElementGuid>e16b80a3-69f2-4ce6-9d0a-4792d8df4e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chequeBookDefFormId_Q000AP_Approve_key&quot;)</value>
      <webElementGuid>48d7b81e-57c3-4d42-96fe-3a27a999453f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='chequeBookDefFormId_Q000AP_Approve_key']</value>
      <webElementGuid>308981ef-fd7e-4dcf-a708-c0ba449b46a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='chequeBook_approve_Q000AP']/span/label</value>
      <webElementGuid>4cb91a32-1e0e-4a1c-9d48-c3d9fbaad23c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges'])[1]/following::label[1]</value>
      <webElementGuid>454f5e79-f314-4694-a469-170f5582d8a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Remarks'])[1]/following::label[1]</value>
      <webElementGuid>f328d045-204f-4d20-bd7c-3d2820c8afed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright'])[1]/preceding::label[1]</value>
      <webElementGuid>1e201be1-3c07-47f9-8a2e-a0a163c3f60c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/label</value>
      <webElementGuid>3df1af9d-7641-4936-8b80-45bc135a7a28</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'chequeBookDefFormId_Q000AP_Approve_key' and (text() = 'Approve ' or . = 'Approve ')]</value>
      <webElementGuid>4954b7fd-96d0-448b-8b91-b3c1799d4514</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
