<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_10133876</name>
   <tag></tag>
   <elementGuidId>8d7df290-4c16-496b-8873-5c2380a73cc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_chequeBookGridTbl_Id_Q000AP_1_ctschqbookVO.ACC_CIF']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2069409f-a87e-4ecf-963c-c037222b0e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>6b405950-7b28-4082-a1a6-8e16e91bb8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>c7ba52c2-feeb-407a-8c41-f9f9760f89c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>10133876</value>
      <webElementGuid>c6e151a2-ac44-47cd-a63c-9257014aac42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>CIF</value>
      <webElementGuid>9563b092-33e0-4d63-8bcd-dbf50839b422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>chequeBookGridTbl_Id_Q000AP_ctschqbookVO.ACC_CIF</value>
      <webElementGuid>63bd0970-88b2-46ee-ad81-6edd46154d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_chequeBookGridTbl_Id_Q000AP_1_ctschqbookVO.ACC_CIF</value>
      <webElementGuid>546aafbb-c077-46d4-a623-8453518d065e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>10133876</value>
      <webElementGuid>dc86a3d3-221e-45d5-b5da-360570773e30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_chequeBookGridTbl_Id_Q000AP_1_ctschqbookVO.ACC_CIF&quot;)</value>
      <webElementGuid>25d4cbed-defc-498d-9c97-501f5854ef1c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_chequeBookGridTbl_Id_Q000AP_1_ctschqbookVO.ACC_CIF']</value>
      <webElementGuid>a61a1999-7d08-4830-ba82-7c6c34524c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[7]</value>
      <webElementGuid>2f033f49-2e6a-4739-bf5a-d8996d255e7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Iden'])[2]/following::td[22]</value>
      <webElementGuid>227268b6-b61c-4a32-aa24-cc07007db99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Iden'])[1]/following::td[22]</value>
      <webElementGuid>6c5a5584-a4d2-4832-b0c4-55572f0186ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::td[6]</value>
      <webElementGuid>72bc8bf4-855d-4394-ac10-ff0dfccd57a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='A'])[1]/preceding::td[7]</value>
      <webElementGuid>27ed2ce0-086a-4f7b-bb63-e32dd1f592d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='10133876']/parent::*</value>
      <webElementGuid>fec91012-511f-4883-b652-036343a80ee6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[7]</value>
      <webElementGuid>297f5def-690b-47b4-b936-f487f7777da2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '10133876' and @id = 'td_chequeBookGridTbl_Id_Q000AP_1_ctschqbookVO.ACC_CIF' and (text() = '10133876' or . = '10133876')]</value>
      <webElementGuid>5aed0680-1428-45b2-96fd-ae2c9ff0ef02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
