<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Additional Details</name>
   <tag></tag>
   <elementGuidId>30192e7b-68f5-4668-9982-6355524fae46</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Additional Details&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='fomMainTabs2_F00I1MT']/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>545a3dc3-1199-4b1b-a693-ceda7b619ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#fomMainTabs-2_F00I1MT</value>
      <webElementGuid>b98be6ac-07fc-4945-ade8-e0a8ed6fd851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Additional Details</value>
      <webElementGuid>bd108783-f0ab-4453-9f17-f3784cb46a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Additional Details</value>
      <webElementGuid>c1a07360-caa0-409b-a96b-bdb861db13a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomMainTabs2_F00I1MT&quot;)/a[1]</value>
      <webElementGuid>d3ec7f1e-b160-4518-9c80-e4bf32b3c879</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='fomMainTabs2_F00I1MT']/a</value>
      <webElementGuid>b16dfe49-2af0-4740-87ca-f33c339f1366</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Name &amp; Address'])[1]/following::a[1]</value>
      <webElementGuid>a669a9a3-c2c2-445a-b9be-93f4592fb76e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason'])[2]/following::a[2]</value>
      <webElementGuid>b7363189-c2c0-493d-a2f7-c62296fccae4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='References'])[1]/preceding::a[1]</value>
      <webElementGuid>6205829e-d5fe-44b5-b2f2-a4e7e9d380fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#fomMainTabs-2_F00I1MT')]</value>
      <webElementGuid>0233f105-dc67-4635-8593-7447533f3671</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/a</value>
      <webElementGuid>6e0b8580-a8ce-4603-abe7-3e357b83a8b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#fomMainTabs-2_F00I1MT' and @title = 'Additional Details' and (text() = 'Additional Details' or . = 'Additional Details')]</value>
      <webElementGuid>1cee50ba-1c97-4b8e-8cf1-d6a47d39f60c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
