<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FATCA</name>
   <tag></tag>
   <elementGuidId>9d4e4d2e-2b73-4a7c-9f41-fae5d437dfc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fom_fatca_details_btn_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fom_fatca_details_btn_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>59d1006a-4345-4989-9e96-42867f0628df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25b06844-31a1-4b83-9dc4-55474a8ef49f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fom_fatca_details_btn_F00I1MT</value>
      <webElementGuid>d297e82b-e6af-4122-a447-696910a70662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>a6597070-81fb-4617-8b8d-325209b4d6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>freezeonsubmit</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bacb5d76-d639-43cb-93ad-89d179734bc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dynamicScreen_openDynamicScreen(1,null,'fom_fatca_details_btn_F00I1MT', 700,500,null,false,'FATCA' );event.stopImmediatePropagation();</value>
      <webElementGuid>c06fece9-a049-45fa-96fd-6061d97ef76d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary ui-state-hover ui-state-focus</value>
      <webElementGuid>cd744472-61a7-481c-8263-7a9231d25b4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>671c51c5-fa01-42a1-bc2f-c38dd8f07662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>eadfa6e5-0fe4-4bda-95c8-a9e527da1eba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FATCA  
</value>
      <webElementGuid>dfdf1fe5-7264-49de-b5bc-ca8a45298963</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fom_fatca_details_btn_F00I1MT&quot;)</value>
      <webElementGuid>c50b50a4-6df0-413e-87dc-f1030bd6d412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fom_fatca_details_btn_F00I1MT']</value>
      <webElementGuid>ffcef567-85ec-43af-a739-395928a37450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fomButtonToolbar_F00I1MT']/div[4]/div[7]/button</value>
      <webElementGuid>36c113d4-06b1-441b-af8f-84373e237663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges Waiver'])[1]/following::button[1]</value>
      <webElementGuid>008b4093-4f28-447e-a3f0-b6bc7ed8f13f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proxies'])[1]/following::button[1]</value>
      <webElementGuid>88137c64-1218-40c9-9bcc-5abf128e8ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PEP'])[1]/preceding::button[1]</value>
      <webElementGuid>e2955a33-a22a-4d8e-a042-9bf800a96304</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button</value>
      <webElementGuid>c3273f66-eb52-420d-b492-e2d5a6e50067</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'fom_fatca_details_btn_F00I1MT' and (text() = ' FATCA  
' or . = ' FATCA  
')]</value>
      <webElementGuid>74ad4db7-79da-45ef-bc5e-557bc3ae53a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
