<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PEP</name>
   <tag></tag>
   <elementGuidId>777cda61-cf6b-417d-ba21-abc283f93414</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fom_pep_details_btn_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fom_pep_details_btn_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64131db0-d221-4d9f-b557-d6bc46e01b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>82818f78-b14e-49f9-b367-403bb5c43de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fom_pep_details_btn_F00I1MT</value>
      <webElementGuid>8365a0f0-8933-4944-863e-06f512eacfa6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>1507823f-a17c-4207-b8cd-3bad22c17273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>freezeonsubmit</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8e56a79-93b8-4dde-8f2b-029818b0cb31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dynamicScreen_openDynamicScreen(2,null,'fom_pep_details_btn_F00I1MT', 700,500,null,false,'PEP' );event.stopImmediatePropagation();</value>
      <webElementGuid>6d2a70ca-64f6-434a-a638-c489534fe7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary ui-state-hover ui-state-focus</value>
      <webElementGuid>93014b07-ecf0-4111-bd2f-461809368bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>25bc229b-42c6-4ac1-8616-068abaf49c2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2a1a5eb9-b045-4a12-82b1-3627e6401ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> PEP  
</value>
      <webElementGuid>2aa6fe6f-ec41-445c-908e-6741b07abf4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fom_pep_details_btn_F00I1MT&quot;)</value>
      <webElementGuid>ae1574fa-9c00-4cdc-a899-25caf7298fd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fom_pep_details_btn_F00I1MT']</value>
      <webElementGuid>d73df7d5-788a-447e-8417-494de8e2e3b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fomButtonToolbar_F00I1MT']/div[5]/div/button</value>
      <webElementGuid>c59a6625-64d3-41d9-ac59-2892d3e94bbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FATCA'])[1]/following::button[1]</value>
      <webElementGuid>29f07f9b-d7d0-4f77-82c7-fa1b0570230f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges Waiver'])[1]/following::button[2]</value>
      <webElementGuid>55b6b950-c296-430d-bc5f-98fe31d3774f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package Products'])[1]/preceding::button[1]</value>
      <webElementGuid>cc5c8e96-29ba-4594-a730-40bccb259dc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>458c436d-9c9e-437a-b011-f6b9e030eccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'fom_pep_details_btn_F00I1MT' and (text() = ' PEP  
' or . = ' PEP  
')]</value>
      <webElementGuid>4e793b3a-216b-44cf-981b-3296e7340e9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
