<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>center</name>
   <tag></tag>
   <elementGuidId>602071ba-a422-4377-a44e-d7bc386aded2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>center</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='div__popup_path_sol_ok']/center</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>f79d43c5-9641-4e45-bf7a-51d39f459c1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;div__popup_path_sol_ok&quot;)/center[1]</value>
      <webElementGuid>ed2baf06-979f-46b6-b468-76c32fbd9023</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div__popup_path_sol_ok']/center</value>
      <webElementGuid>898eaa5a-3e68-417f-bb42-d9c4247b3eb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[2]/following::center[1]</value>
      <webElementGuid>d69c10bd-1d3b-4c59-a069-cb21957763b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Missing Elements'])[1]/following::center[1]</value>
      <webElementGuid>18d58960-2835-4a6b-9fa7-974aa6e299ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center</value>
      <webElementGuid>bada7d79-e2bb-4c85-9e8f-acbf369e2f06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
