<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PO BOX Area_addressCO.POBOX_AREA</name>
   <tag></tag>
   <elementGuidId>5f5b5245-12db-4697-9883-a56b53b9f693</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lookuptxt_addressCO_POBOX_AREA_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookuptxt_addressCO_POBOX_AREA_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71d213c4-c34f-4388-acd3-56be9ff8d5d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9fa7eeb6-546e-4374-90d9-56163197c5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a396e58d-8620-4708-a736-ab84b28d57c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookuptxt_addressCO_POBOX_AREA_F00I1MT</value>
      <webElementGuid>f2453689-c463-431a-a665-4492f22b42bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>beforedepevent</name>
      <type>Main</type>
      <value>setCustomPageRefToSession('F00I1MT')</value>
      <webElementGuid>4d6f5a68-0636-4fa4-aa86-fa8caabc3b85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>reSetOriginalPageRefToSession('F00I1MT'),fomNameAddressLanguageDropDown_onChange('F00I1MT')</value>
      <webElementGuid>00928fb3-1203-4400-b9d5-e51aeac0f958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input liveSearchText liveSearchCompSize ui-state-focus liveSearchInputCorner</value>
      <webElementGuid>cac74071-2044-43ad-907f-d3da306b5d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.POBOX_AREA</value>
      <webElementGuid>3eb1262e-751c-474a-82e9-afeb0763359c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57644d01-16b2-4b12-9aa9-0601c30758f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>PO BOX Area</value>
      <webElementGuid>0a2bba2a-5670-49ab-9e41-20e8053bce29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>PO BOX Area</value>
      <webElementGuid>6d8ab813-b8dc-4983-84a2-266d49f30513</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>317e666a-e944-4dbd-a86c-08cc32483274</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f643c37a-b02b-432b-9ece-00a703657ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>6b6ef5b4-699b-4de7-8082-d318ce4385e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>33bdeccc-65d2-4887-b7ae-cbca426bf9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>PO BOX Area</value>
      <webElementGuid>7a64e166-60e2-4071-8cf7-19695d758486</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookuptxt_addressCO_POBOX_AREA_F00I1MT&quot;)</value>
      <webElementGuid>6773fff6-5fc2-41df-a9d3-878eb2bc3d50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookuptxt_addressCO_POBOX_AREA_F00I1MT']</value>
      <webElementGuid>4af462ca-a586-4c8c-bb15-6bd413a7b6c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lookupid_addressCO_POBOX_AREA_F00I1MT']/div/input</value>
      <webElementGuid>3079cc07-c328-4ffd-baa7-bef26e694790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>34feb28d-4470-45bb-a701-ad07c827f5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lookuptxt_addressCO_POBOX_AREA_F00I1MT' and @name = 'addressCO.POBOX_AREA' and @title = 'PO BOX Area']</value>
      <webElementGuid>4c1f5f83-3b70-49fe-9383-2ef29d52bfe2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
