<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_First Name_fomCO.cifVO.FIRST_NAME_ENG</name>
   <tag></tag>
   <elementGuidId>650d4b77-3e30-4a17-a4e1-b990c6c9f3d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cifVO_FIRST_NAME_ENG_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifVO_FIRST_NAME_ENG_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7e838224-3841-4a5b-8728-4b3e522425ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>593dec9a-bc27-4910-a89c-2b9cf694ede7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>bf685308-5823-4812-a32d-86c5fbe9647a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.FIRST_NAME_ENG</value>
      <webElementGuid>1bcbc15b-9a8b-4520-b99d-faf9b55f621a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>d1a3eff2-3b38-49db-810e-47b254a5e64d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>2f5feeb0-6c06-4ba3-80da-a0d68538ed95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_FIRST_NAME_ENG_F00I1MT</value>
      <webElementGuid>612a0519-8ce6-4edf-b48e-eaa56cecf2c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>fomNameAddressTabLongName_onChange('true')</value>
      <webElementGuid>85f3848e-fcdb-467e-a40d-51993beb7a48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cifVO_SHORT_NAME_ENG_F00I1MT:fomCO.cifVO.SHORT_NAME_ENG,cifVO_LONG_NAME_ENG_F00I1MT:fomCO.cifVO.LONG_NAME_ENG</value>
      <webElementGuid>ac9669b4-197d-4b8b-8bcd-2d289d953210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_dependencyByFirstNameEng</value>
      <webElementGuid>0848c642-e200-43ba-ac60-1b65bf9f2164</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.cifVO.FIRST_NAME_ENG:cifVO_FIRST_NAME_ENG_F00I1MT,fomCO.cifVO.SEC_NAME_ENG:cifVO_SEC_NAME_ENG_F00I1MT,fomCO.cifVO.THIRD_NAME_ENG:cifVO_THIRD_NAME_ENG_F00I1MT,fomCO.cifVO.LAST_NAME_ENG:cifVO_LAST_NAME_ENG_F00I1MT,fomCO.cifVO.SHORT_NAME_ENG:cifVO_SHORT_NAME_ENG_F00I1MT,fomCO.addressCommonCO.COUNTRY:lookuptxt_addressCO_COUNTRY_F00I1MT,fomCO.cifVO.CIF_TYPE:lookuptxt_cifVO_CIF_TYPE_F00I1MT,fomCO.cifVO.LONG_NAME_ENG:cifVO_LONG_NAME_ENG_F00I1MT,_pageRef:_pageRef</value>
      <webElementGuid>bafcbff3-b9d7-45c0-9980-86bad2e99af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>200423db-d468-40c7-a1c4-ce99448abed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>First_Name_eng_key</value>
      <webElementGuid>7d4cb47e-c929-4f62-a0b8-50a779e149ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>First Name</value>
      <webElementGuid>48d6ad37-69ba-4de5-8a70-92263dbc74bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_FIRST_NAME_ENG_F00I1MT&quot;)</value>
      <webElementGuid>2decb577-cefd-430f-baf1-683ea50ecf1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifVO_FIRST_NAME_ENG_F00I1MT']</value>
      <webElementGuid>790f144b-53f8-41b1-aab9-7ed70b94943f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fomNameDetailsDialog_F00I1MT']/table/tbody/tr/td[2]/input</value>
      <webElementGuid>4176fc5e-6355-432b-bfc3-9ce6814bf698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>4f444be4-f7e9-44b3-ab15-dacea15650e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifVO.FIRST_NAME_ENG' and @id = 'cifVO_FIRST_NAME_ENG_F00I1MT' and @title = 'First Name']</value>
      <webElementGuid>95c8146e-975a-42f6-9feb-5997b0c16385</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
