<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Way No_addressCO.ADDRESS3_ENG</name>
   <tag></tag>
   <elementGuidId>8ed7c2cd-3c26-46dc-a302-7a2a362b520f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressCO_ADDRESS3_ENG_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_ADDRESS3_ENG_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1b0cfeb-97a1-4d96-979e-fa3aceeb3b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3fc6c206-e8c5-4de1-adaf-b95cf1d6d020</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2a2d3e3d-2142-4708-8325-8a04377cbbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.ADDRESS3_ENG</value>
      <webElementGuid>6a6c1ad3-6c17-4e9d-b0eb-327695693cac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>967f1887-8691-4ce6-ab9a-41520db35f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>26694d2e-994b-413b-9864-aab6babb335b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_ADDRESS3_ENG_F00I1MT</value>
      <webElementGuid>62d37563-e837-42af-8af4-1186f33f4594</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_ADDRESS3_ENG_F00I1MT:fomCO.addressField</value>
      <webElementGuid>93fedaba-d04d-42b8-9984-e6331a361d6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>f971c253-e8e8-4a16-b027-ce00ac16be6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_ADDRESS3_ENG_F00I1MT</value>
      <webElementGuid>a866612c-a8d5-4087-b178-c9643ef42cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Way No</value>
      <webElementGuid>7b248423-3546-4977-a0a2-b63a1728c849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Way No</value>
      <webElementGuid>db64a823-2764-45e0-8295-dd7af043786c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Way No</value>
      <webElementGuid>9922f637-8e6f-4f7a-9dd8-2b8eb7229ac7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_ADDRESS3_ENG_F00I1MT&quot;)</value>
      <webElementGuid>5b00fd86-3e2c-44a9-b88b-1ee15875ff85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_ADDRESS3_ENG_F00I1MT']</value>
      <webElementGuid>b0b22bca-2872-4f97-a9e2-c67d9a50a0ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addressSectionTbl_Id_ENG_F00I1MT']/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>08fd3297-c483-45cb-887f-6088d6eff338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>ca1a9eb9-8b3b-432d-b06d-58a63a3823f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.ADDRESS3_ENG' and @id = 'addressCO_ADDRESS3_ENG_F00I1MT' and @title = 'Way No']</value>
      <webElementGuid>61ec3166-905b-4ad0-a84c-ccec76b489f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
