<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Type_fomCO.idTypeDesc</name>
   <tag></tag>
   <elementGuidId>b1f5622d-e020-4492-abd9-adb6efbc585c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fomCO_idTypeDesc_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fomCO_idTypeDesc_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d79a24a8-483c-4038-9601-8c86c0e313b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a4ff253-d908-44af-8356-87bd98a4a4b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b51973db-1e6a-43d3-b5ac-45b3b0f9aea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.idTypeDesc</value>
      <webElementGuid>05e5abf3-385d-4459-90bd-3c7136aa63b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>303f33a8-df31-4ef7-a9be-f652525b9741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>readonly</name>
      <type>Main</type>
      <value>readonly</value>
      <webElementGuid>c805d70c-5289-4d95-8c39-13e086e09909</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6261166e-eeb6-4cd8-a690-f247d883853a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fomCO_idTypeDesc_F00I1MT</value>
      <webElementGuid>9632fa49-8ce4-4f57-9ec0-935119d9c915</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomCO_idTypeDesc_F00I1MT&quot;)</value>
      <webElementGuid>aaa2be8e-1b26-4c04-b1bf-455fe274a6f1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fomCO_idTypeDesc_F00I1MT']</value>
      <webElementGuid>9737ea3c-6986-4c53-bc4a-20661fccfe30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel1']/div[3]/table/tbody/tr[2]/td/table/tbody/tr/td[3]/input[3]</value>
      <webElementGuid>1a0d5aec-9ae7-42e7-a6b7-75c733b07b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td/table/tbody/tr/td[3]/input[3]</value>
      <webElementGuid>d1b906ff-f498-4283-b891-b82e6a500765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.idTypeDesc' and @id = 'fomCO_idTypeDesc_F00I1MT']</value>
      <webElementGuid>7440fde2-9395-4116-b725-e604df041896</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
