<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Postal Code_addressCO.POSTAL_CODE</name>
   <tag></tag>
   <elementGuidId>e4b8fe46-a8a6-4818-80af-647bffb6ab6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lookuptxt_addressCO_POSTAL_CODE_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookuptxt_addressCO_POSTAL_CODE_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a47d2458-a0be-4146-a742-46518d8e6e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4360bbd4-7c36-46c7-a3f1-a356bda0e2ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7417e9b0-4c1f-4a22-8a81-58ec1a855bd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookuptxt_addressCO_POSTAL_CODE_F00I1MT</value>
      <webElementGuid>bf03b467-fd62-4d5f-9a42-de16b3603a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input liveSearchText liveSearchCompSize ui-state-focus liveSearchInputCorner</value>
      <webElementGuid>7c586ebd-1d9c-4e74-ae6b-3b4f0466ed8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.POSTAL_CODE</value>
      <webElementGuid>239ebcb5-2a13-4893-a3ca-8262a3aba937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>738037f2-fe09-408a-8317-3ec1c33828b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Postal Code</value>
      <webElementGuid>789b7e19-252f-463e-a8e4-b6bd9da2b4d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Postal Code</value>
      <webElementGuid>d887a2ca-dc73-4e7c-a26e-be443fb6e977</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>655e6599-2535-41b9-a064-e7930b07c952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e36ce18a-4653-48d5-afb6-4144e93d6f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>9a1e4a6a-0667-4f7d-9e32-9315af6dee48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>d344247a-3746-4781-a2eb-51c1ceb53acd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Postal Code</value>
      <webElementGuid>eba6962d-c35c-4f7a-9322-00df7473490c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookuptxt_addressCO_POSTAL_CODE_F00I1MT&quot;)</value>
      <webElementGuid>9fe56864-6df3-4089-992d-239cf9599edd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookuptxt_addressCO_POSTAL_CODE_F00I1MT']</value>
      <webElementGuid>3e060896-202a-433f-bacb-1e14fd781454</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lookupid_addressCO_POSTAL_CODE_F00I1MT']/div/input</value>
      <webElementGuid>2b4c52c4-0930-4484-9d57-3a9ed604d835</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[8]/td[2]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>f5e946b0-5966-41dc-bec9-c9d2e77e146e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lookuptxt_addressCO_POSTAL_CODE_F00I1MT' and @name = 'addressCO.POSTAL_CODE' and @title = 'Postal Code']</value>
      <webElementGuid>a8ed5586-3253-41e0-bde7-c4214ab93a7a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
