<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address Description_addressCO.ADDRESS_DESC</name>
   <tag></tag>
   <elementGuidId>2d582f31-f11d-411c-9e9c-e75f830f64c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressCO_ADDRESS_DESC_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_ADDRESS_DESC_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d55c1434-47c8-4b0a-893e-c2b8097a083c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9886cdf6-174e-4a05-8ea7-e552a2c86344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5aa3acf-cc13-4759-9efb-dde66c1835e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.ADDRESS_DESC</value>
      <webElementGuid>dddadc1d-21f4-4c2d-9b0c-d02b7017cfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>799e4749-1db2-4dfb-be42-1eeceef449e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>33c19280-7c52-4141-b609-68ec1ce791fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_ADDRESS_DESC_F00I1MT</value>
      <webElementGuid>7d57505b-44d9-4da8-b820-e2c6578c8f69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_ADDRESS_DESC_F00I1MT&quot;)</value>
      <webElementGuid>6aa348dd-6ce7-4e44-aa20-ea07f5b16722</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_ADDRESS_DESC_F00I1MT']</value>
      <webElementGuid>53a3cae7-1042-46b5-9287-1d2ecaaee09b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addressSectionTbl_Id_ENG_F00I1MT']/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>6098919f-54df-49b8-8fbf-4d4467656237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>f286e1b5-3f36-47f6-a5d4-7b7e299c170b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.ADDRESS_DESC' and @id = 'addressCO_ADDRESS_DESC_F00I1MT']</value>
      <webElementGuid>5383ef20-f370-4e1f-8cf1-bd36e1c775d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
