<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile No (2)_addressCO.OTHER_TEL</name>
   <tag></tag>
   <elementGuidId>c70fd06e-8653-4fd3-87d9-62fa4e290560</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressCO_OTHER_TEL_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_OTHER_TEL_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a61b3c15-b84d-49ba-9671-242dd3b004a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6ec3a828-e960-4950-81e0-e107d300f535</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ac557a2b-a862-4f39-9eb2-133141eb00cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.OTHER_TEL</value>
      <webElementGuid>1a586674-709e-4e83-9277-3c5c5c1462c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>2c3fc235-d7c7-48ef-abd7-9708427893fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>4f9b0c0c-2c70-4c88-b0bc-4a2fee19cbfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_OTHER_TEL_F00I1MT</value>
      <webElementGuid>85955b56-a375-4a6d-a422-89588bcc391a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_OTHER_TEL_F00I1MT:fomCO.addressField</value>
      <webElementGuid>103570fe-c977-449a-8481-86d02c31c6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>6c082223-4dc9-4c8f-a1e6-eb09b804cae6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_OTHER_TEL_F00I1MT</value>
      <webElementGuid>6aef1fc9-a871-48fd-beed-3e6099e0e55b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Mobile No (2)</value>
      <webElementGuid>c58adf6e-84c3-487f-80ba-9397e08bf7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Mobile No (2)</value>
      <webElementGuid>3d17437a-82d6-479a-8aac-33a4befda783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>cc0a28d1-da60-4955-996f-a1fca6512992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mobile No (2)</value>
      <webElementGuid>ca2cf444-ebfa-4d58-82bb-5aded1eba0a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_OTHER_TEL_F00I1MT&quot;)</value>
      <webElementGuid>c0fb95b5-40a6-4daf-bda9-647d2a524d86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_OTHER_TEL_F00I1MT']</value>
      <webElementGuid>78ae1706-a494-4873-a46b-874a1f19bd79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addrTbl_F00I1MT']/tbody/tr[3]/td[2]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>71632325-fe98-463c-bcdb-4c2d8311ebbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>cdea6838-1d97-4472-b6ef-fa73c601d729</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.OTHER_TEL' and @id = 'addressCO_OTHER_TEL_F00I1MT' and @title = 'Mobile No (2)']</value>
      <webElementGuid>3b1c5fb9-b9b3-49d2-a576-7030776c5f9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
