<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Short Name_fomCO.cifVO.SHORT_NAME_ENG</name>
   <tag></tag>
   <elementGuidId>e4761db7-c83a-4695-ab54-1bdcd2de5d75</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cifVO_SHORT_NAME_ENG_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifVO_SHORT_NAME_ENG_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6664ad46-cf24-433a-b4eb-f151bae65308</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>aa4406bf-1f63-40bb-9295-44f121bb9ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5d47c24-6751-4de9-b248-02d9426e64c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.SHORT_NAME_ENG</value>
      <webElementGuid>a5ed51f5-7ee3-4cbb-84e1-b40fdcd45a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>009e2065-7169-42cb-baca-71356b2f07d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>3f1bc7f0-8279-4a3e-9668-652c83820ecf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_SHORT_NAME_ENG_F00I1MT</value>
      <webElementGuid>99b30773-b7f0-4451-9c92-8bbf24cfe3fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fomNameAddressTabBriefName_onChange();</value>
      <webElementGuid>352987ea-d0c3-4135-9e29-bacd574ffe4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Short Name</value>
      <webElementGuid>3e84deb4-7557-415f-ad24-3c577516c2e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Short_name_eng_key</value>
      <webElementGuid>76714bce-63f1-4f91-9f1f-b09bb1b0592d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Short Name</value>
      <webElementGuid>c4ffde4a-360a-485b-b7e9-0edc8b6ee3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_SHORT_NAME_ENG_F00I1MT&quot;)</value>
      <webElementGuid>41d0b0ca-ece1-4f85-b578-cfcc5c28933a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifVO_SHORT_NAME_ENG_F00I1MT']</value>
      <webElementGuid>5a7d49a3-ff8f-42ab-96b5-f3cdc9c6e99c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel2']/div[3]/table/tbody/tr[3]/td[2]/input[2]</value>
      <webElementGuid>66825253-83c3-43e9-8851-c5c86193e608</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input[2]</value>
      <webElementGuid>4e48ee6d-3373-4759-aee0-13312e9fed08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifVO.SHORT_NAME_ENG' and @id = 'cifVO_SHORT_NAME_ENG_F00I1MT' and @title = 'Short Name']</value>
      <webElementGuid>527fb0bd-417a-4dc5-a64c-e15dda4f8741</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
