<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifVO.CIF_TYPE</name>
   <tag></tag>
   <elementGuidId>e79dd66c-f2f3-4109-86a5-9f1a64d974ec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lookuptxt_cifVO_CIF_TYPE_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookuptxt_cifVO_CIF_TYPE_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d027ae6-3787-4e73-a816-04b4c16579a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4cf7777e-656d-4d40-a767-e0e7c5400df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>6caacb06-e926-4e0e-889e-d889129c8d57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookuptxt_cifVO_CIF_TYPE_F00I1MT</value>
      <webElementGuid>958a3e35-6d84-4f81-84b1-ba049b2a3ced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>fomMaint_cifTypeAfterDep</value>
      <webElementGuid>81211e25-77b0-4d3b-ac21-63463f2e9c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input liveSearchText liveSearchCompSize ui-state-focus liveSearchInputCorner</value>
      <webElementGuid>dce36cb6-fa75-42e5-b761-86da23e87dbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.CIF_TYPE</value>
      <webElementGuid>88101556-05b1-4c3a-a1af-fa2a1dcf3b7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b30ee47a-14f3-4fab-92e6-cd568ba4abe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>96da81e4-1c94-41c1-9966-b1a9ffc17dc1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>be07e707-85a3-43e5-9cff-cc057df66ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c4f93edf-bca8-461a-83ad-7b32b2893042</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>8916965a-7dbf-49a8-bbb1-2c2501205ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>a466b010-e5f2-4124-8b07-7478529478c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>relateddescelt</name>
      <type>Main</type>
      <value>fomCO_cifTypeDesc_F00I1MT</value>
      <webElementGuid>bea3087e-79a5-492a-9305-8d6668dc8f5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookuptxt_cifVO_CIF_TYPE_F00I1MT&quot;)</value>
      <webElementGuid>f7c9da5b-cf6d-47ff-907a-d1281bc72aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookuptxt_cifVO_CIF_TYPE_F00I1MT']</value>
      <webElementGuid>6242e189-59e8-4205-a05c-cc097c041c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lookupid_cifVO_CIF_TYPE_F00I1MT']/div/input</value>
      <webElementGuid>2d643660-94e5-4b50-80e1-7aa58e0733ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>5e555607-77fe-415c-81c6-948ac14abe3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lookuptxt_cifVO_CIF_TYPE_F00I1MT' and @name = 'fomCO.cifVO.CIF_TYPE']</value>
      <webElementGuid>4b1f7606-ad70-4b39-8a55-0ea7b094a39b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
