<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifVO.BIRTH_DATE</name>
   <tag></tag>
   <elementGuidId>2923272b-89ac-416f-b913-748a3934ce5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cifVO_BIRTH_DATE_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifVO_BIRTH_DATE_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9e2321d-9647-456f-bec6-938eccd1f084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f532b79b-43b6-4952-9bb0-ac3d7d99912f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>359a2de1-b0b2-45b3-b041-ea5a9684ecd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.BIRTH_DATE</value>
      <webElementGuid>3f835258-f0be-49db-aef2-a65441514f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12px</value>
      <webElementGuid>f6f8deff-019c-4d16-b03f-7a7f451170f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input ui-state-focus ui-corner-all path-text-size hasDatepicker</value>
      <webElementGuid>1a07e4c1-9116-44c6-8892-a58c87db73b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_BIRTH_DATE_F00I1MT</value>
      <webElementGuid>4be92714-0cca-4f6c-940c-ee982786e512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cifVO_BIRTH_DATE_F00I1MT:fomCO.cifVO.BIRTH_DATE</value>
      <webElementGuid>acac699c-a2ec-46ae-bbfa-a8f612a642c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateBirthDate</value>
      <webElementGuid>b0da0e74-149a-40ef-8ef0-213a8142ecba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.cifVO.BIRTH_DATE:cifVO_BIRTH_DATE_F00I1MT,fomCO.cifVO.ID_DELIVERY_DATE:cifVO_ID_DELIVERY_DATE_F00I1MT,fomCO.cifVO.TYPE:cifVO_TYPE_F00I1MT,fomCO.cifVO.CIF_TYPE:lookuptxt_cifVO_CIF_TYPE_F00I1MT</value>
      <webElementGuid>430211f9-7c39-4470-bcdf-78410c33614d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>9d639fd9-d66d-42e8-b75f-0bd497ecde75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Date_of_Birth_key</value>
      <webElementGuid>092e2d9b-75aa-4755-80f9-5aff1b6c4100</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>d671998f-bff3-49dd-a534-ce38f550e410</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5200fdb7-0483-4243-9783-96d046704f65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_BIRTH_DATE_F00I1MT&quot;)</value>
      <webElementGuid>442d9702-5be7-4fbc-ae5d-72590bd0e5dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifVO_BIRTH_DATE_F00I1MT']</value>
      <webElementGuid>4589522d-6954-44d7-b188-b754fb9536bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel1']/div[3]/table/tbody/tr[6]/td[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>683aae78-0fbe-45be-ab0c-4f214da3dcec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>1ff6ef50-ec5d-47b6-9a29-9796aa17811e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifVO.BIRTH_DATE' and @id = 'cifVO_BIRTH_DATE_F00I1MT' and @title = 'Date of Birth']</value>
      <webElementGuid>9cf9d9af-3230-4810-9c3f-dd0f886943ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
