<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Second Name_fomCO.cifVO.SEC_NAME_ENG</name>
   <tag></tag>
   <elementGuidId>7c675f31-9af1-43a8-9328-a49b3de103bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cifVO_SEC_NAME_ENG_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifVO_SEC_NAME_ENG_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>efa34271-0870-4a0a-a4fb-39b2b7273630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>887780f1-dfd0-4c89-9c61-4bc173c8fc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>02c41ba3-7dd3-425c-b2ed-e24482488a7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.SEC_NAME_ENG</value>
      <webElementGuid>a7fef1f3-4c50-4579-96e7-ea671d7e9d5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>285e599e-f775-4bb7-8ce6-4edb3f283341</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>b943fd73-e474-4031-9818-9091a3c32893</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_SEC_NAME_ENG_F00I1MT</value>
      <webElementGuid>d1bc2b6a-d438-4bf1-8a45-4821d06b634f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>fomNameAddressTabLongName_onChange('true')</value>
      <webElementGuid>f8ce12b6-8817-4fdc-bab1-2d580b5d57b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cifVO_SHORT_NAME_ENG_F00I1MT:fomCO.cifVO.SHORT_NAME_ENG,cifVO_LONG_NAME_ENG_F00I1MT:fomCO.cifVO.LONG_NAME_ENG</value>
      <webElementGuid>62af95aa-c463-4415-a695-7f1f7b914103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_dependencyBySecNameEng</value>
      <webElementGuid>44510923-312c-4dce-a11e-d21ddc12a7c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.cifVO.FIRST_NAME_ENG:cifVO_FIRST_NAME_ENG_F00I1MT,fomCO.cifVO.SEC_NAME_ENG:cifVO_SEC_NAME_ENG_F00I1MT,fomCO.cifVO.THIRD_NAME_ENG:cifVO_THIRD_NAME_ENG_F00I1MT,fomCO.cifVO.LAST_NAME_ENG:cifVO_LAST_NAME_ENG_F00I1MT,fomCO.cifVO.SHORT_NAME_ENG:cifVO_SHORT_NAME_ENG_F00I1MT,fomCO.addressCommonCO.COUNTRY:lookuptxt_addressCO_COUNTRY_F00I1MT,fomCO.cifVO.CIF_TYPE:lookuptxt_cifVO_CIF_TYPE_F00I1MT,fomCO.cifVO.LONG_NAME_ENG:cifVO_LONG_NAME_ENG_F00I1MT,_pageRef:_pageRef</value>
      <webElementGuid>61e51a57-bd8a-45d6-b67b-24c3fc77798c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_SEC_NAME_ENG_F00I1MT&quot;)</value>
      <webElementGuid>c913e25e-bac2-4c8b-ae8c-f5554d695b1d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifVO_SEC_NAME_ENG_F00I1MT']</value>
      <webElementGuid>ac9c79bf-cf15-4369-a8c7-e54de5e8b2e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fomNameDetailsDialog_F00I1MT']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>5ae81d29-c0e1-452c-aea4-b9b157e972e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]/input</value>
      <webElementGuid>77895eee-325d-4ad0-9c52-d7b385bc744e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifVO.SEC_NAME_ENG' and @id = 'cifVO_SEC_NAME_ENG_F00I1MT']</value>
      <webElementGuid>57a2c746-c2f7-4dc0-a93e-dd0eb136d970</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
