<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifExtendedVO.COUNTRY_OF_ISSUANCE</name>
   <tag></tag>
   <elementGuidId>6b547a4e-7172-4efa-b5d9-799c2ebe0acd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#lookuptxt_countryOfIssuance_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookuptxt_countryOfIssuance_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b3c91db2-c70c-438e-9b39-e7b939e6befc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ebf4df8c-b1a6-4711-a7d7-4dd64c94a66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ac10dbc0-883f-4f36-a19f-f399db01402d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookuptxt_countryOfIssuance_F00I1MT</value>
      <webElementGuid>542352cd-b56a-4595-a9d5-56bddb241d10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input liveSearchText liveSearchCompSize ui-state-focus liveSearchInputCorner</value>
      <webElementGuid>a5556abb-52da-49dd-8200-eba29095a30e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifExtendedVO.COUNTRY_OF_ISSUANCE</value>
      <webElementGuid>f345d6be-61c1-4deb-a983-93d3d49d94d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>9c9716f2-5d73-4c57-a48d-4910a281b9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0e3efa37-0752-4a2b-b76f-7075a47b3001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>673fac5c-01a8-481c-810f-fd6d4ab183bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>659ca2f8-9b4f-46ea-818b-2529bef9717a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>relateddescelt</name>
      <type>Main</type>
      <value>countryOfIssuanceDesc_F00I1MT</value>
      <webElementGuid>2322de5f-9ab7-4973-bc57-0b742441357b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>78a7e8f4-16dc-4967-b0a7-ef9e2e9839ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookuptxt_countryOfIssuance_F00I1MT&quot;)</value>
      <webElementGuid>21076067-b32c-4ce6-863d-4cc7bdd5dd74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookuptxt_countryOfIssuance_F00I1MT']</value>
      <webElementGuid>ab0bd2a4-158e-4a80-bf5a-45c245bf27e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lookupid_countryOfIssuance_F00I1MT']/div/input</value>
      <webElementGuid>2c8b0dc5-91a0-4472-8ca4-e2922f916d3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>735c20c0-188e-4af5-bb50-52b4217b213b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lookuptxt_countryOfIssuance_F00I1MT' and @name = 'fomCO.cifExtendedVO.COUNTRY_OF_ISSUANCE']</value>
      <webElementGuid>87df259a-a8f6-4d07-9253-426a947ef344</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
