<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile No (1)_addressCO.MOBILE</name>
   <tag></tag>
   <elementGuidId>76ef8185-4c20-405a-8db2-ce773942fcca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressCO_MOBILE_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_MOBILE_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2b9a109-73ae-4a70-b2f9-9f186ab35f93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fe2c215d-c020-44e4-8fec-47d6883653bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c119733c-b55b-4aa1-9f3f-171bb8da6398</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.MOBILE</value>
      <webElementGuid>406a0186-40c4-4608-86a4-942951938844</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>5504e358-6d10-48eb-a7b9-718c38fffc00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>7558364c-6e38-4f5a-9d52-57544b05d468</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_MOBILE_F00I1MT</value>
      <webElementGuid>38d2ce48-e60d-4413-bc5e-c15bf7248ef3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>8d5dd2c6-602a-4698-ae15-03b8e42e39c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>###</value>
      <webElementGuid>7476d2ef-72c1-4823-b178-7f0bfd133108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>noformat</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>040f0848-1e83-4c8c-a119-681cfa191c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zeronotallowed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8767577a-afad-453c-b95f-b93f528d1045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalsepa</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>e8c542bd-9962-4181-a8e6-43463c2585fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>groupsepa</name>
      <type>Main</type>
      <value>,</value>
      <webElementGuid>5c40c5cc-f2ab-4f24-8b79-732c0c117700</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_MOBILE_F00I1MT:fomCO.addressField</value>
      <webElementGuid>c9a9fae7-c8b2-4ed0-9a27-2c357f6f654a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>eed16c3e-b300-49ca-bbe8-73cf1e941344</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_MOBILE_F00I1MT</value>
      <webElementGuid>3112c1e2-7594-47cb-b431-55411d9b4194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Mobile No (1)</value>
      <webElementGuid>2444a712-5a39-4f15-b801-285cbfd70755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Mobile No (1)</value>
      <webElementGuid>9e936886-d3da-485a-af99-3e250d79e137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>9398742f-cb82-4ab7-9f3b-b27d52c1b239</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mobile No (1)</value>
      <webElementGuid>695e8966-0d86-44ae-82fd-0c065864613b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_MOBILE_F00I1MT&quot;)</value>
      <webElementGuid>481750ff-638d-4ac6-9e91-47cf6dac3b47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_MOBILE_F00I1MT']</value>
      <webElementGuid>c8f1ffc3-a6e1-43f6-bc6d-9b473c2fc251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addrTbl_F00I1MT']/tbody/tr[3]/td[2]/table/tbody/tr[4]/td[2]/div/input</value>
      <webElementGuid>20bdb485-b154-4909-be0e-3520419ab00c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[4]/td[2]/div/input</value>
      <webElementGuid>16715b4c-f7a7-4513-80ac-3a3ab28123de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.MOBILE' and @id = 'addressCO_MOBILE_F00I1MT' and @title = 'Mobile No (1)']</value>
      <webElementGuid>4a70af91-0a03-4db2-a834-fe933261a911</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
