<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full Name_fomCO.cifExtendedVO.FULL_NAME_ENG</name>
   <tag></tag>
   <elementGuidId>f72f179f-3502-488d-8dbd-250e10527be0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cifExtendedVO_FULL_NAME_ENG_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifExtendedVO_FULL_NAME_ENG_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c515ead8-d6c1-474c-8897-ffaec8fd4064</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>12b70f4b-4e3e-4401-bdba-0722ac249ea7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1d8103af-864d-44aa-824c-e768689bbb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifExtendedVO.FULL_NAME_ENG</value>
      <webElementGuid>caf30dd9-9119-493b-bb44-73947e5a7009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>4504f5b4-3f33-4aee-8c0a-325a094083b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>a81d4d00-f19f-4d49-aa50-4ebb86d059f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifExtendedVO_FULL_NAME_ENG_F00I1MT</value>
      <webElementGuid>a80e2bfd-7337-450c-8c1f-e1df2bc47c84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cifVO_SHORT_NAME_ENG_F00I1MT:fomCO.cifVO.SHORT_NAME_ENG,cifVO_LONG_NAME_ENG_F00I1MT:fomCO.cifVO.LONG_NAME_ENG,cifExtendedVO_FULL_NAME_ENG_F00I1MT:fomCO.cifExtendedVO.FULL_NAME_ENG,cifVO_AUTH_NAME_F00I1MT:fomCO.cifVO.AUTH_NAME</value>
      <webElementGuid>93314d9a-d16c-4adf-b6b4-b42981c55687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_dependencyByFullNameEng</value>
      <webElementGuid>02a5f577-c26e-49e2-9b1d-bef49935cb0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.cifExtendedVO.FULL_NAME_ENG:cifExtendedVO_FULL_NAME_ENG_F00I1MT,_pageRef:_pageRef,fomCO.cifVO.SHORT_NAME_ENG:cifVO_SHORT_NAME_ENG_F00I1MT,fomCO.cifVO.LONG_NAME_ENG:cifVO_LONG_NAME_ENG_F00I1MT</value>
      <webElementGuid>a00e003e-09f1-467a-aef4-0110fb2ed41d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifExtendedVO_FULL_NAME_ENG_F00I1MT&quot;)</value>
      <webElementGuid>55717f75-f584-4d73-8e32-b014867ed68d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifExtendedVO_FULL_NAME_ENG_F00I1MT']</value>
      <webElementGuid>3a35010a-c62d-4bb0-b301-21eec3095e4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel2']/div[3]/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>991d7c6b-e873-47ca-bba7-7109bbdeb213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>b9e38468-49ea-4f2f-bec4-76f2a69bded3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifExtendedVO.FULL_NAME_ENG' and @id = 'cifExtendedVO_FULL_NAME_ENG_F00I1MT']</value>
      <webElementGuid>44b88f22-a764-4f2a-8b56-22a2453d4081</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
