<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifVO.ID_EXPIRY_DATE</name>
   <tag></tag>
   <elementGuidId>7e379e2b-6b8f-4e90-9da4-c19c6b633f77</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cifVO_ID_EXPIRY_DATE_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifVO_ID_EXPIRY_DATE_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>53463af1-d709-45ae-b405-5f02146b7971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c033c21b-28c5-41bf-8179-78c23be1f157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1a7b59aa-ff91-4a7a-b66e-eaa662fddae4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.ID_EXPIRY_DATE</value>
      <webElementGuid>d0baed2c-286f-4b58-9584-eec6b323dfaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12px</value>
      <webElementGuid>4b82ce5c-a8f6-45b8-bd8f-b6d314d5f825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input ui-state-focus ui-corner-all path-text-size hasDatepicker</value>
      <webElementGuid>b55a0fd3-0df1-491a-a53a-e9a8ae6d420e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_ID_EXPIRY_DATE_F00I1MT</value>
      <webElementGuid>2ebceda0-63ac-4ad4-a5ba-69d51a1a11f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cifVO_ID_EXPIRY_DATE_F00I1MT:fomCO.cifVO.ID_EXPIRY_DATE</value>
      <webElementGuid>8c8d0c18-fc67-4448-aabe-1e3d032655eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateIDExpiryDate</value>
      <webElementGuid>d273b064-e57d-4b2b-86d7-707af011e8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.cifVO.ID_EXPIRY_DATE:cifVO_ID_EXPIRY_DATE_F00I1MT,fomCO.cifVO.CIF_NO:cifVO_CIF_NO_F00I1MT,fomCO.cifVO.ID_DELIVERY_DATE:cifVO_ID_DELIVERY_DATE_F00I1MT,fomCO.cifVO.BIRTH_DATE:cifVO_BIRTH_DATE_F00I1MT,fomCO.cifVO.ID_TYPE:lookuptxt_cifVO_ID_TYPE_F00I1MT</value>
      <webElementGuid>5b130233-1690-474b-8e5c-c3d02e4deebe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>ID Expiry Date</value>
      <webElementGuid>629ec5bf-2612-4628-8135-ccf398219db3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>ID_Expiry_Date_key</value>
      <webElementGuid>3619674e-d6c5-424b-ae34-c56916d436c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ID Expiry Date</value>
      <webElementGuid>19085f03-1b40-4e49-be79-43ed773d3ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>5745574c-3aba-4d8b-a16f-6bd5386bb17d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_ID_EXPIRY_DATE_F00I1MT&quot;)</value>
      <webElementGuid>4eedc9ad-e0ed-40b9-afb1-40aa02517fca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifVO_ID_EXPIRY_DATE_F00I1MT']</value>
      <webElementGuid>80aec3da-6f91-4be4-aba2-12432b9dfd0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel1']/div[3]/table/tbody/tr[6]/td[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>dba98baa-0d07-474b-be85-229bddfff35d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>0db3e309-3476-49be-809f-43e052886ac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifVO.ID_EXPIRY_DATE' and @id = 'cifVO_ID_EXPIRY_DATE_F00I1MT' and @title = 'ID Expiry Date']</value>
      <webElementGuid>03d6fb5c-6807-48dd-90e6-271474705282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
