<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_City_addressCO.CITY_ENG</name>
   <tag></tag>
   <elementGuidId>27181614-bd0c-4359-9be5-95d3faf384e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#addressCO_CITY_ENG_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_CITY_ENG_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3a7c1d98-56f4-450d-a206-cf455a7a6dc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8d1b1cb0-5183-4d86-85e6-74a87a57a20f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>2e4e77ca-b096-482c-af5c-266f187f2cdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.CITY_ENG</value>
      <webElementGuid>653203cd-0542-4654-8bf1-f3b1e6da2e46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>37c618d4-f234-47a6-bc26-801328f56b06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>c880f10c-06d0-4889-8eaa-86c0886885df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_CITY_ENG_F00I1MT</value>
      <webElementGuid>b907e8ff-d8f5-42ba-a130-f1957370ff21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_CITY_ENG_F00I1MT:fomCO.addressField</value>
      <webElementGuid>5e3cfadb-c6b5-4ca9-a872-95e04a9559b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>0635a727-5dcb-45b2-adfa-6e29e2e11b1c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_CITY_ENG_F00I1MT</value>
      <webElementGuid>2f20a51e-2111-4dce-972c-3eaf260b330b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>4200087b-ab8b-4a49-9d0a-4480e3649baa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>88803ff8-6ada-482b-983f-e0dfeb579807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>City</value>
      <webElementGuid>b267b633-fdec-4ef5-8ab5-fba388a08750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_CITY_ENG_F00I1MT&quot;)</value>
      <webElementGuid>f897481b-5848-4527-9cb1-762e259b0f51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_CITY_ENG_F00I1MT']</value>
      <webElementGuid>ba975092-faed-4cbd-b566-40660a087abf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addressSectionTbl_Id_ENG_F00I1MT']/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>230bb5dd-ea7e-41b4-b5bf-4d216c2f278c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[10]/td[2]/input</value>
      <webElementGuid>7b043e4f-fbc6-42ea-8b12-ebc4b79b2335</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.CITY_ENG' and @id = 'addressCO_CITY_ENG_F00I1MT' and @title = 'City']</value>
      <webElementGuid>91bfe52d-cd78-40d7-8120-1fe53eb9e509</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
