<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Long Name_fomCO.cifVO.LONG_NAME_ENG</name>
   <tag></tag>
   <elementGuidId>9a8b3fc0-fbfb-48d5-a7ef-c0ff00b70990</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cifVO_LONG_NAME_ENG_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifVO_LONG_NAME_ENG_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db3ffc78-922a-4cad-9ed6-c60cf1cb397e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>edb37629-96dd-485b-a369-185b710fff5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>41a39158-e998-46a5-852e-97bfe63d607a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.LONG_NAME_ENG</value>
      <webElementGuid>9c80b8a6-4cf9-43aa-9538-301959a94138</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>41661882-c7b6-423a-b7de-f14486deb648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>0c828fd2-170d-4b01-ab94-7100e86704e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_LONG_NAME_ENG_F00I1MT</value>
      <webElementGuid>3330a467-1ce8-452c-9770-d96aabc8704a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fomNameAddressTabLongName_onChange()</value>
      <webElementGuid>690570cb-f547-4ebf-a7dc-a9508ce4ed2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Long Name</value>
      <webElementGuid>4fb79702-1cb2-4ea2-87ec-bc4ad21d1abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Long_Name_eng_key</value>
      <webElementGuid>d732d425-177d-4835-aac3-9c06bcaa2459</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Long Name</value>
      <webElementGuid>1ef7ccc1-caf4-4144-9419-796892721846</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_LONG_NAME_ENG_F00I1MT&quot;)</value>
      <webElementGuid>5d4bc552-684f-443f-8147-9e2f89004cdf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifVO_LONG_NAME_ENG_F00I1MT']</value>
      <webElementGuid>f407911b-ef91-47be-bf00-723312054433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel2']/div[3]/table/tbody/tr[4]/td[2]/input</value>
      <webElementGuid>d5abc923-2916-457c-88bc-2d03098cd429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[4]/td[2]/input</value>
      <webElementGuid>21f7115e-717c-44b2-a51e-d6c96e75b464</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifVO.LONG_NAME_ENG' and @id = 'cifVO_LONG_NAME_ENG_F00I1MT' and @title = 'Long Name']</value>
      <webElementGuid>8aaf6e45-7778-4fee-9d75-9fcc802e9f8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
