<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Save</name>
   <tag></tag>
   <elementGuidId>bd4d58a8-768b-4d0b-8769-800fe0036d14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fomMaintForm_F00I1MT_Save_key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='fomMaintForm_F00I1MT_Save_key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>72ffbd73-960d-477b-aea2-dc4ee1b24b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fomMaintForm_F00I1MT_Save_key</value>
      <webElementGuid>2a9ef53a-1013-4b09-be2b-5ba343302e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>fom_Save_btn_F00I1MT</value>
      <webElementGuid>e32b16a2-0ee9-46f3-adc0-cecdcafda4f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>Save_key</value>
      <webElementGuid>7295da64-4b3c-4247-b4fb-0afeb9d3c3b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>beea5508-3078-4d9b-94bb-11adbd126a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save </value>
      <webElementGuid>2c817fc3-e8b0-4809-aa0d-5590a9199932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomMaintForm_F00I1MT_Save_key&quot;)</value>
      <webElementGuid>a6dd5188-3044-4091-91af-bba430e6b0ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='fomMaintForm_F00I1MT_Save_key']</value>
      <webElementGuid>be0933d6-94b5-4cab-8ea6-963d5bcf6b9c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fom_Save_btn_F00I1MT']/span[2]/label</value>
      <webElementGuid>5cf5b3d2-d0de-4550-b2d7-cdcfe38b676d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Fields'])[2]/following::label[1]</value>
      <webElementGuid>c08b52d1-306b-4bc5-bad6-586edd688796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Agreement Date'])[1]/following::label[5]</value>
      <webElementGuid>f78c65e0-b9e4-47cc-8bec-1093072b83e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright'])[1]/preceding::label[1]</value>
      <webElementGuid>fa6e98a1-c22d-43d7-8e13-396326071a4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>38d645e4-b98d-4b30-8a3e-39f3083ebc3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span[2]/label</value>
      <webElementGuid>6c042bb8-55f0-4ea4-af43-487710b5a7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'fomMaintForm_F00I1MT_Save_key' and (text() = 'Save ' or . = 'Save ')]</value>
      <webElementGuid>2e2bb413-5711-45a4-a4a3-49d767e2f240</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
