<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Validate</name>
   <tag></tag>
   <elementGuidId>77411e67-65b6-4461-9bf3-9cca82341576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fomMaintForm_F00I1MT_Validate_key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='fomMaintForm_F00I1MT_Validate_key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>92d02538-f643-4b34-9d4d-9d2b8c68362e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fomMaintForm_F00I1MT_Validate_key</value>
      <webElementGuid>efdc7ded-f3a9-4c3e-9669-b78ad33408cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>fom_Validate_btn_F00I1MT</value>
      <webElementGuid>08b80a24-fadb-4172-9dbf-82dd5a685bf5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>Validate_key</value>
      <webElementGuid>39c924fa-5e7f-4169-be09-599fe2518488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>1624a6c4-f7ce-4d20-a502-b6cb4ce88972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validate </value>
      <webElementGuid>cf474305-4d2f-471e-bd1a-4d1192b53851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomMaintForm_F00I1MT_Validate_key&quot;)</value>
      <webElementGuid>7e482514-6a21-4168-8277-8736eb57be02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='fomMaintForm_F00I1MT_Validate_key']</value>
      <webElementGuid>50419b46-0db8-44ec-b368-7571c3eb25ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fom_Validate_btn_F00I1MT']/span[2]/label</value>
      <webElementGuid>9dce4291-5058-428a-b918-ee6b2d2ed7a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::label[1]</value>
      <webElementGuid>e25bc6a7-f7d5-4d86-a1a1-33bdd9a38875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Fields'])[3]/following::label[2]</value>
      <webElementGuid>f3ad5c84-4bde-4016-9eda-b60e6ca68be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='check_out_key'])[1]/preceding::label[1]</value>
      <webElementGuid>b1cb8e7e-b4f2-43a8-a943-1e0cb0d96458</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Validate']/parent::*</value>
      <webElementGuid>8b077b83-6d72-479a-bc82-fcf95e6947a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span[2]/label</value>
      <webElementGuid>f6703d62-6d49-4dd5-baf7-164cd485e521</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'fomMaintForm_F00I1MT_Validate_key' and (text() = 'Validate ' or . = 'Validate ')]</value>
      <webElementGuid>43b367c3-47c4-493e-8860-e97d4301d809</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
