<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SingleDivorcedWidowedMarriedUnknown</name>
   <tag></tag>
   <elementGuidId>4893815f-084c-40f6-b942-b1e527542c2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cifVO_MARITAL_STATUS_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cifVO_MARITAL_STATUS_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>8cfda46b-57cf-49b2-876f-48a46528fe83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.MARITAL_STATUS</value>
      <webElementGuid>6632ae93-11f5-4685-a2a6-b4074b2219b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>3c70416b-8d79-437e-b781-2bf650c13a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_MARITAL_STATUS_F00I1MT</value>
      <webElementGuid>d19cfe2a-e30b-44bc-93c2-92c7797abe2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listkey</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>f8a76f63-5603-4193-b965-3296a73288f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listvalue</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>24294251-8cb5-4f93-8172-10e922d47217</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>initialvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>f7686ea3-bafe-49de-acfe-ce78a8715b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prevvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>d478543a-f68a-4c3a-9c70-4a917b356da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Marital Status</value>
      <webElementGuid>3228f9eb-5099-4fb0-b725-bf490f6405d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Marital_Status_key</value>
      <webElementGuid>59e0cd6a-07a3-4869-ab58-ecec1edb23a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9cd28349-3d20-43f5-82f5-edeb80d185aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marital Status</value>
      <webElementGuid>5f9dbc04-5c90-4b44-a8bd-8a946809c19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SingleDivorcedWidowedMarriedUnknown</value>
      <webElementGuid>11e6ac4d-0aac-429d-abac-8269bf90d5e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_MARITAL_STATUS_F00I1MT&quot;)</value>
      <webElementGuid>c7671326-1354-4888-ab1a-3829e96d99bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cifVO_MARITAL_STATUS_F00I1MT']</value>
      <webElementGuid>4ea38240-5c8a-42f3-93f7-f4d74b9a2ca6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel1']/div[3]/table/tbody/tr[9]/td[3]/select</value>
      <webElementGuid>14fc0854-6a8a-4edb-b7ca-b188644243c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>6a358d59-60c7-4d96-9c20-0ea41dc051ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>5c8fc017-1f85-4e82-977b-b3c8816d91af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/select</value>
      <webElementGuid>0f21b935-45c0-46dd-bb9f-136da5d73646</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fomCO.cifVO.MARITAL_STATUS' and @id = 'cifVO_MARITAL_STATUS_F00I1MT' and @title = 'Marital Status' and (text() = 'SingleDivorcedWidowedMarriedUnknown' or . = 'SingleDivorcedWidowedMarriedUnknown')]</value>
      <webElementGuid>2091399f-b281-4609-8c59-3795518ea4c7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
