<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo_1</name>
   <tag></tag>
   <elementGuidId>6631a1b6-d8ce-46cd-889b-a029125f6226</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#pep_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pep_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>05518536-5c81-49c1-ba86-1c2a7b5de82a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pep</value>
      <webElementGuid>7f1a0e94-c076-4ba5-b48a-b840d5e4f43a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>b60b892a-18a2-4cd5-adb3-d878a4175b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pep_F00I1MT</value>
      <webElementGuid>1a7d031c-8ca0-4bee-b189-2360b98585e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listkey</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>b1c8a246-10a7-463a-bf24-3bcf49828928</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listvalue</name>
      <type>Main</type>
      <value>descValue</value>
      <webElementGuid>8dc10731-8d30-4579-8a5a-05a8accdd471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c11d3203-ad77-4127-ab7b-38e13efb5488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>callDependency(&quot;pep_F00I1MT:criteria.elemHm.pep&quot;,&quot;/imal_core_portal/path/dynamicScreen/dynDependencyAction_dynDependenciesProcess?&quot;,&quot;screenId:~CONST_2,elementId:~CONST_pep,criteria.elemHm.pep:pep_F00I1MT,criteria.elemHm.politically_exposed:politically_exposed_F00I1MT,criteria.elemHm.salutation:salutation_F00I1MT,criteria.elemHm.related_politically:related_politically_F00I1MT,criteria.elemHm.relativity:relativity_F00I1MT&quot;,&quot;pep_F00I1MT&quot;,&quot;&quot;)</value>
      <webElementGuid>b020ed69-d5ce-4f4b-90b9-059df68cb51d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>pep_F00I1MT:criteria.elemHm.pep</value>
      <webElementGuid>8aabab78-bf38-466d-815f-e26ca2a714b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/dynamicScreen/dynDependencyAction_dynDependenciesProcess?</value>
      <webElementGuid>8d8bb19a-d6d0-49ba-90e4-171e07e1cfc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>screenId:~CONST_2,elementId:~CONST_pep,criteria.elemHm.pep:pep_F00I1MT,criteria.elemHm.politically_exposed:politically_exposed_F00I1MT,criteria.elemHm.salutation:salutation_F00I1MT,criteria.elemHm.related_politically:related_politically_F00I1MT,criteria.elemHm.relativity:relativity_F00I1MT</value>
      <webElementGuid>950ce7ad-ada2-4b43-8dc5-79d878107d20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>fe2b1481-7fef-47b2-9609-e3a4505d7ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pep_F00I1MT&quot;)</value>
      <webElementGuid>239e8913-8db8-4c34-80f8-c34090444706</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pep_F00I1MT']</value>
      <webElementGuid>86cda027-6f08-40ce-9edc-de1238c93362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dynScreen_2_FormId_F00I1MT_DivId']/select[3]</value>
      <webElementGuid>b1fa99d5-c7ae-4085-9935-dd9cd88dee36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::select[1]</value>
      <webElementGuid>74a3f07d-9978-4257-9f63-6c5f94a384be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::select[1]</value>
      <webElementGuid>125723e9-c3e9-4caa-ab1a-856527dbda91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>33b51610-8fe0-4e69-8c86-8c277081ca01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'pep' and @id = 'pep_F00I1MT' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>2e733a79-39d0-422a-bd3e-faad11eb22df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
