<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo</name>
   <tag></tag>
   <elementGuidId>09bbba60-4e7f-4181-94b2-060f48673b3c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#us_acc_holder_F00I1MT</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='us_acc_holder_F00I1MT']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>deafef65-c9dc-4109-ab3d-236238129f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>scrElemHm.us_acc_holder</value>
      <webElementGuid>3dfcc324-d688-4a74-943f-18c400d33812</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>d8d0ab37-3ca4-41a0-9f60-e1735f1b7124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>us_acc_holder_F00I1MT</value>
      <webElementGuid>58729ca7-09dd-47af-a68b-4abd1f1afead</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listkey</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>376ca4a7-e3bc-4d01-8d6a-94e29cbf8476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listvalue</name>
      <type>Main</type>
      <value>descValue</value>
      <webElementGuid>e00b7015-6e8e-4dd3-ba51-2fa1ff55cd79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5b47b2f2-d7cc-4e3e-8b7e-067f4b2a0dc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>callDependency(&quot;us_acc_holder_F00I1MT:criteria.elemHm.us_acc_holder&quot;,&quot;/imal_core_portal/path/dynamicScreen/dynDependencyAction_dynDependenciesProcess?&quot;,&quot;screenId:~CONST_1,elementId:~CONST_us_acc_holder,criteria.elemHm.us_acc_holder:us_acc_holder_F00I1MT,criteria.elemHm.client_type:client_type_F00I1MT&quot;,&quot;us_acc_holder_F00I1MT&quot;,&quot;&quot;)</value>
      <webElementGuid>1a827881-4170-4f6b-af85-00f6631867e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>us_acc_holder_F00I1MT:criteria.elemHm.us_acc_holder</value>
      <webElementGuid>584657f0-e4d1-4073-8fe1-931e10513365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/dynamicScreen/dynDependencyAction_dynDependenciesProcess?</value>
      <webElementGuid>19dd634e-10ca-4a65-bada-976604f57940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>screenId:~CONST_1,elementId:~CONST_us_acc_holder,criteria.elemHm.us_acc_holder:us_acc_holder_F00I1MT,criteria.elemHm.client_type:client_type_F00I1MT</value>
      <webElementGuid>329b7455-ae83-44da-8cdd-3414e110cf48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>216ecbf8-70db-4aa8-a57e-9183c3be2599</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;us_acc_holder_F00I1MT&quot;)</value>
      <webElementGuid>c15da68b-949b-4a9f-837b-a901c30cbe40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='us_acc_holder_F00I1MT']</value>
      <webElementGuid>17ff5304-8e41-4052-9406-dab5ec867d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dynScreen_1_FormId_F00I1MT_DivId']/select[4]</value>
      <webElementGuid>71708495-a702-408d-8d90-ab8e18d2c7b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::select[1]</value>
      <webElementGuid>4693ae2b-3c08-4204-9116-b3ae17ca9f58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::select[1]</value>
      <webElementGuid>80c5dcc1-1220-472f-89ec-c0ff01b23506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning'])[11]/preceding::select[2]</value>
      <webElementGuid>785c9477-c074-49d2-a85b-ec5417b6d244</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please, select row'])[11]/preceding::select[2]</value>
      <webElementGuid>7faeda56-e736-4694-95cb-f4c03d1688fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[4]</value>
      <webElementGuid>82ac6fe2-a9f0-4b63-b97b-95f82b569435</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'scrElemHm.us_acc_holder' and @id = 'us_acc_holder_F00I1MT' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>e7e74c37-ed52-4d67-bd18-aa8eb000e798</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
