<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_OK</name>
   <tag></tag>
   <elementGuidId>bed53a47-4c99-4343-aaaf-0d82f79c9a76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ok_F00I1MT > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ok_F00I1MT']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d3a4699d-5042-4426-b802-e08d13da6c56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>06da0749-39c2-4da0-9e4d-390c10c2336d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK 
</value>
      <webElementGuid>cbc03583-159a-4fb6-b62d-3785c97f1fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ok_F00I1MT&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>c8645b96-2a2d-40e0-ac9b-8c5bccc98600</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ok_F00I1MT']/span</value>
      <webElementGuid>a2a07097-a545-4b60-a9d0-2738d77e6cdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::span[1]</value>
      <webElementGuid>c10b6207-9065-431b-b94a-369017adaeb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='fatca_compliant'])[1]/following::span[2]</value>
      <webElementGuid>a026466b-d1e7-43c1-b854-9d64757f80a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning'])[11]/preceding::span[1]</value>
      <webElementGuid>048680bd-7d87-4c51-9c25-45461ef37fb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/form/div/div[3]/button/span</value>
      <webElementGuid>f6b144ad-45bd-48e9-aa3f-cf7b72714be2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'OK 
' or . = 'OK 
')]</value>
      <webElementGuid>bd86a2c2-5d57-4937-9c77-758af28430b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
