<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Dismiss</name>
   <tag></tag>
   <elementGuidId>99a5969f-52b1-4f54-b750-ff6296fa8c85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#dismissbut_F00I1MT > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='dismissbut_F00I1MT']/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>58b51e2f-e444-4233-8d0b-a24f968c70de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>e28cf744-7bba-473b-9b06-b07f9baf108c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Dismiss </value>
      <webElementGuid>ed0c3aef-16f7-47e9-b4fe-bcc2948f043c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;dismissbut_F00I1MT&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>90b20784-2f26-4245-a12e-f3857e3b8aa6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='dismissbut_F00I1MT']/span</value>
      <webElementGuid>92ce27ef-ec89-45e1-854e-f2c8344b552a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/following::span[1]</value>
      <webElementGuid>b2d906b4-911c-4a5b-b865-201250377361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No records to view'])[3]/following::span[2]</value>
      <webElementGuid>31d8c0de-1db4-497e-953a-6dd43976d33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Warning'])[12]/preceding::span[1]</value>
      <webElementGuid>6358f002-30d4-4ff0-a24b-08112853d250</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please, select row'])[12]/preceding::span[3]</value>
      <webElementGuid>663e1201-a440-49e5-9517-c0e708b87c4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Dismiss']/parent::*</value>
      <webElementGuid>5a6c3db1-0b5c-497d-8845-3377af3da303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/a[2]/span</value>
      <webElementGuid>7e12d213-abc4-4974-923e-3588c2dc9f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Dismiss ' or . = ' Dismiss ')]</value>
      <webElementGuid>c08aeaea-8d9f-49bd-8fce-94997737ffd9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
