<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>d5e9cd5c-856d-4d71-84ba-98ef93663012</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#fom_Save_btn_F00I1MT > span.ui-button-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fom_Save_btn_F00I1MT']/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f9477f32-6575-4d11-9db0-6daefafa2697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>e5d252a8-61c2-4b8e-9d2e-84f8e2f11958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save  
</value>
      <webElementGuid>63ffd2ec-a974-4053-80c8-ffe1add77ad5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fom_Save_btn_F00I1MT&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>cef71474-f4b4-4d22-a995-95060c10c77f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fom_Save_btn_F00I1MT']/span[2]</value>
      <webElementGuid>e13f81cf-9776-4a52-90f6-80a6c6b72ca3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Fields'])[2]/following::span[2]</value>
      <webElementGuid>21992716-5af7-4346-b70c-dcd430aef500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Master Agreement Date'])[1]/following::span[4]</value>
      <webElementGuid>9947bcad-3172-4c6b-aa5d-9192337b477a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span[2]</value>
      <webElementGuid>2e326393-4e4c-45bb-843f-07098b9cb9be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Save  
' or . = ' Save  
')]</value>
      <webElementGuid>bc44a5db-6d3d-43e6-a2cd-2afa0dfce0e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
