<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td</name>
   <tag></tag>
   <elementGuidId>315abb0c-129c-4c0a-8a10-61572aab4d4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='MarketedByTabInfo_pannel2']/div[3]/table/tbody/tr[8]/td[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6c7649f7-1b83-4dbd-bc88-48aa078d4b44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>colspan</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>e804432a-8bfc-4e48-b9a8-b83bc7b3948d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MarketedByTabInfo_pannel2&quot;)/div[@class=&quot;collapsibleContainerContent ui-widget-content&quot;]/table[@class=&quot;headerPortionContent ui-widget-content&quot;]/tbody[1]/tr[8]/td[4]</value>
      <webElementGuid>3bcb95a3-1742-438d-b3d8-eb4655fb81e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel2']/div[3]/table/tbody/tr[8]/td[4]</value>
      <webElementGuid>b452cd01-2602-446f-b61a-271ecd76a746</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/table/tbody/tr[8]/td[4]</value>
      <webElementGuid>51d566a2-4167-4fd9-bbc6-ab3b8d82b570</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
