<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>4cfc910e-3fb9-4cbc-b7eb-a6c51a856576</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_TYPE_CODE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_TYPE_CODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>22e550f4-e167-4c6f-835a-3bcac0437b2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>c608f172-7206-4682-a1fb-5ccb48f46e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>6c25cf61-c90c-427e-b802-fead8e4400ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9cd24f43-ce55-42ba-afbb-c778ec331a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>b8e6d7a8-fd06-4955-bd6d-c5dc3369b397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_cifVO_CIF_TYPE_F00I1MT_TYPE_CODE</value>
      <webElementGuid>d6bb3a1f-c265-4534-b185-cc238d766d2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_TYPE_CODE</value>
      <webElementGuid>1f5dc5ac-eb0b-4333-b844-1bbb8e23892e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>08c79c36-dbc9-4072-bbd9-6e9e11661e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_TYPE_CODE&quot;)</value>
      <webElementGuid>8721c5bc-02ef-4bd7-b803-8ceba9fd52a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_TYPE_CODE']</value>
      <webElementGuid>d341cae3-ae0b-4a3a-9660-ffe6dbfc6804</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td</value>
      <webElementGuid>9253c498-1098-4989-8ec1-9ccc9bf1550d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Reference'])[3]/following::td[7]</value>
      <webElementGuid>01e986db-4832-4007-a9ea-930d66b79d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف الكامل'])[1]/following::td[7]</value>
      <webElementGuid>030ed8d6-6cb3-4b4b-8a9e-37ba965ba6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value'])[1]/preceding::td[1]</value>
      <webElementGuid>bac80fa1-f054-405b-972d-3634b4c12470</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value'])[2]/preceding::td[2]</value>
      <webElementGuid>9f42f27f-7b8b-436c-83e3-d53f360d6706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/table/tbody/tr[2]/td</value>
      <webElementGuid>abb48fba-677f-4a37-9d53-02e943e0c99d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '1' and @id = 'td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_TYPE_CODE' and (text() = '1' or . = '1')]</value>
      <webElementGuid>c74fde2b-5c84-4f4d-9840-655b28f2aef9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
