<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_398</name>
   <tag></tag>
   <elementGuidId>948ff5a7-2b78-477c-88a1-da3406f2a71a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_countryOfIssuance_F00I1MT_1_COUNTRY_CODE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_countryOfIssuance_F00I1MT_1_COUNTRY_CODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>38d39cc2-b035-4067-9ee6-b9155a6e4205</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>7fc6e054-f137-4445-9633-4663cd867cf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>6857be69-7162-4e93-89ac-ce53b211cf3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>398</value>
      <webElementGuid>32c1c363-9406-48a5-a45d-f93eb0425ea1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>085efc2c-d3c2-4556-ae7b-a967a20ab222</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_countryOfIssuance_F00I1MT_COUNTRY_CODE</value>
      <webElementGuid>948cc155-01ab-4e4d-91db-bde4bc914c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_countryOfIssuance_F00I1MT_1_COUNTRY_CODE</value>
      <webElementGuid>edae642d-a95c-45f7-8971-7e3548bc02f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>398</value>
      <webElementGuid>95dd221d-cea7-44a1-9ac5-5a14b8aea258</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_countryOfIssuance_F00I1MT_1_COUNTRY_CODE&quot;)</value>
      <webElementGuid>738bb989-d24d-49a9-98ab-f7b9cda6130c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_countryOfIssuance_F00I1MT_1_COUNTRY_CODE']</value>
      <webElementGuid>965ddb70-83e5-484f-942d-a100ed7f32d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td)[11]</value>
      <webElementGuid>679afae7-018f-4710-b365-457b8c2761d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISO Code'])[1]/following::td[8]</value>
      <webElementGuid>5e75f71c-3ea0-4109-a097-495edb1b4556</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telephone Format'])[1]/following::td[8]</value>
      <webElementGuid>8892391f-6062-4b68-b199-61b5047868c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KAZ'])[1]/preceding::td[1]</value>
      <webElementGuid>34df0df1-b68c-4965-be8a-bdca3942126c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='كازاخستان'])[1]/preceding::td[2]</value>
      <webElementGuid>1ba1ebe6-1ea7-4e2c-a654-af49d1380b10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='398']/parent::*</value>
      <webElementGuid>3a6c3c93-8453-43b1-98e1-730f3be39399</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[3]/div[3]/div/table/tbody/tr[2]/td</value>
      <webElementGuid>e1bd877f-371a-4d24-bca8-01fdce0ed190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '398' and @id = 'td_gridtab_countryOfIssuance_F00I1MT_1_COUNTRY_CODE' and (text() = '398' or . = '398')]</value>
      <webElementGuid>59c52f6c-116b-49ce-8716-66781578477d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
