<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Central Post Office</name>
   <tag></tag>
   <elementGuidId>29d72094-2f57-409a-9420-5ab110b9db40</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>f68cb7b3-fa08-4562-bf98-b0e84bdd754b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>e5e8962e-e212-4721-8ae4-d7ea752f9534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Central Post Office</value>
      <webElementGuid>0627dd44-203d-4c0d-8910-9f26af2678b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>f1f59bd1-715a-48c1-bf13-dc833ff146f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_addressCO_POSTAL_CODE_F00I1MT_BRIEF_NAME_ENG</value>
      <webElementGuid>3c72c28a-1610-4f89-b955-9e2954f9522c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG</value>
      <webElementGuid>cdb84811-e251-4e69-aa26-cc3422db166b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Central Post Office</value>
      <webElementGuid>b0b07eca-1308-4611-846a-e828d930a3c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG&quot;)</value>
      <webElementGuid>0cf7f68f-82f0-42c4-a8de-eb5ee7afb2a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG']</value>
      <webElementGuid>f011ee52-22ea-4a14-ac16-9f56cbcbceab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[6]</value>
      <webElementGuid>c1a3fa37-4734-4e83-bab1-92f733c03837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[2]/following::td[9]</value>
      <webElementGuid>32cf0c56-48e3-47a8-827b-a6299f408b94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Reference'])[6]/following::td[9]</value>
      <webElementGuid>d0bdfd21-31f0-4ec2-8be6-d368fcbdd31b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Post Office'])[2]/preceding::td[1]</value>
      <webElementGuid>c853b545-59cd-4ef7-ad94-acadd799bbcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Post Office'])[3]/preceding::td[2]</value>
      <webElementGuid>ed759bd0-4c43-41ae-86ff-9e78daeed9d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Central Post Office']/parent::*</value>
      <webElementGuid>fed2593c-9822-4ef2-bd64-0ddb9af464c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>ba055d77-a3ba-46fc-8c44-bec0317985fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Central Post Office' and @id = 'td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG' and (text() = 'Central Post Office' or . = 'Central Post Office')]</value>
      <webElementGuid>a6c988c5-910a-4a9e-bcb3-941390e40b79</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
