<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Central Post Office_1</name>
   <tag></tag>
   <elementGuidId>29b1aec0-06a9-403c-a5c0-a76d29ea74d0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_LONG_NAME_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_LONG_NAME_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0872e10b-fa04-482a-9b16-2e946f034c2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>54536d1e-a736-43a1-a55e-613b242af043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Central Post Office</value>
      <webElementGuid>0074352b-00c0-4713-8d49-080ea5e1bb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Long Description</value>
      <webElementGuid>28c82a93-7084-4a75-a36c-f9327dc2704e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_addressCO_POSTAL_CODE_F00I1MT_LONG_NAME_ENG</value>
      <webElementGuid>484c0a23-3c4d-40bc-9216-753e8882748d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_LONG_NAME_ENG</value>
      <webElementGuid>376dbdec-d769-4a5e-a699-7ce4aeb74315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Central Post Office</value>
      <webElementGuid>79d33eff-eecb-42b5-bc1a-7a28bf7ea19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_LONG_NAME_ENG&quot;)</value>
      <webElementGuid>7927d81c-33b1-4781-a923-33da5c06dd0c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_LONG_NAME_ENG']</value>
      <webElementGuid>0ce4152d-6d0a-46b3-ab9b-0096bd58e20e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[3])[6]</value>
      <webElementGuid>a4435af5-46f2-434c-b955-8e2d8001bbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Post Office'])[1]/following::td[1]</value>
      <webElementGuid>e09f2a53-6488-46c8-95e2-594e4b2e89a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[2]/following::td[10]</value>
      <webElementGuid>579ba161-dc48-4a42-a1e6-39e58a237c2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Post Office'])[3]/preceding::td[1]</value>
      <webElementGuid>32178a33-43c0-4a9b-a7d1-2dd52c82959f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Post Office'])[4]/preceding::td[2]</value>
      <webElementGuid>9410db1e-fff6-4903-b7a2-3b8774a62e7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[30]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[3]</value>
      <webElementGuid>69e42973-bcba-492d-b8bf-d4d45ce18a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Central Post Office' and @id = 'td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_LONG_NAME_ENG' and (text() = 'Central Post Office' or . = 'Central Post Office')]</value>
      <webElementGuid>158a100d-8d2b-4eff-8a78-2940a0160170</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
