<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_KAZ</name>
   <tag></tag>
   <elementGuidId>7cd5ae18-46c2-4fa2-b86f-5087497eb88e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6872945f-330d-4916-8d4b-eabf019e1cc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>f4252cb5-02fb-4441-b888-06796eef1c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>KAZ</value>
      <webElementGuid>c4a31825-b729-4d2a-88bd-971e87665bb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>049cc676-b572-4f47-845a-485e5ad580c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_countryOfIssuance_F00I1MT_BRIEF_DESC_ENG</value>
      <webElementGuid>424c68f3-8221-4a64-a1e6-01de3b98f15f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>65f07f62-f902-46d9-98d2-e1e00d8e1a96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>KAZ</value>
      <webElementGuid>f2cd8f06-3a85-43a7-b5b6-e5706abb8d5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>d88c05b3-b35f-456b-8342-dc05bc41ca83</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>62e64ebc-014c-455e-a4a6-9f8cad3acb1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[3]</value>
      <webElementGuid>6563c961-859d-4732-9958-a970ad9415ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISO Code'])[1]/following::td[9]</value>
      <webElementGuid>b602d238-2831-4842-ae27-7b9c2c0ac74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telephone Format'])[1]/following::td[9]</value>
      <webElementGuid>18efe7f7-f0d3-4f9e-8701-ebb3ad825988</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='كازاخستان'])[1]/preceding::td[1]</value>
      <webElementGuid>8d88acef-40e5-4172-92ba-e5cd6eaeddaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kazakhstan'])[1]/preceding::td[2]</value>
      <webElementGuid>c243c77d-991b-4a4d-9936-6dc028b1d411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='KAZ']/parent::*</value>
      <webElementGuid>2653b7bf-2c36-41fd-9e63-5b2116b0c855</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>cd470388-199e-4442-8d92-e0eef2c02feb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'KAZ' and @id = 'td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG' and (text() = 'KAZ' or . = 'KAZ')]</value>
      <webElementGuid>9c1ff402-3d56-449f-973f-24919fcd1641</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
