<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Log Out</name>
   <tag></tag>
   <elementGuidId>274a9567-cea1-4b3d-bafe-70e3e948f020</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@onclick=&quot;document.getElementById('hder_logout_icon_id').click()&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>0f792cfd-82bc-4a72-b508-0e9ef3c90756</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nowrap</name>
      <type>Main</type>
      <value>nowrap</value>
      <webElementGuid>5cb83864-2fbc-4941-b2c5-67649812245b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>document.getElementById('hder_logout_icon_id').click()</value>
      <webElementGuid>c495ddee-70fa-4c42-a8aa-771ac872d0f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Log Out  </value>
      <webElementGuid>41e1b742-f20a-4da7-9357-6fc475734da0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui_bar_div&quot;)/table[1]/tbody[1]/tr[1]/td[@class=&quot;header-top-right&quot;]/table[1]/tbody[1]/tr[1]/td[2]/table[1]/tbody[1]/tr[1]/td[3]/table[1]/tbody[1]/tr[1]/td[8]/table[@class=&quot;whiteText&quot;]/tbody[1]/tr[1]/td[3]</value>
      <webElementGuid>94f77a4b-ac42-4831-953b-01c9372c0bb4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick=&quot;document.getElementById('hder_logout_icon_id').click()&quot;]</value>
      <webElementGuid>6e422f38-116b-472c-9ef2-c7fd656143da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ui_bar_div']/table/tbody/tr/td[2]/table/tbody/tr/td[2]/table/tbody/tr/td[3]/table/tbody/tr/td[8]/table/tbody/tr/td[3]</value>
      <webElementGuid>5da1f5dc-613b-42ef-a1f6-3f239e5549a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Home'])[1]/following::td[8]</value>
      <webElementGuid>cb76792b-8218-4cde-a252-687794c09568</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Options'])[1]/following::td[16]</value>
      <webElementGuid>fc9aa11d-e938-4477-aadd-867c1cb4c28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help'])[1]/preceding::td[7]</value>
      <webElementGuid>d80861a2-5e8c-47a3-b301-8f3fb4febd1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/table/tbody/tr/td[3]</value>
      <webElementGuid>8f5d6186-a3cb-4df3-a46c-3e2ab9460145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Log Out  ' or . = ' Log Out  ')]</value>
      <webElementGuid>23accfed-95e4-4a90-b871-ca82dd9436c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
