<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Muscat_1</name>
   <tag></tag>
   <elementGuidId>d09fb8da-918a-4bb6-84d5-007e3a9c08b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_cifExtendedVO_CITY_OF_BIRTH_F00I1MT_1_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_cifExtendedVO_CITY_OF_BIRTH_F00I1MT_1_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>6d6343cf-49ef-4e6a-90a7-7291ec402c86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>6ead1c33-f2fe-4bea-b0ae-534028c8ca91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Muscat</value>
      <webElementGuid>8ccf2cc3-17c5-418b-914d-1e4216639dec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>4c249843-7112-4f89-bc54-f5cc5b4fa555</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_cifExtendedVO_CITY_OF_BIRTH_F00I1MT_BRIEF_DESC_ENG</value>
      <webElementGuid>913f78c9-b035-48cf-bc65-1daab62ebda4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_cifExtendedVO_CITY_OF_BIRTH_F00I1MT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>76d7e0fc-31d8-4ecc-809b-bdd3bc434408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Muscat</value>
      <webElementGuid>fe47d558-a512-4aa0-883f-3764e3e9ecb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_cifExtendedVO_CITY_OF_BIRTH_F00I1MT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>73687110-221c-4c69-91ea-3ab5c31731c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_cifExtendedVO_CITY_OF_BIRTH_F00I1MT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>4e66ddbc-9ace-46fb-8c41-cc0013cc61a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[5]</value>
      <webElementGuid>9df6e245-537f-4945-b6f1-1e3bf241458e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Reference'])[5]/following::td[8]</value>
      <webElementGuid>0e5edc6c-7acd-4e8d-9c20-203c59628c04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف الكامل'])[5]/following::td[8]</value>
      <webElementGuid>36b020cf-5024-487d-9873-644271f044d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مسقط'])[3]/preceding::td[1]</value>
      <webElementGuid>07238d35-f1d6-4a9c-a022-b78413ff25b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muscat'])[4]/preceding::td[2]</value>
      <webElementGuid>3cc7b412-5d5b-4d65-840a-7fc56b9b1b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>09e10f72-7fb2-4a0f-b9bb-58bd79da8d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Muscat' and @id = 'td_gridtab_cifExtendedVO_CITY_OF_BIRTH_F00I1MT_1_BRIEF_DESC_ENG' and (text() = 'Muscat' or . = 'Muscat')]</value>
      <webElementGuid>601ef51d-3bc2-42ec-80a6-f955e206e21b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
