<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Muscat</name>
   <tag></tag>
   <elementGuidId>f24a0e42-d0ea-4994-9803-41ff20955488</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_cifExtendedVO_region_ofBirth_F00I1MT_1_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_cifExtendedVO_region_ofBirth_F00I1MT_1_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>35a61f74-ce57-4b96-8b9e-a58c8d73beb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>3b1d13bf-201a-42b3-badb-a4218444deb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Muscat</value>
      <webElementGuid>26e3163c-31f0-44cd-ad5f-64404b0d2607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>796553b6-2045-4dba-86e0-6cb002697a19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_cifExtendedVO_region_ofBirth_F00I1MT_BRIEF_DESC_ENG</value>
      <webElementGuid>86117639-5506-4be9-bad4-1e40d3fe307f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_cifExtendedVO_region_ofBirth_F00I1MT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>f593af76-3071-415d-888f-326a65944ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Muscat</value>
      <webElementGuid>2dd84378-4ad3-44a4-93e5-3251caa32a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_cifExtendedVO_region_ofBirth_F00I1MT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>fad29f2d-aecb-4ee5-92ba-a02f13e19b74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_cifExtendedVO_region_ofBirth_F00I1MT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>14e932dd-31f2-4e8f-83a3-2c3a576005f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[4]</value>
      <webElementGuid>469e5caf-a273-4ac9-9577-8caa337199e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف الكامل'])[3]/following::td[7]</value>
      <webElementGuid>dc3d40ef-caa9-4a4b-8784-22d864fc0538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Long Description'])[3]/following::td[7]</value>
      <webElementGuid>ad15f6be-2a9a-4af4-bb88-3eaec5133d02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مسقط'])[1]/preceding::td[1]</value>
      <webElementGuid>c7767cc4-862f-4f59-9f98-4f6b8f1087f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muscat'])[2]/preceding::td[2]</value>
      <webElementGuid>3a3ea6ad-1ad5-4077-8f5b-c26008572a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Muscat']/parent::*</value>
      <webElementGuid>106b7e47-12d7-410b-881c-754d02c1d047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>046c1391-0f7c-4dbb-bca5-d597d6f88924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Muscat' and @id = 'td_gridtab_cifExtendedVO_region_ofBirth_F00I1MT_1_BRIEF_DESC_ENG' and (text() = 'Muscat' or . = 'Muscat')]</value>
      <webElementGuid>42d2148e-8e40-44a5-99d7-3287ca5aa8e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
