<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Muscat_1_2</name>
   <tag></tag>
   <elementGuidId>d644e202-e824-480b-83b1-133012f2ec01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a63a1877-73c2-4cde-8ec3-4c9b9e229104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>ddfa71e5-743f-4ffc-9833-9cb1a656be0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Muscat</value>
      <webElementGuid>a19871a8-8c14-4e26-a9bb-62c7cabfd591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>46df05a9-0458-42b3-9284-f9adf0bea02a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_addressCO_POBOX_AREA_F00I1MT_BRIEF_DESC_ENG</value>
      <webElementGuid>3b0586a5-2174-493e-97db-c981155be7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>1ae5e0c0-06db-42d2-a107-76cc2b2dc6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Muscat</value>
      <webElementGuid>a82fe814-dfa7-4e1a-9ca5-895d4eae10f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>9c400369-7af5-47cf-a84d-629dec1cfeef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>57a06afb-d107-4e1f-a7fe-8d3f858d0b46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[7]</value>
      <webElementGuid>14db5683-0c7d-4d8e-87b7-356625e7f7b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف الكامل'])[7]/following::td[7]</value>
      <webElementGuid>5e7dac80-0b18-46f7-8d45-6c58c9c47f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Long Description'])[7]/following::td[7]</value>
      <webElementGuid>a4ec4c4c-2a44-4820-9f95-47abe1c4835e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مسقط'])[5]/preceding::td[1]</value>
      <webElementGuid>7e993a40-1dce-4f51-aa63-605f7c42e742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muscat'])[10]/preceding::td[2]</value>
      <webElementGuid>b1595b65-dd66-48b4-9743-a286129cc127</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[32]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>51cda44b-c14c-44ab-a521-2d486e7732aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Muscat' and @id = 'td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG' and (text() = 'Muscat' or . = 'Muscat')]</value>
      <webElementGuid>edc7eaae-df24-453f-919c-a1793d16a249</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
