<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Passport</name>
   <tag></tag>
   <elementGuidId>83ef90e8-2cfd-4459-b307-787ab78caaa3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_cifVO_ID_TYPE_F00I1MT_2_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_cifVO_ID_TYPE_F00I1MT_2_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>4a1f3d91-13f0-4559-9cd2-99b62889ada4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>698bec79-a408-4d3b-81dd-1bd22533bbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Passport</value>
      <webElementGuid>88f20fce-d554-4ab0-ae5f-5b7dd1b01c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>1be75244-b363-48bf-b429-05e93df57052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_cifVO_ID_TYPE_F00I1MT_DESC_ENG</value>
      <webElementGuid>be4f9d88-2931-456b-a753-ce6791eb1a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_cifVO_ID_TYPE_F00I1MT_2_DESC_ENG</value>
      <webElementGuid>f1933dbd-69ce-489b-a861-2b1aefb663f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Passport</value>
      <webElementGuid>21142175-c38a-4fde-aa70-0b209490404d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_cifVO_ID_TYPE_F00I1MT_2_DESC_ENG&quot;)</value>
      <webElementGuid>f59887c2-b307-4bee-a6ba-02919d3f9bfb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_cifVO_ID_TYPE_F00I1MT_2_DESC_ENG']</value>
      <webElementGuid>e3c19ae2-0e46-4fbb-9246-a839277a251a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='2']/td[2])[2]</value>
      <webElementGuid>22046b92-5e8b-47a4-b836-a0e2d2427ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='البطاقة الشخصية'])[1]/following::td[3]</value>
      <webElementGuid>26c96fad-613a-4772-a458-fddb77159173</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='National ID'])[1]/following::td[4]</value>
      <webElementGuid>1d3557e4-8409-4c86-8b37-565a52807056</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='جواز سفر'])[1]/preceding::td[1]</value>
      <webElementGuid>d1ea3347-14f1-4b44-bc9e-0f90a4155569</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Resident ID'])[1]/preceding::td[4]</value>
      <webElementGuid>cee9b2be-3dfd-4e76-bfa7-2c1f3195881b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Passport']/parent::*</value>
      <webElementGuid>09ded711-eaaf-44de-a760-23163c63ca86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[3]/div[3]/div/table/tbody/tr[3]/td[2]</value>
      <webElementGuid>75022fe3-a700-459a-956b-9db11e2b5937</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Passport' and @id = 'td_gridtab_cifVO_ID_TYPE_F00I1MT_2_DESC_ENG' and (text() = 'Passport' or . = 'Passport')]</value>
      <webElementGuid>c0aef90a-65b5-4953-ae0d-a15110ac3967</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
