<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Value</name>
   <tag></tag>
   <elementGuidId>a556cf99-ea7c-41b6-b06b-18ad0e03ece2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_BRIEF_DESC_ENG</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_BRIEF_DESC_ENG']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>33903c0b-a9e1-4b8d-b9e4-1cbb68b837dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>f45b9c75-9050-43aa-9229-001be5652534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>fd84bf98-a78d-4197-bd5f-5e84f809ea17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>2b18db8e-d608-4e8c-901e-9c977b100533</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_cifVO_CIF_TYPE_F00I1MT_BRIEF_DESC_ENG</value>
      <webElementGuid>b38f772f-0bb9-4654-873a-aba561d67965</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>8a2f53c2-7542-446c-8ecf-216134e1e174</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Value</value>
      <webElementGuid>c18e28ee-80e7-4580-9bab-6875f3e334c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>63dbccba-927b-4e86-bd87-47c588f665a8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>a594c0c2-228c-4412-8009-745b50e905a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[2]</value>
      <webElementGuid>610c6130-c468-4211-a502-fdc0039bf4e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Reference'])[3]/following::td[8]</value>
      <webElementGuid>9514cb39-dcba-41ad-bb04-63cb009f5adf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف الكامل'])[1]/following::td[8]</value>
      <webElementGuid>6d74874e-4e2e-42be-ab35-ba1864ce2166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value'])[2]/preceding::td[1]</value>
      <webElementGuid>b430a0e9-93f8-4ce7-a179-cc2b565dae37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Value'])[3]/preceding::td[2]</value>
      <webElementGuid>ae171d9a-1347-4766-bb28-39993c46d337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Value']/parent::*</value>
      <webElementGuid>f7244a39-d369-47b2-918d-7fec2e272599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>b9fa0bb3-4b43-43ff-8d09-e3418c610514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Value' and @id = 'td_gridtab_cifVO_CIF_TYPE_F00I1MT_1_BRIEF_DESC_ENG' and (text() = 'Value' or . = 'Value')]</value>
      <webElementGuid>9733c89f-60e0-43f4-99b9-0a3a95f74861</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
