<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__additionalFieldsByTypeCOList1.ADD_VC</name>
   <tag></tag>
   <elementGuidId>7f8e4fda-22c0-411b-b86a-c6e3f0ae8815</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addFieldsByType_2_D001MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addFieldsByType_2_D001MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9f860722-6283-4e7d-a29c-d6cd411e47ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e55361b4-cbde-4904-8a4d-9d7630866f64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a9f98149-984a-4e37-9179-ef07b8b4b7e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>additionalFieldsByTypeCOList[1].ADD_VC</value>
      <webElementGuid>11852cf7-0016-4236-8bbf-1e07b3d4fdd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>cf1f36bc-609e-4bcd-8301-9686037771ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>c2f965bb-a513-4d75-94f9-6b8b1133e72c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFieldsByType_2_D001MT</value>
      <webElementGuid>47580c40-bdc7-4c8e-aeaa-f60aed208b83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>10ec24be-804e-49cc-86a2-5dd35a98a6ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>56f28310-5007-41c4-aa36-41b9a1a9226d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFieldsByType_2_D001MT&quot;)</value>
      <webElementGuid>cb7f40b9-3f05-4507-958d-607e03f34855</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addFieldsByType_2_D001MT']</value>
      <webElementGuid>7ced9020-84d4-4884-975b-befec525b7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trxMgntAddFieldsTypeDiv_id_D001MT']/table/tbody/tr[2]/td[4]/input</value>
      <webElementGuid>49e68479-a0c4-4508-b22c-966e5527a3d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/input</value>
      <webElementGuid>7888e007-4a8d-4e3d-832a-5a98f1072996</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'additionalFieldsByTypeCOList[1].ADD_VC' and @id = 'addFieldsByType_2_D001MT']</value>
      <webElementGuid>ef406903-70ad-4daf-bc78-2b06e8f8cac3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
