<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__additionalFieldsByTypeCOList0.ADD_VC</name>
   <tag></tag>
   <elementGuidId>312539ef-868f-45b7-b82c-54f9790cbaea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addFieldsByType_1_D001MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addFieldsByType_1_D001MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0022bc22-6ce9-4758-81ab-79224ca3b68f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>54e70623-cb86-401d-b3f1-03083ba57da4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>88b55117-dfd6-415c-af1f-86a4de60a3d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>additionalFieldsByTypeCOList[0].ADD_VC</value>
      <webElementGuid>73248914-5699-443b-ba47-d2e845ca8bc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>038a04e8-e891-4b72-863e-02de4fbd0a3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>04aa455b-229f-467d-9c56-8d2a80650f76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addFieldsByType_1_D001MT</value>
      <webElementGuid>2807ca04-62b2-47a3-aada-53e46fef3540</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3af12d72-c292-481c-8cfd-111f41e09ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minlength</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d421cb9a-d760-4b16-8786-8b13002479c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addFieldsByType_1_D001MT&quot;)</value>
      <webElementGuid>40b06cb0-8ac4-4a02-88b4-fa382f8c7e04</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addFieldsByType_1_D001MT']</value>
      <webElementGuid>3e2104a2-8aa9-475e-9570-d821b1254f53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trxMgntAddFieldsTypeDiv_id_D001MT']/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>59c2427b-4223-4b70-9d59-5949fbd7b070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>1ff96d48-049e-4d31-98b1-0e4fe88b2047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'additionalFieldsByTypeCOList[0].ADD_VC' and @id = 'addFieldsByType_1_D001MT']</value>
      <webElementGuid>8760b4e4-a88f-4f29-b20e-e38066d18e2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
