<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__trxMgntCO.ctstrsVO.AMOUNT</name>
   <tag></tag>
   <elementGuidId>337ef0ce-ac7e-4a3c-bad5-a9686f4b0482</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='amount_D001MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#amount_D001MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>48b53b4d-688f-4e2f-a806-79b8dfb6e899</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>61b9b06d-2e05-411d-bacf-967318284605</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>8e7444f9-e9a1-49d1-b104-b61931782099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trxMgntCO.ctstrsVO.AMOUNT</value>
      <webElementGuid>b6377111-2ef2-492a-adab-80aa5cb1b6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>ea34d3f2-d941-4afe-98d6-d57a0ae20f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>amount_D001MT</value>
      <webElementGuid>608ec4eb-b4a6-4e97-9e37-89770bb57610</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>60d7a8d8-8562-4635-b96f-3b50c712b6f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#,##0.000</value>
      <webElementGuid>c6a56496-19f5-4c14-89c8-59c8ca0628d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>noformat</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>cbaf3578-ad5c-4a56-813a-1b8cf3b5ef8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalsepa</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>80bca308-acfc-400a-b4bf-4027f225812a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>groupsepa</name>
      <type>Main</type>
      <value>,</value>
      <webElementGuid>080e7f4c-efba-4e2f-9f5b-466d8fa6f17e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxvalue</name>
      <type>Main</type>
      <value>999999999999.999</value>
      <webElementGuid>76043e27-8ce0-48e2-9912-8a5ee5c74237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlenbeforedec</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>b6d92735-8224-4ff6-9d23-44026df557e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5a73b938-5045-408c-a73c-72d03858b9fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>trxMgnt_reloadCyDenom()</value>
      <webElementGuid>f7c8cb3f-7b92-491f-9567-214a9f764867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fieldaudit</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>2f7e0fc9-d930-4c5e-a07e-316407ee4326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>@JS_VAR_amountDependency_D001MT,@JS_VAR_chargesCommonDep_D001MT,remittance_fr_num_D001MT:trxMgntCO.ctstrsVO.REMITTANCE_FR_NUM,cyPurchaseSaleBehavior_D001MT:trxMgntCO.cyPurchaseSaleBehavior</value>
      <webElementGuid>94d38dd1-fe9f-4494-9ccb-2207a9c9dbc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/trxMgnt/TrxMgntDependencies_dependencyByAmount</value>
      <webElementGuid>d3b41685-7883-4f64-a780-3fff8b5cf56c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>trxMgntCO.ctstrsVO.BENEF_BANK:lookuptxt_benef_bank_D001MT,trxMgntCO.multiTrsNo:multi_trs_no_D001MT,@JS_VAR_amountParams_D001MT,@JS_VAR_chargesCommonParams_D001MT,trxMgntCO.ctstrsExtendedVO.CY_PURCHASE_SALE:cy_purchaseSale_D001MT,trxMgntCO.ctstrsExtendedVO.TRX_DETAILS:trx_details_D001MT,trxMgntCO.ctstrsExtendedVO.NEGOTIATED_RATE:nego_exchange_rate_D001MT,trxMgntCO.availAmount:avail_am_D001MT,trxMgntCO.ctsCircularDefVO.AUTH_CEILING_CV_AMNT:auth_ceiling_circular_D001MT,trxMgntCO.ctsTrsExchClientDetVO.AUTHORIZATION_CEILING:auth_ceiling_D001MT,trxMgntCO.ctstrsVO.TRS_AC_CY:trs_ac_cy_D001MT,trxMgntCO.ctstrsVO.TRS_AC_CIF:trs_ac_cif_D001MT,trxMgntCO.ctstrsVO.TO_TRS_AC_CY:to_trs_ac_cy_D001MT,trxMgntCO.ctstrsVO.TO_TRS_AC_CIF:to_trs_ac_cif_D001MT,trxMgntCO.ctstrsVO.TRS_CY:lookuptxt_trs_cy_D001MT,trxMgntCO.ctstrxtypeVO.TYPE:type_D001MT,trxMgntCO.ctstrxtypeVO.CR_DR_FOREX:cr_dr_forex_D001MT,trxMgntCO.proceedWithCyPurchaseSale:proceedWithCyPurchaseSale_D001MT,trxMgntCO.ctstrsVO.VOID_REASON:holdReason_D001MT</value>
      <webElementGuid>d15e66c9-f95a-45e1-a722-369a00e370a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>5ec93f88-958e-45a5-8486-9ee5de1cd1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Amount_key</value>
      <webElementGuid>292816ca-6d50-444c-9459-cdcfcb6c5701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Amount</value>
      <webElementGuid>eb351c39-2928-438f-a359-2dfff6e3d116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;amount_D001MT&quot;)</value>
      <webElementGuid>2006861b-08e5-4b90-bd48-8311d0939441</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='amount_D001MT']</value>
      <webElementGuid>a3d5bed1-25b6-49e6-b8ee-3923b721be41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trxMgntListDetailDiv_D001MT']/div[2]/table/tbody/tr[7]/td[2]/table/tbody/tr[6]/td[2]/div/input</value>
      <webElementGuid>2992e442-682c-420f-b954-2147772324a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/div/input</value>
      <webElementGuid>0b4d361a-5142-4747-8955-7cc74680428a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'trxMgntCO.ctstrsVO.AMOUNT' and @id = 'amount_D001MT' and @title = 'Amount']</value>
      <webElementGuid>9584a94c-bfca-4a67-92a0-97eeb9f1b934</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
