<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Status_amfVO.CIF_SUB_NO</name>
   <tag></tag>
   <elementGuidId>87c9f3b4-9938-4ecb-bdbb-a9ed6e3cabb6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_trs_ac_sl_D001MT_gs_amfVO.CIF_SUB_NO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>43043eaf-b16a-4a91-b4c6-5308895316e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b8e85d2-530e-4dfb-a3f1-6cb557f6bf43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>amfVO.CIF_SUB_NO</value>
      <webElementGuid>28c1b609-afc7-4762-adf2-1c6de09e4972</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_trs_ac_sl_D001MT_gs_amfVO.CIF_SUB_NO</value>
      <webElementGuid>2e61c7e0-c270-4878-b8f8-25070dd008d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_trs_ac_sl_D001MT_gs_amfVO.CIF_SUB_NO&quot;)</value>
      <webElementGuid>eebbd369-d055-4ad4-a7c6-5f64044cff5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_trs_ac_sl_D001MT_gs_amfVO.CIF_SUB_NO']</value>
      <webElementGuid>2ca8df43-9a72-47c0-b1a2-844b977f453b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_trs_ac_sl_D001MT']/div[2]/div/table/thead/tr[2]/th[5]/div/input</value>
      <webElementGuid>9a087707-e06f-482e-9a9c-dd81535fd958</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[3]/div[2]/div/table/thead/tr[2]/th[5]/div/input</value>
      <webElementGuid>8e879065-8816-4604-965a-d3d1ca1177c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'amfVO.CIF_SUB_NO' and @id = 'gridtab_trs_ac_sl_D001MT_gs_amfVO.CIF_SUB_NO']</value>
      <webElementGuid>341f4e52-c823-48a4-86c7-6215d58d33d1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
