<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Reference_SHORT_DESC_ENG</name>
   <tag></tag>
   <elementGuidId>c671a316-9d75-4447-8b22-aef86ce8d705</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_trx_type_D001MT_gs_SHORT_DESC_ENG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gridtab_trx_type_D001MT_gs_SHORT_DESC_ENG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f10ff6d4-3a95-4d7f-9e76-fe4e2a898b5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1f11a395-c242-4ee3-89c3-06fcf5f65816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SHORT_DESC_ENG</value>
      <webElementGuid>398efb1d-cb7d-4b12-a10e-b023268d0c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_trx_type_D001MT_gs_SHORT_DESC_ENG</value>
      <webElementGuid>b2cbfd82-0a66-4c35-9fba-e5c2a8d2666f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_trx_type_D001MT_gs_SHORT_DESC_ENG&quot;)</value>
      <webElementGuid>eb848fa3-a0da-45dc-af76-e869686f450f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_trx_type_D001MT_gs_SHORT_DESC_ENG']</value>
      <webElementGuid>f38ee38f-c501-42b7-9a2c-232d202a1b84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_trx_type_D001MT']/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>effaa499-5ec8-48f4-aa7f-480145883df8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[17]/div/div[3]/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>409a7e3b-6469-4174-9087-01aca0b0b11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SHORT_DESC_ENG' and @id = 'gridtab_trx_type_D001MT_gs_SHORT_DESC_ENG']</value>
      <webElementGuid>245c4e38-bc6a-4669-ba83-907ee4c6b6b4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
