<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ID Number_trxMgntCO.ctstrsVO.DEPOSITER_ID</name>
   <tag></tag>
   <elementGuidId>4103cc2d-0640-4af2-901a-831ceb2dc56d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='id_no_D001MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#id_no_D001MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dd5152ca-0944-477a-bc7f-33b19e6d129b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e3679ea-4167-4d70-8341-037c4413cf4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f6ffa74b-c24b-4d70-aaa9-ef289d70714e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>trxMgntCO.ctstrsVO.DEPOSITER_ID</value>
      <webElementGuid>db9c1773-e829-4382-b71a-033410a8374d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>bba5af6e-2900-4b8a-91f6-03a9789e00d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>40</value>
      <webElementGuid>94347dfc-ea55-4431-a629-3896db07efe9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>id_no_D001MT</value>
      <webElementGuid>e1ddac26-585b-4529-aa89-1d42264e2cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prevvalue</name>
      <type>Main</type>
      <value>04181228</value>
      <webElementGuid>595b1952-a045-46a5-bde0-cb1be8b33889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>id_no_D001MT:trxMgntCO.ctstrsVO.DEPOSITER_ID,id_typeDesc_{_pageRef}:trxMgntCO.id_typeDesc,lblPepWarning_D001MT:trxMgntCO.pepWarning</value>
      <webElementGuid>1fc2fab7-66a6-45b3-9586-1b52f3245359</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/trxMgnt/TrxMgntDependencies_dependencyByDepositerId</value>
      <webElementGuid>40a648b8-2e91-490f-8874-a347071b6854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>trxMgntCO.ctstrsVO.DEPOSITER_ID:id_no_D001MT,trxMgntCO.ctstrsVO.ID_TYPE:lookuptxt_id_type_D001MT,trxMgntCO.ctstrsVO.TRS_AC_CIF:trs_ac_cif_D001MT,trxMgntCO.ctstrsVO.COUNTER_PARTY:lookuptxt_counter_party_D001MT</value>
      <webElementGuid>fc2f3e3a-5b96-4bdd-8645-02b94488f6b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id_no_D001MT&quot;)</value>
      <webElementGuid>3a4e0269-5b20-45a6-9eb6-6e0ec3fb1f30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='id_no_D001MT']</value>
      <webElementGuid>e5b92a63-f4c8-434f-8031-bfb9dbbe7404</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='trxMgntListDetailDiv_D001MT']/div[2]/table/tbody/tr[5]/td[3]/table/tbody/tr[2]/td[5]/input</value>
      <webElementGuid>b3d0f937-48ac-40b8-88e2-444f4bfde28d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>89cd9dc9-2ff3-4338-9553-741a723fbea2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'trxMgntCO.ctstrsVO.DEPOSITER_ID' and @id = 'id_no_D001MT']</value>
      <webElementGuid>85809996-4069-4908-9fe6-cd06f548d602</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
