<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Save</name>
   <tag></tag>
   <elementGuidId>dd0c641f-31a9-45b5-9710-f162f254c478</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='trxMgntSaveBtn_D001MT']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#trxMgntSaveBtn_D001MT > span.ui-button-text</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d7cc1441-142c-4012-8cd4-d162a9c235db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text</value>
      <webElementGuid>a55462c6-658a-464f-9ae4-d144ad4d9df7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Save 
</value>
      <webElementGuid>ea4871fc-6774-4e9a-a554-4149622e2e61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;trxMgntSaveBtn_D001MT&quot;)/span[@class=&quot;ui-button-text&quot;]</value>
      <webElementGuid>6d09bd81-91f7-4e52-ad18-15a46ae6325b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='trxMgntSaveBtn_D001MT']/span</value>
      <webElementGuid>bbc5136a-0ecf-401d-ad2b-9321e6453b00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='narration'])[1]/following::span[1]</value>
      <webElementGuid>addaca00-2ce7-4b96-baca-cf9190cdb2db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status Reason'])[1]/following::span[1]</value>
      <webElementGuid>e93ac2a2-33ee-4462-ab30-a2cb4d596279</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Officer Code'])[1]/preceding::span[1]</value>
      <webElementGuid>c5d0b8fe-7acd-4a50-aaa0-1640e1dc50a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Officer Name'])[1]/preceding::span[1]</value>
      <webElementGuid>ad705a95-be3e-4f3b-8502-6cd525566e64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>89b9fd6f-0608-4412-981c-47c1a8de9dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/button/span</value>
      <webElementGuid>c3e82cec-d917-4da1-b882-acf914e4f15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = ' Save 
' or . = ' Save 
')]</value>
      <webElementGuid>fe63a988-011e-4d4c-b809-6278f0e4b0c2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
