<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_512</name>
   <tag></tag>
   <elementGuidId>1cada2dc-3a61-4356-98e0-8f3522f54b4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_trs_ac_sl_D001MT_1_amfVO.CURRENCY_CODE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>61bbb199-ef5f-43bb-bd6f-6623a2c0a761</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>1106a011-2ff9-4340-974a-894866fea53c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>4e6bb510-652d-4d93-9a19-4a484b1a042a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>76cb2df8-348e-4ed7-be02-6f36a5d15ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Currency</value>
      <webElementGuid>9725deaa-b5c6-4903-93a0-ace79f187f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_trs_ac_sl_D001MT_amfVO.CURRENCY_CODE</value>
      <webElementGuid>3e4db4c7-4fe3-4e38-b8cd-5ec6e1bc215a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_trs_ac_sl_D001MT_1_amfVO.CURRENCY_CODE</value>
      <webElementGuid>43c61804-6e13-4bc5-bbee-5cbb6e88c15e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>6bf0bc60-cc01-468f-b8bd-9ceba1de01b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_trs_ac_sl_D001MT_1_amfVO.CURRENCY_CODE&quot;)</value>
      <webElementGuid>cf51b042-f6ee-4f3c-a7ca-57bc6b0467a4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_trs_ac_sl_D001MT_1_amfVO.CURRENCY_CODE']</value>
      <webElementGuid>8b7e6198-6d09-4dbd-8577-d3c6f5ca52fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[2]</value>
      <webElementGuid>d4915dad-94b1-4722-a26a-b40a65132207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[5]/following::td[37]</value>
      <webElementGuid>e20d037c-dca2-4e4e-9d84-5ec52f2ca703</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nick Name'])[1]/following::td[37]</value>
      <webElementGuid>0ba7ce95-53e6-41c9-829a-316fe41275c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Savings Account'])[1]/preceding::td[2]</value>
      <webElementGuid>0ca32bd0-51e3-4838-8dfe-4f3fd86764ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='B'])[1]/preceding::td[13]</value>
      <webElementGuid>805c4b3f-dc73-445a-9897-175979234121</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='512']/parent::*</value>
      <webElementGuid>592c341e-cd50-4243-909c-be1462096565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>9ceaceb2-ecef-41e3-ba2b-324e82529b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '512' and @id = 'td_gridtab_trs_ac_sl_D001MT_1_amfVO.CURRENCY_CODE' and (text() = '512' or . = '512')]</value>
      <webElementGuid>0e45ef66-5949-4ab6-8486-70f3d21eb11c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
