<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Cash Deposit</name>
   <tag></tag>
   <elementGuidId>e33eba74-8b22-4c5c-9840-2f948dd99572</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_trx_type_D001MT_1_SHORT_DESC_ENG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_trx_type_D001MT_1_SHORT_DESC_ENG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>75a46309-1311-48b4-904a-197ac412e613</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>01915e1d-d484-4d88-bcfb-e20ce6de548a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Cash Deposit</value>
      <webElementGuid>a07e3de2-ddc4-4f11-a765-a039ff2bda12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>18d1f538-6298-4b6c-be32-a6ee07d313e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_trx_type_D001MT_SHORT_DESC_ENG</value>
      <webElementGuid>dcfd212b-69bd-41b1-a22b-dae3e69cdc0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_trx_type_D001MT_1_SHORT_DESC_ENG</value>
      <webElementGuid>986a8734-35a9-4cd9-9a43-7b75ae935fc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cash Deposit</value>
      <webElementGuid>ba12fed7-4521-42a4-8e70-2ccfc624e5c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_trx_type_D001MT_1_SHORT_DESC_ENG&quot;)</value>
      <webElementGuid>48688bab-3c4f-4250-bb5a-635d726cb97d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_trx_type_D001MT_1_SHORT_DESC_ENG']</value>
      <webElementGuid>9b06960d-83c3-4562-a618-7efe4227df18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[2]</value>
      <webElementGuid>d45cbb53-57ae-4cb2-b7a8-e04bde9d0944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reference'])[1]/following::td[8]</value>
      <webElementGuid>45889a86-77dd-4cb7-b171-71836eee1827</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف الكامل'])[1]/following::td[8]</value>
      <webElementGuid>47fc4d5a-f453-44e9-8289-83c8b8e00a61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cash Deposit'])[2]/preceding::td[1]</value>
      <webElementGuid>e9257808-efcd-4246-b2cd-69348224d444</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ايداع نقدي'])[1]/preceding::td[2]</value>
      <webElementGuid>83518272-8ea2-4648-abf3-f4a1a0f2bed5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cash Deposit']/parent::*</value>
      <webElementGuid>3f53da5b-eb17-450e-b845-c18df99ec237</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>cc73a968-eca7-41ce-9130-25728fb25828</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Cash Deposit' and @id = 'td_gridtab_trx_type_D001MT_1_SHORT_DESC_ENG' and (text() = 'Cash Deposit' or . = 'Cash Deposit')]</value>
      <webElementGuid>ad5c36f1-3706-4c31-8e49-833dd0e2dd6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
