<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_CIF No</name>
   <tag></tag>
   <elementGuidId>56715a48-5e6f-454d-a13c-0970cc618bcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='jqgh_fomGridTbl_Id_F00I1P_cifVO.CIF_NO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bdcb188c-863e-4eca-acd4-aa2c89bda850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>jqgh_fomGridTbl_Id_F00I1P_cifVO.CIF_NO</value>
      <webElementGuid>afd2d0af-621b-4abb-8223-3f9f6347f769</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-jqgrid-sortable</value>
      <webElementGuid>1a16b8b7-6f14-47d6-9cb0-e08ad067c5a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CIF No</value>
      <webElementGuid>557c9aed-e6b2-45d0-a822-ecf7bd628fe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;jqgh_fomGridTbl_Id_F00I1P_cifVO.CIF_NO&quot;)</value>
      <webElementGuid>e946b8b8-3ec6-4351-817c-357b9d67a444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='jqgh_fomGridTbl_Id_F00I1P_cifVO.CIF_NO']</value>
      <webElementGuid>11c146a9-b20e-4ebc-abce-01e7625c1f96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//th[@id='fomGridTbl_Id_F00I1P_cifVO.CIF_NO']/div</value>
      <webElementGuid>223b5696-f0b1-41c2-bd11-c78e83a93f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Branch Code'])[1]/following::div[1]</value>
      <webElementGuid>f00d632a-f4b3-4887-8c8c-68859a4ef2aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CIF'])[1]/following::div[5]</value>
      <webElementGuid>de7bb299-9e76-4510-9cd7-f78a317fe537</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::div[1]</value>
      <webElementGuid>51e05199-e30e-4dd8-9914-b99bfa710c00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Short Name'])[1]/preceding::div[2]</value>
      <webElementGuid>62bbd9b8-1552-46cd-a2ad-c56dffa15535</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CIF No']/parent::*</value>
      <webElementGuid>b498abaf-1fe8-46db-a6aa-2b0a367f6bb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div</value>
      <webElementGuid>e036c5db-cd79-452c-81d0-c87fa6b5938f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'jqgh_fomGridTbl_Id_F00I1P_cifVO.CIF_NO' and (text() = 'CIF No' or . = 'CIF No')]</value>
      <webElementGuid>c2694465-5736-430d-87a4-8b333697bfdc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
