<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CIF_NO</name>
   <tag></tag>
   <elementGuidId>6dab7d00-4f83-49f0-be26-66628f62294e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fomGridTbl_Id_F00I1P_gs_cifVO.CIF_NO']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e7c8ede4-f10a-440f-9c1f-bb8ff20ea493</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2080e469-a61f-47d7-8ad4-9a3c6f950d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CIF_NO</value>
      <webElementGuid>d509a5a8-49a1-4ff0-8772-2190bbdee099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fomGridTbl_Id_F00I1P_gs_cifVO.CIF_NO</value>
      <webElementGuid>7fa020b0-609c-41f6-8431-60b317c1372a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomGridTbl_Id_F00I1P_gs_cifVO.CIF_NO&quot;)</value>
      <webElementGuid>e31611f7-14b7-49f8-b6fe-508550b6f8d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fomGridTbl_Id_F00I1P_gs_cifVO.CIF_NO']</value>
      <webElementGuid>3b6e16ef-7374-42f0-bcb3-4a397ec697af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_fomGridTbl_Id_F00I1P']/div[2]/div/table/thead/tr[2]/th[3]/div/input</value>
      <webElementGuid>b7c11bea-b579-4164-a0f5-cf2a48054e07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[3]/div/input</value>
      <webElementGuid>efcdf334-b2cf-4d01-9f88-fd8f6bdf5f54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'CIF_NO' and @id = 'fomGridTbl_Id_F00I1P_gs_cifVO.CIF_NO']</value>
      <webElementGuid>21cd08f0-5c27-4d03-ac41-fa7389198818</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
