<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__SHORT_NAME_ENG</name>
   <tag></tag>
   <elementGuidId>af0ddd80-ea98-4689-8a7e-c7e717f494a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fomGridTbl_Id_F00I1P_gs_cifVO.SHORT_NAME_ENG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f17e27a8-73af-4750-b0f8-1910dbb8dfbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>de5a92ae-b152-4260-912d-af615e67bddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SHORT_NAME_ENG</value>
      <webElementGuid>dc9f70a8-d43e-4d44-ac26-9a975f8a3623</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fomGridTbl_Id_F00I1P_gs_cifVO.SHORT_NAME_ENG</value>
      <webElementGuid>153e63a6-564e-410d-bdb7-06a57f79761f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomGridTbl_Id_F00I1P_gs_cifVO.SHORT_NAME_ENG&quot;)</value>
      <webElementGuid>36832a18-7ec0-4949-ab9b-f79720a95669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fomGridTbl_Id_F00I1P_gs_cifVO.SHORT_NAME_ENG']</value>
      <webElementGuid>9d136b51-89f0-4d71-ae1d-b84a932040a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_fomGridTbl_Id_F00I1P']/div[2]/div/table/thead/tr[2]/th[5]/div/input</value>
      <webElementGuid>ea7cd8d0-8826-443e-b46f-1da6b8941bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[5]/div/input</value>
      <webElementGuid>51a1ac3f-f1ed-442c-9a10-8be92fd60cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'SHORT_NAME_ENG' and @id = 'fomGridTbl_Id_F00I1P_gs_cifVO.SHORT_NAME_ENG']</value>
      <webElementGuid>bf8ba87a-7fcd-41c2-9ca0-6a85929e6754</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
