<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__BRANCH_CODE</name>
   <tag></tag>
   <elementGuidId>c792fb3c-5519-40f2-b7d1-0b6a5fb76565</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='fomGridTbl_Id_F00I1P_gs_cifVO.BRANCH_CODE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9cdd5bba-77f3-47a0-b710-ba55e0324082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>89a63428-917f-4067-a520-9e460a86926b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRANCH_CODE</value>
      <webElementGuid>432dd9dd-7ceb-408d-acab-ee34fcd74fb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fomGridTbl_Id_F00I1P_gs_cifVO.BRANCH_CODE</value>
      <webElementGuid>83d108af-70cf-4132-9bdc-14c4c0d37bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomGridTbl_Id_F00I1P_gs_cifVO.BRANCH_CODE&quot;)</value>
      <webElementGuid>56965de5-13b8-42e0-8fd3-075dc6f46177</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='fomGridTbl_Id_F00I1P_gs_cifVO.BRANCH_CODE']</value>
      <webElementGuid>90d578b9-2ee2-4340-b659-d46fe7bd96a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_fomGridTbl_Id_F00I1P']/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>491681ad-e6db-40c1-be9b-6cf7f0fc4db9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[2]/div/input</value>
      <webElementGuid>6bd0f690-a2b8-483b-b964-4d9220600aaf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRANCH_CODE' and @id = 'fomGridTbl_Id_F00I1P_gs_cifVO.BRANCH_CODE']</value>
      <webElementGuid>f9c079d0-b062-4acf-90dc-749806ea22bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
