<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Approve</name>
   <tag></tag>
   <elementGuidId>047f82aa-14fa-4ad7-9fe1-e9ad7b75f68f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='fomMaintForm_F00I1P_Approve_key']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fomMaintForm_F00I1P_Approve_key</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>82781923-8660-4193-a67e-6e7de2397e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fomMaintForm_F00I1P_Approve_key</value>
      <webElementGuid>d34d1ddf-35eb-4a8b-820b-7b1569ddfb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>Approve_key</value>
      <webElementGuid>84d61e3e-2feb-498b-8300-7b29509c2f49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>adbb76d4-a866-48f7-a602-1f1005b5f3c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve </value>
      <webElementGuid>f5a8232d-34d3-43e9-a878-056fa1108b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomMaintForm_F00I1P_Approve_key&quot;)</value>
      <webElementGuid>5270a958-1978-4693-aa91-00d5e329802c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='fomMaintForm_F00I1P_Approve_key']</value>
      <webElementGuid>511e85fc-35d8-444d-938d-ea29648c2d3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fom_Approve_btn_F00I1P']/span[2]/label</value>
      <webElementGuid>1507c746-e6b6-4b40-b1df-e03d21e350f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='check_out_key'])[1]/following::label[1]</value>
      <webElementGuid>1f39c6d6-e5e8-4beb-b8b8-5d7040a56128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Fields'])[3]/following::label[2]</value>
      <webElementGuid>feab14ca-46e3-46da-ba3e-86ec399769de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/preceding::label[1]</value>
      <webElementGuid>b1267da8-70f4-406b-9e1b-78b5bc54680a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span[2]/label</value>
      <webElementGuid>cf68fb1b-4f40-49c3-9ae0-6add428b0e35</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'fomMaintForm_F00I1P_Approve_key' and (text() = 'Approve ' or . = 'Approve ')]</value>
      <webElementGuid>d54e6952-b597-4dc4-9c06-44e304dbef5b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
