<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_900</name>
   <tag></tag>
   <elementGuidId>7d97cef2-1415-4149-98f7-894a4627e3a1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_fomGridTbl_Id_F00I1P_1_cifVO.BRANCH_CODE']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>ad562967-0022-426e-9a8b-8f7ffd2e13d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>32c6504a-855b-42eb-a2ce-e0f3da754802</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>af86edc6-f760-4d6a-9fd7-476890e45e06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>900</value>
      <webElementGuid>83466e18-0bb5-4010-98cb-f5d0f4b10fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Branch Code</value>
      <webElementGuid>7f67b0cf-4874-424c-9172-602d918a6c6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>fomGridTbl_Id_F00I1P_cifVO.BRANCH_CODE</value>
      <webElementGuid>65dde3ab-84fd-404a-a064-222d0de4fec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_fomGridTbl_Id_F00I1P_1_cifVO.BRANCH_CODE</value>
      <webElementGuid>6f7222c7-760d-4a7b-b3dc-e1f51e984deb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>900</value>
      <webElementGuid>84837311-d8d9-43ed-a903-aad8e4e9dec1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_fomGridTbl_Id_F00I1P_1_cifVO.BRANCH_CODE&quot;)</value>
      <webElementGuid>980c8364-59c5-4185-aab6-47233d0076ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_fomGridTbl_Id_F00I1P_1_cifVO.BRANCH_CODE']</value>
      <webElementGuid>2a040174-2738-4889-97ea-f723bc3da63f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[2]</value>
      <webElementGuid>c9f7628e-64c8-42d7-a749-c5d108178e5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الاسم المفصّل'])[1]/following::td[24]</value>
      <webElementGuid>619faf5a-a0dd-4ce4-bd2c-c614b5e484e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الإسم الكامل بالعربية'])[1]/following::td[24]</value>
      <webElementGuid>1277b4a1-278e-4816-b14a-be4cc02a268b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::td[2]</value>
      <webElementGuid>f783a5f2-92c7-4eef-859d-d7ab4df649d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANU KUTTAN'])[1]/preceding::td[3]</value>
      <webElementGuid>39666482-211c-4db3-8929-66662a3f0120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='900']/parent::*</value>
      <webElementGuid>ed7c3be6-b497-4f12-af8b-4a0c5f0d47cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>b0c37b82-2101-4788-9cd9-98e630789eb5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '900' and @id = 'td_fomGridTbl_Id_F00I1P_1_cifVO.BRANCH_CODE' and (text() = '900' or . = '900')]</value>
      <webElementGuid>5e08d8b7-91f4-4a7a-9a54-0b55e41915b8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
