<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Approve</name>
   <tag></tag>
   <elementGuidId>52799180-ec25-415e-8125-00c928d4dc9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Q000AP</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='Q000AP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ba46d389-7d11-4f2a-8336-ec5d3153defd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Q000AP</value>
      <webElementGuid>825cebe7-8947-42f2-a1c0-a83a6f35be13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>bed7c53e-70cd-4cdf-a5a0-62c1526bdbb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:addMenuTab('Q000AP','Approve','RET','Q000' )</value>
      <webElementGuid>05b15dfb-05ce-4536-b7a7-69ab3e8d8a7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Approve	</value>
      <webElementGuid>865a7718-f031-4b0c-a6a9-9e905d2806d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Q000AP&quot;)</value>
      <webElementGuid>dd0d4992-fc4d-4c91-a9d8-5841db9b49ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='Q000AP']</value>
      <webElementGuid>1c478c4f-dcd0-4d02-b2bb-0d011efe5600</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_selenuimQ000AP']/li/a</value>
      <webElementGuid>1e9fd56f-5f00-4d5c-b139-f464f989ca78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maintenance'])[1]/following::a[1]</value>
      <webElementGuid>dbf0f243-830d-4d06-992c-861eaddb8101</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chequebook Request'])[1]/following::a[2]</value>
      <webElementGuid>ac4aa8a2-8278-4977-90bc-7e8d20601700</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/preceding::a[1]</value>
      <webElementGuid>5768ea0b-49df-4206-ac87-18525de8c00b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[13]</value>
      <webElementGuid>fd62deca-eb0c-4f7f-bf4f-6b107bf19763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/li/a</value>
      <webElementGuid>b6c781fa-4ffa-4ad1-a918-f14d1b93fbd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'Q000AP' and @href = '#' and (text() = 'Approve	' or . = 'Approve	')]</value>
      <webElementGuid>2d48fb1f-8d67-48b7-928a-c04d8b45d088</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
