<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trade Date_statusDesc</name>
   <tag></tag>
   <elementGuidId>068ac452-4e88-47ce-b3ff-31470996c9a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transferCashGridTbl_Id_L0VVRV_gs_statusDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transferCashGridTbl_Id_L0VVRV_gs_statusDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>10f727fc-8d7a-4d00-bb43-f873c7713fcb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1efaa443-8234-4748-82bb-02c599eab9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statusDesc</value>
      <webElementGuid>de5b9658-d5fa-4dfc-87bc-ad86ec556ed9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transferCashGridTbl_Id_L0VVRV_gs_statusDesc</value>
      <webElementGuid>14b4809a-f8ca-4b79-acb7-1b5cf1a3fadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferCashGridTbl_Id_L0VVRV_gs_statusDesc&quot;)</value>
      <webElementGuid>4e2c8750-4ab2-4362-a93c-43947ffcbdf8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transferCashGridTbl_Id_L0VVRV_gs_statusDesc']</value>
      <webElementGuid>ee1734bd-ffe8-464c-81f3-0875f3e0af40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_transferCashGridTbl_Id_L0VVRV']/div[2]/div/table/thead/tr[2]/th[6]/div/input</value>
      <webElementGuid>60bcec2f-7f59-4b68-ae2e-deabd978aa20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/div/input</value>
      <webElementGuid>ca5762a3-bb39-4fbc-84df-72cfca83a551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'statusDesc' and @id = 'transferCashGridTbl_Id_L0VVRV_gs_statusDesc']</value>
      <webElementGuid>84e44a89-fe4d-4ce0-a5e6-9e626e3bc9e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
