<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Apply To Reverse</name>
   <tag></tag>
   <elementGuidId>09ab9df7-e582-4fb5-a921-e22a44de149b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_transferCashGridTbl_Id_L0VVRV_1_statusDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_transferCashGridTbl_Id_L0VVRV_1_statusDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9fa45f66-c047-47b7-b956-337670e4bd48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>143ce71c-7537-4928-a54f-783a899e69b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Apply To Reverse</value>
      <webElementGuid>580b9f71-969f-4287-b8df-f8aa6d4a4474</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Status</value>
      <webElementGuid>e56fd614-0677-4c0c-918a-e8daccc9da8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>transferCashGridTbl_Id_L0VVRV_statusDesc</value>
      <webElementGuid>6df6def4-88bd-40ba-b542-e3ebc27a0e0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_transferCashGridTbl_Id_L0VVRV_1_statusDesc</value>
      <webElementGuid>9f2ea00a-d261-49df-8be3-1cd5f268057d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Apply To Reverse</value>
      <webElementGuid>db350473-388b-4f9f-b8d4-9ae2cda4966a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_transferCashGridTbl_Id_L0VVRV_1_statusDesc&quot;)</value>
      <webElementGuid>5c6a8b6b-45f3-42df-b0b6-2d1e5ef9c283</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_transferCashGridTbl_Id_L0VVRV_1_statusDesc']</value>
      <webElementGuid>cf37777e-5e4e-4c3d-a01a-6cb60e3d4047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[6]</value>
      <webElementGuid>bbc70266-324d-4b2a-bc45-95294426fe36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[2]/following::td[1]</value>
      <webElementGuid>964509c6-aaa4-49cf-9751-a043f5982991</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[1]/following::td[3]</value>
      <webElementGuid>1ecf8f33-c933-4b03-bb5c-ce5e36cba1ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[3]/preceding::td[4]</value>
      <webElementGuid>29aa284b-ef1e-445c-b6e3-6aee26f86712</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[4]/preceding::td[6]</value>
      <webElementGuid>b5a1bc15-428c-491f-aec7-17bfc1eb4c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Apply To Reverse']/parent::*</value>
      <webElementGuid>41f39014-4e01-41ee-b40d-4038b8ab9939</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[6]</value>
      <webElementGuid>7f008938-5e2b-4cfe-8b96-428aed51197c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Apply To Reverse' and @id = 'td_transferCashGridTbl_Id_L0VVRV_1_statusDesc' and (text() = 'Apply To Reverse' or . = 'Apply To Reverse')]</value>
      <webElementGuid>0e3a4718-60b0-4e8f-bcc4-b3193fe149ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
