<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_FATCA</name>
   <tag></tag>
   <elementGuidId>febdabfa-0037-4f5b-8686-f2c2a3f0d702</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fom_fatca_details_btn_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fom_fatca_details_btn_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>415ce342-6fe2-47a5-930a-3a0e465c65d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f663a3f1-33b7-4711-9d2f-b60029899581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fom_fatca_details_btn_F00I1MT</value>
      <webElementGuid>10e530df-c528-40a0-8d6e-561876900268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>9f0cb106-984c-43df-be92-efb5df0f3a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>freezeonsubmit</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0781571d-6bb9-4f55-a926-4185797cc088</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dynamicScreen_openDynamicScreen(4,null,'fom_fatca_details_btn_F00I1MT', 700,500,null,false,'fatca' );event.stopImmediatePropagation();</value>
      <webElementGuid>8ad57f85-01ce-4a60-b03d-d9a2b8d6f2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary ui-state-hover ui-state-focus</value>
      <webElementGuid>af98abc7-1235-43da-92e0-179d242d098a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86d6b686-aa87-48bf-844e-250bdca5cc96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5964f4dd-a6cb-4299-8c73-ce1f6a15b6c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FATCA  
</value>
      <webElementGuid>0d0cf66a-a19a-46af-9103-09b481596358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fom_fatca_details_btn_F00I1MT&quot;)</value>
      <webElementGuid>d046749e-c4a9-419a-ba84-cc2007c00f6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fom_fatca_details_btn_F00I1MT']</value>
      <webElementGuid>2cf46b8a-a884-42f0-ba72-10ba0503c006</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fomButtonToolbar_F00I1MT']/div[4]/div[7]/button</value>
      <webElementGuid>9d048761-3ab9-462e-905c-def6cc2a6465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges Waiver'])[1]/following::button[1]</value>
      <webElementGuid>d7eeedb9-9165-4abf-bf7c-627505597168</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proxies'])[1]/following::button[1]</value>
      <webElementGuid>994bb0b2-e1c9-4858-a21d-ba331f06d75c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PEP'])[1]/preceding::button[1]</value>
      <webElementGuid>637bce58-012a-4595-81e9-150166dae7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button</value>
      <webElementGuid>0d7b85cd-ddd3-4a71-a581-79902c3a2a23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'fom_fatca_details_btn_F00I1MT' and (text() = ' FATCA  
' or . = ' FATCA  
')]</value>
      <webElementGuid>7f24a1a2-cdcd-49b7-be35-365762781e70</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
