<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PEP</name>
   <tag></tag>
   <elementGuidId>b9c4adcc-e19f-4922-b80e-d5ce42dd5915</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='fom_pep_details_btn_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fom_pep_details_btn_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>2345b977-4de6-4f14-bf9e-86a16d48ea6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5d6bc23d-bf2b-4d62-b043-e76e9de7776b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fom_pep_details_btn_F00I1MT</value>
      <webElementGuid>fa0f25d4-7420-4c69-8f92-60d26f2887a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>6c3840e5-df6e-4701-b1bf-fa62e09eadf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>freezeonsubmit</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f0408e80-bff4-4120-b9bd-8eab9b368558</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>dynamicScreen_openDynamicScreen(2,null,'fom_pep_details_btn_F00I1MT', 700,500,null,false,'PEP' );event.stopImmediatePropagation();</value>
      <webElementGuid>606500a0-48e1-4820-bfb5-54887b099188</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button ui-widget ui-state-default ui-corner-all ui-button-text-icon-primary ui-state-hover ui-state-focus</value>
      <webElementGuid>3d6a849c-db0c-4066-8919-a903e5af01fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a2148a40-ade4-41ee-bae5-0de826a4adf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5b2105fc-b8a5-4bb0-8e62-a56139c894fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> PEP  
</value>
      <webElementGuid>e20a57e7-b7c6-4b8c-ae44-da19a887fcf9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fom_pep_details_btn_F00I1MT&quot;)</value>
      <webElementGuid>f3b65b2f-fe11-4371-8e43-93a132c30d05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='fom_pep_details_btn_F00I1MT']</value>
      <webElementGuid>da0d7993-9fae-4ebb-985a-414ed198e7aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='fomButtonToolbar_F00I1MT']/div[5]/div/button</value>
      <webElementGuid>7e0747ad-db30-4b12-ab03-94136bc2ef9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FATCA'])[1]/following::button[1]</value>
      <webElementGuid>ad753bbe-eae1-49f6-aadb-3fc8a82bccf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges Waiver'])[1]/following::button[2]</value>
      <webElementGuid>8823114a-f572-4b1c-bdae-732411f4e9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Package Products'])[1]/preceding::button[1]</value>
      <webElementGuid>e7c212bf-cd23-4299-bc36-b61f88279e47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button</value>
      <webElementGuid>992ca2bd-6644-4c65-8f18-dfd974e0b13a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'fom_pep_details_btn_F00I1MT' and (text() = ' PEP  
' or . = ' PEP  
')]</value>
      <webElementGuid>3438be44-5dfd-4a7e-823b-4ae6a3e18ee0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
