<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifExtendedVO.FULL_NAME_ARAB</name>
   <tag></tag>
   <elementGuidId>cf007174-d62d-445b-a89f-3ea958767b16</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifExtendedVO_FULL_NAME_ARAB_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cifExtendedVO_FULL_NAME_ARAB_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>427b30d1-2260-49fa-b4e3-5456d229d505</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>096c0b67-f60d-4a34-95c8-e00d00c72c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>460773ec-9578-4f55-a8bc-9ba8bf4819d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifExtendedVO.FULL_NAME_ARAB</value>
      <webElementGuid>01ccdd8c-3dbd-43a5-a8dc-dc18b0b6b342</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>bf7d264a-bfe9-44ea-9a7e-0badb08ac4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>1f2e01e3-ed51-4ecd-8ba7-7e90c2557220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifExtendedVO_FULL_NAME_ARAB_F00I1MT</value>
      <webElementGuid>e8a380af-13e3-4310-a617-f60c76d4fa5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cifVO_SHORT_NAME_ARAB_F00I1MT:fomCO.cifVO.SHORT_NAME_ARAB,cifVO_LONG_NAME_ARAB_F00I1MT:fomCO.cifVO.LONG_NAME_ARAB,cifExtendedVO_FULL_NAME_ARAB_F00I1MT:fomCO.cifExtendedVO.FULL_NAME_ARAB</value>
      <webElementGuid>1daef031-e1f8-40e5-9256-a7b1f5ff42d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_dependencyByFullNameArab</value>
      <webElementGuid>4282a944-cbf0-44fe-a189-42057d94f560</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.cifExtendedVO.FULL_NAME_ARAB:cifExtendedVO_FULL_NAME_ARAB_F00I1MT,_pageRef:_pageRef,fomCO.cifVO.SHORT_NAME_ARAB:cifVO_SHORT_NAME_ARAB_F00I1MT,fomCO.cifVO.LONG_NAME_ARAB:cifVO_LONG_NAME_ARAB_F00I1MT</value>
      <webElementGuid>473bdf1d-e4c2-4864-86cd-fe3df3a74479</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifExtendedVO_FULL_NAME_ARAB_F00I1MT&quot;)</value>
      <webElementGuid>5d8d885e-b4b0-4c70-ba31-6aec29f654c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifExtendedVO_FULL_NAME_ARAB_F00I1MT']</value>
      <webElementGuid>0d4e9f87-4d0d-4721-acd4-784b3aebfbd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel2']/div[3]/table/tbody/tr[9]/td[2]/input</value>
      <webElementGuid>92e0b342-bace-495e-91d0-133acbe8b551</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[9]/td[2]/input</value>
      <webElementGuid>a6d0b832-b44c-41ee-b3ed-e9ff3e1517fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifExtendedVO.FULL_NAME_ARAB' and @id = 'cifExtendedVO_FULL_NAME_ARAB_F00I1MT']</value>
      <webElementGuid>80fb2e8e-9742-4888-837f-e9338ac84ceb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
