<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifVO.ID_EXPIRY_DATE</name>
   <tag></tag>
   <elementGuidId>9b186412-54c2-43d4-9bf7-d3fbf2ae58c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifVO_ID_EXPIRY_DATE_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cifVO_ID_EXPIRY_DATE_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0eaf2a0b-4d0b-4e69-98dc-4d55618635a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>22579ae1-7e4a-474a-b126-e1b44e9bc580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>335868ec-6157-42b5-8166-5694269c31be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.ID_EXPIRY_DATE</value>
      <webElementGuid>b4984182-b841-4f18-9948-51b7f522938f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12px</value>
      <webElementGuid>c2a78b5d-322a-4ba2-a8b6-fa8b8004cf31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input ui-state-focus ui-corner-all path-text-size hasDatepicker</value>
      <webElementGuid>834c8923-fc14-492f-818a-90d91f109704</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_ID_EXPIRY_DATE_F00I1MT</value>
      <webElementGuid>a95e9129-f9b3-43f7-8ee1-3e869116906c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cifVO_ID_EXPIRY_DATE_F00I1MT:fomCO.cifVO.ID_EXPIRY_DATE</value>
      <webElementGuid>be1d0285-72ad-48eb-9f10-1d77268afc80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateIDExpiryDate</value>
      <webElementGuid>b7598cbf-bd1b-4a62-95e9-fbb9cc122324</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.cifVO.ID_EXPIRY_DATE:cifVO_ID_EXPIRY_DATE_F00I1MT,fomCO.cifVO.CIF_NO:cifVO_CIF_NO_F00I1MT,fomCO.cifVO.ID_DELIVERY_DATE:cifVO_ID_DELIVERY_DATE_F00I1MT,fomCO.cifVO.BIRTH_DATE:cifVO_BIRTH_DATE_F00I1MT,fomCO.cifVO.ID_TYPE:lookuptxt_cifVO_ID_TYPE_F00I1MT</value>
      <webElementGuid>653be05b-187b-4356-b055-f36d234a743f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>ID Expiry Date</value>
      <webElementGuid>7b6c52d5-4912-4dce-8774-20834c03798e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>ID_Expiry_Date_key</value>
      <webElementGuid>95c8a1d9-b28f-4916-8f2d-6bbba3b3c5f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ID Expiry Date</value>
      <webElementGuid>f566f825-5088-43d7-8969-cee07d1aed49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>b65f3e51-b477-4ff7-90f3-4a16016a6d8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_ID_EXPIRY_DATE_F00I1MT&quot;)</value>
      <webElementGuid>e77171e7-48bf-4296-9792-8ac784dcd640</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifVO_ID_EXPIRY_DATE_F00I1MT']</value>
      <webElementGuid>e2b29a87-be30-43f4-9785-c7ae028b1047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel1']/div[3]/table/tbody/tr[6]/td[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>4f039699-26ff-4b9a-b51a-e421e11462dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>d5a609af-b8a9-4635-a94d-c6738dd88c50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifVO.ID_EXPIRY_DATE' and @id = 'cifVO_ID_EXPIRY_DATE_F00I1MT' and @title = 'ID Expiry Date']</value>
      <webElementGuid>d14c8c61-3a35-4b44-ae07-2273805036aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
