<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Full Name_fomCO.cifExtendedVO.FULL_NAME_ENG</name>
   <tag></tag>
   <elementGuidId>d911e298-72f5-46d5-9ada-3915f629ad22</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifExtendedVO_FULL_NAME_ENG_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cifExtendedVO_FULL_NAME_ENG_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d51f232-bf5a-43f6-a999-13b00eda4c7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9213eaa4-4bc8-4709-9f8a-9e38b39c6e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>66e72df5-333b-4264-af59-97ac9665e5eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifExtendedVO.FULL_NAME_ENG</value>
      <webElementGuid>05904e23-2f93-484c-bfad-ed9f75e414ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>927262f2-367d-419e-9f6f-f1614cb2808a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>250</value>
      <webElementGuid>303194d8-528e-4eca-a78d-6aeee8053c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifExtendedVO_FULL_NAME_ENG_F00I1MT</value>
      <webElementGuid>6e0ce7fa-2739-43d8-8f51-3810713a8c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cifVO_SHORT_NAME_ENG_F00I1MT:fomCO.cifVO.SHORT_NAME_ENG,cifVO_LONG_NAME_ENG_F00I1MT:fomCO.cifVO.LONG_NAME_ENG,cifExtendedVO_FULL_NAME_ENG_F00I1MT:fomCO.cifExtendedVO.FULL_NAME_ENG,cifVO_AUTH_NAME_F00I1MT:fomCO.cifVO.AUTH_NAME</value>
      <webElementGuid>b5b8d518-54f3-4077-ad54-4f1d6c3a9e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_dependencyByFullNameEng</value>
      <webElementGuid>6d56db8b-ac62-4f5f-8d7d-fff2b8e53f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.cifExtendedVO.FULL_NAME_ENG:cifExtendedVO_FULL_NAME_ENG_F00I1MT,_pageRef:_pageRef,fomCO.cifVO.SHORT_NAME_ENG:cifVO_SHORT_NAME_ENG_F00I1MT,fomCO.cifVO.LONG_NAME_ENG:cifVO_LONG_NAME_ENG_F00I1MT</value>
      <webElementGuid>10c910cd-49e4-4309-8e20-7b66fc56d8ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifExtendedVO_FULL_NAME_ENG_F00I1MT&quot;)</value>
      <webElementGuid>2ad24384-2ead-453c-8fd2-0edd7f8ce126</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifExtendedVO_FULL_NAME_ENG_F00I1MT']</value>
      <webElementGuid>114b9d34-6942-4347-a8d6-e8ab336edd11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel2']/div[3]/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>c0511fd8-3639-4c7f-a44a-3224f60c89c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td[2]/input</value>
      <webElementGuid>65a7ee3d-8c8f-455b-93d2-1b91a792b695</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifExtendedVO.FULL_NAME_ENG' and @id = 'cifExtendedVO_FULL_NAME_ENG_F00I1MT']</value>
      <webElementGuid>e436f7a9-6e7e-493f-bdc5-0940ce5c1521</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
