<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ISO Code_BRIEF_DESC_ENG</name>
   <tag></tag>
   <elementGuidId>83e41dbb-2738-4951-a51e-214ad0bb10e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_countryOfIssuance_F00I1MT_gs_BRIEF_DESC_ENG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gridtab_countryOfIssuance_F00I1MT_gs_BRIEF_DESC_ENG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>87637f72-d9e5-40ce-81ed-de9e2713a739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bca682db-d5cb-469d-ae52-e2238c8f0814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRIEF_DESC_ENG</value>
      <webElementGuid>066c1182-3c32-428f-a176-62ab1efa9115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_countryOfIssuance_F00I1MT_gs_BRIEF_DESC_ENG</value>
      <webElementGuid>8c931993-ed8f-45cb-b39b-441c1d6d4009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_countryOfIssuance_F00I1MT_gs_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>d8f933bc-2377-4e85-acc8-860855ca6fc7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_countryOfIssuance_F00I1MT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>96619536-9367-478d-881b-797d96ca966d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_countryOfIssuance_F00I1MT']/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>f7f3c907-efa6-4331-af85-67aa96a978a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[3]/div[2]/div/table/thead/tr[2]/th[2]/div/input</value>
      <webElementGuid>a159598f-5e0d-46cb-bc20-28222722b560</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRIEF_DESC_ENG' and @id = 'gridtab_countryOfIssuance_F00I1MT_gs_BRIEF_DESC_ENG']</value>
      <webElementGuid>102f2faa-da85-452b-88f4-be6516030a28</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
