<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Way No_addressCO.ADDRESS3_ENG</name>
   <tag></tag>
   <elementGuidId>fab2c808-e5d5-4ea3-86c1-65abb57673a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_ADDRESS3_ENG_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressCO_ADDRESS3_ENG_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3eb54970-1759-466d-8c73-f033c9df88c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b9595d2d-f5eb-47c4-b457-f3fa5e94c2c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d80f48a4-ce92-4e1f-87fd-231792111178</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.ADDRESS3_ENG</value>
      <webElementGuid>edafe924-b40a-48f5-bf01-f8b347e8eeaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>f84c4bfc-58bb-4ea5-9a54-bb48dbaa7c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>32325799-f750-439d-a4e8-adbd20d1d39c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_ADDRESS3_ENG_F00I1MT</value>
      <webElementGuid>91ee660f-aa4a-43a7-a9b3-15e305e8ac1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_ADDRESS3_ENG_F00I1MT:fomCO.addressField</value>
      <webElementGuid>be2f2085-3273-4c57-9632-6e23ffba3021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>1616c430-f7bf-4bcd-960f-14e00867ec4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_ADDRESS3_ENG_F00I1MT</value>
      <webElementGuid>bebec6f1-8f33-46c1-bd15-0a1582a20da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Way No</value>
      <webElementGuid>dfcbb8fe-14ce-48bb-9cd2-ce9ece979ef1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Way No</value>
      <webElementGuid>1f32d4b6-bd54-40b9-88cd-fcbfa4d14a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Way No</value>
      <webElementGuid>6dc25ee3-2d61-4e3f-8d50-9eac432451ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_ADDRESS3_ENG_F00I1MT&quot;)</value>
      <webElementGuid>a9d5788e-bda0-4da5-8266-c21b1a633cea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_ADDRESS3_ENG_F00I1MT']</value>
      <webElementGuid>5f320cfa-8563-4f02-a0bc-df6bd7fb3ee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addressSectionTbl_Id_ENG_F00I1MT']/tbody/tr[7]/td[2]/input</value>
      <webElementGuid>e1bfa8bf-5e2b-4000-99e2-396ad831a203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/input</value>
      <webElementGuid>91621249-00bb-4111-8b0c-a3cdad6d5d50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.ADDRESS3_ENG' and @id = 'addressCO_ADDRESS3_ENG_F00I1MT' and @title = 'Way No']</value>
      <webElementGuid>18bb3065-c160-48a7-bbec-19efeca33396</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
