<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifVO.ID_TYPE</name>
   <tag></tag>
   <elementGuidId>dc1a5289-7c38-475f-a8cd-6abbc1110ce9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookuptxt_cifVO_ID_TYPE_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lookuptxt_cifVO_ID_TYPE_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7acf442-d24a-45f3-acf8-ee086dab4aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>078ecec7-3bfe-4491-be0b-06c77754cc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>ec0315a0-e9a3-436b-be6a-6077e0800c4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookuptxt_cifVO_ID_TYPE_F00I1MT</value>
      <webElementGuid>8a011bef-97b0-445a-8400-881e57f6ea37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>fomMaint_IdTypeAfterDep</value>
      <webElementGuid>17c96405-b1b3-4336-bddd-e64f6756cc3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input liveSearchText liveSearchCompSize ui-state-focus liveSearchInputCorner</value>
      <webElementGuid>7d8216e3-31a7-4e17-a88d-72cf01cf3419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.ID_TYPE</value>
      <webElementGuid>a11d155a-ccbc-468c-b817-68c051a37d66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>ID Type</value>
      <webElementGuid>b7389bf6-a177-4e97-b6ba-294937f7f00d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Id_Type_key</value>
      <webElementGuid>fbae0bda-224a-4c54-9cbf-49e9e63676c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>ea607ff5-f105-488e-8f74-60227c796226</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>12cb2690-136f-4db0-bc11-6d3409c60690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5c40bb87-b6a6-43fe-a569-f7550df6e041</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>a8548174-48b6-4e31-9794-f585b4b5a683</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>848f366d-6b48-488a-9b6b-4a72d1df9c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>relateddescelt</name>
      <type>Main</type>
      <value>fomCO_idTypeDesc_F00I1MT</value>
      <webElementGuid>5a334fb9-73dc-44dc-9008-32bfd9fd3122</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prevvalue</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>c933fcf0-5eb5-4a36-9720-ed6fa06c7c21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>ID Type</value>
      <webElementGuid>daf26094-0541-4ca6-8d2d-f594bcea22ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zeronotallowed</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e704926b-5656-437a-bd1f-99617658634a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>15300555-a880-4380-9088-b50958f315f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookuptxt_cifVO_ID_TYPE_F00I1MT&quot;)</value>
      <webElementGuid>c94d691a-2b65-4d69-967d-0d61c32cacef</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookuptxt_cifVO_ID_TYPE_F00I1MT']</value>
      <webElementGuid>e7be141d-dcfd-47ca-8b72-94e3117c3c83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lookupid_cifVO_ID_TYPE_F00I1MT']/div/input</value>
      <webElementGuid>3aa5354a-a8b3-415c-937b-e7216fa754f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr[2]/td/table/tbody/tr/td[2]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>ca61279b-d76c-4522-ac6c-2139223e231e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lookuptxt_cifVO_ID_TYPE_F00I1MT' and @name = 'fomCO.cifVO.ID_TYPE' and @title = 'ID Type']</value>
      <webElementGuid>f0a095ba-0191-4ff6-a81c-1e5cefb0a81e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
