<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Building Name  Number_addressCO.ADDRESS2_ENG</name>
   <tag></tag>
   <elementGuidId>afd32839-0af7-4e52-936b-f3c43493af27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_ADDRESS2_ENG_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressCO_ADDRESS2_ENG_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>96e66ef8-64c6-4973-a8d0-a2c29ba12ea3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d46da645-9736-40ca-b743-1a03b149a807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>812bbc88-13bc-457d-bc74-c3a93220f200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.ADDRESS2_ENG</value>
      <webElementGuid>a0bb9181-e9db-4166-aeaf-8daf28d66d02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>a6d27a97-30a0-4fd3-b213-b53f65aa4527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>87fb3162-34da-4b3b-9277-4874ddb2e3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_ADDRESS2_ENG_F00I1MT</value>
      <webElementGuid>40e53167-cc58-4273-9b42-2d077c5bda08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_ADDRESS2_ENG_F00I1MT:fomCO.addressField</value>
      <webElementGuid>df65f681-db72-430c-87a3-47f97b023737</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>ce74642f-1f7f-4be7-8071-fb6db03af823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_ADDRESS2_ENG_F00I1MT</value>
      <webElementGuid>94d4c7f3-9b33-4568-97e8-633d39a993a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Building Name / Number</value>
      <webElementGuid>2c24e1a0-b9e2-4680-8faf-f7ad54d43845</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Building Name / Number</value>
      <webElementGuid>0a6a4d5b-ea16-49bf-969a-f80298303f8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Building Name / Number</value>
      <webElementGuid>729bcd13-06b9-4e19-b9a2-8de0f73576cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_ADDRESS2_ENG_F00I1MT&quot;)</value>
      <webElementGuid>8e24815c-480c-4a8b-a7b6-3a185420ca10</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_ADDRESS2_ENG_F00I1MT']</value>
      <webElementGuid>0ab59637-990d-411e-b84e-344385fcd1a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addressSectionTbl_Id_ENG_F00I1MT']/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>280f4072-8bea-422b-adfe-92a93ad97259</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[6]/td[2]/input</value>
      <webElementGuid>01b5c6f3-0d8e-4c69-8e21-fa5626f0d09c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.ADDRESS2_ENG' and @id = 'addressCO_ADDRESS2_ENG_F00I1MT' and @title = 'Building Name / Number']</value>
      <webElementGuid>557663ae-a506-4a84-9045-4223cda0ae99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
