<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CONFIRM__popup_path_sol_confirm_ok</name>
   <tag></tag>
   <elementGuidId>37d9240f-0eff-4a0f-b0b7-eb38e403a676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_popup_path_sol_confirm_ok']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#_popup_path_sol_confirm_ok</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9c168709-31be-4584-a3c0-2fc5757f4f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5c6b15ac-c1b3-430e-9c47-a4202134f045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_popup_path_sol_confirm_ok</value>
      <webElementGuid>2db1043f-e18b-4529-bd09-7ff453877fa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fg-button ui-button ui-corner-all ui-button-text ui-widget ui-state-default ui-button-text-only</value>
      <webElementGuid>bcc82430-3994-4e76-a06d-4e209582d8dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok </value>
      <webElementGuid>3475ff6e-65c2-4b72-a72f-bc69b3b7708a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_popup_path_sol_confirm_ok&quot;)</value>
      <webElementGuid>dd1b208b-5010-48aa-a9e7-5e39ebc0c59e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_popup_path_sol_confirm_ok']</value>
      <webElementGuid>3f64709c-1b7a-434f-b265-13f1d16a5cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div__popup_path_sol_confirm']/center/input</value>
      <webElementGuid>c547326c-d852-4d7f-a0e1-011ab172e861</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/input</value>
      <webElementGuid>3735252c-4e10-424a-b9cc-674d0c734388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_popup_path_sol_confirm_ok']</value>
      <webElementGuid>6cde5e24-4d3c-437e-999b-9f6d3c44f28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
