<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifVO.CIF_TYPE</name>
   <tag></tag>
   <elementGuidId>4e0cb9eb-f3f4-4abf-ab14-2c8eab2110f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookuptxt_cifVO_CIF_TYPE_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lookuptxt_cifVO_CIF_TYPE_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>23612956-8018-4390-b50b-97cf3b681817</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd80fa3b-825f-4f2f-a392-a40a421e9624</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>cb5cd4c0-d1c7-499e-838a-ac0751418c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookuptxt_cifVO_CIF_TYPE_F00I1MT</value>
      <webElementGuid>231cc4c2-a596-49f7-b3db-77e35bd7d669</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>afterdepevent</name>
      <type>Main</type>
      <value>fomMaint_cifTypeAfterDep</value>
      <webElementGuid>741827be-a5c7-48d6-b573-8bba7cd99360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input liveSearchText liveSearchCompSize ui-state-focus liveSearchInputCorner</value>
      <webElementGuid>2051e960-6919-4007-b29f-ff1e43de8e62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.CIF_TYPE</value>
      <webElementGuid>0ad2cbd0-e2e2-4686-849e-287a984eec33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>68ed4311-182a-404c-b70d-59d0a73404de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>ad826a93-8b0e-4167-a741-5c266e648750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>71d512dd-81e6-4a6d-a094-1ec6eabe2d99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>08f8f3d2-60cf-4c54-b641-05735f5f0185</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>59b0c794-0465-4a21-a9a3-8558b4c28660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>95f6ffd2-2308-4c1e-a7a3-9c879d413f89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>relateddescelt</name>
      <type>Main</type>
      <value>fomCO_cifTypeDesc_F00I1MT</value>
      <webElementGuid>a87d7b9a-39e0-47ee-a4ed-97f2eca7e867</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookuptxt_cifVO_CIF_TYPE_F00I1MT&quot;)</value>
      <webElementGuid>b57d1b1b-de8a-45af-a4ba-0cbeb7a4a0f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookuptxt_cifVO_CIF_TYPE_F00I1MT']</value>
      <webElementGuid>196087c6-48bf-4c01-a8b8-f372e38b10c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lookupid_cifVO_CIF_TYPE_F00I1MT']/div/input</value>
      <webElementGuid>27372d61-ded9-4e28-af34-a62aecc9e540</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/table/tbody/tr/td[2]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>410f4d6e-3817-45e6-adeb-f45d493622ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lookuptxt_cifVO_CIF_TYPE_F00I1MT' and @name = 'fomCO.cifVO.CIF_TYPE']</value>
      <webElementGuid>a352de12-a77e-4ecf-a542-8b38b0dce69c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
