<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifExtendedVO.COUNTRY_OF_ISSUANCE</name>
   <tag></tag>
   <elementGuidId>e172652e-0fb5-408d-a14e-c2175242513b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='lookuptxt_countryOfIssuance_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lookuptxt_countryOfIssuance_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a8aa93e-fc51-464b-8aed-02b90564069e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>380e0d36-12f1-4f1d-a4f6-c0c6d04a0fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>57ed0414-0d05-4a37-b9be-31ec44b41335</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lookuptxt_countryOfIssuance_F00I1MT</value>
      <webElementGuid>53351f18-d8dc-49c2-8a65-1f577dd08a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input liveSearchText liveSearchCompSize ui-state-focus liveSearchInputCorner</value>
      <webElementGuid>ba18b0a8-e1a3-49d1-9dc7-9b0449da3ac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifExtendedVO.COUNTRY_OF_ISSUANCE</value>
      <webElementGuid>ecc817a6-abed-4546-b8bf-d4a829ec5888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a809bff2-1d6a-4821-9b96-56921b769d76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a4950702-a45f-4e95-bd9b-f7aa93338e19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>6fee1ffd-d7d1-40c0-bf15-23a62a403760</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>minvalue</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>4658aa6d-02a9-4410-a0eb-5296b7e4ff66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>relateddescelt</name>
      <type>Main</type>
      <value>countryOfIssuanceDesc_F00I1MT</value>
      <webElementGuid>c66f4abe-e58b-4e37-a56b-5a776eb0fb78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>4422e566-567f-4b8a-979d-7e1caa91b24f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lookuptxt_countryOfIssuance_F00I1MT&quot;)</value>
      <webElementGuid>2958d1b7-0910-4e22-aee0-48d91159c123</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='lookuptxt_countryOfIssuance_F00I1MT']</value>
      <webElementGuid>0a2c5e52-ddf2-49d9-b97b-43e0b3a0edac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='lookupid_countryOfIssuance_F00I1MT']/div/input</value>
      <webElementGuid>8da1c56a-c6e1-4214-829c-0cbabb1b4ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[7]/div/table/tbody/tr/td/div/div/input</value>
      <webElementGuid>1e2f33c6-35f7-4c88-8437-ea7ae0039941</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'lookuptxt_countryOfIssuance_F00I1MT' and @name = 'fomCO.cifExtendedVO.COUNTRY_OF_ISSUANCE']</value>
      <webElementGuid>e44b8bbf-a4cc-4026-a8d8-299183248ef5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
