<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_House No  Flat No_addressCO.ADDRESS1_ENG</name>
   <tag></tag>
   <elementGuidId>b6672e7b-f4b9-49e0-8604-22fa9ffa7834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_ADDRESS1_ENG_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressCO_ADDRESS1_ENG_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>756edb92-6922-4f75-a77c-ef6ff2eeb6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>05b67359-19e2-4e40-98a7-519c9e6a393c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>9e425c3a-a838-4b31-bcd0-5810152d6408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.ADDRESS1_ENG</value>
      <webElementGuid>83353221-0390-464a-af14-929f3bfdd1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>f372ed6f-6ee4-4d4e-83c6-72a83abf61de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>f56bb446-c05a-4874-829f-129800017f99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_ADDRESS1_ENG_F00I1MT</value>
      <webElementGuid>53408f66-4480-45c3-bca2-80a77669d4e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_ADDRESS1_ENG_F00I1MT:fomCO.addressField</value>
      <webElementGuid>6c456a51-befb-4e79-ba3b-3be5d4eb0f53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>3b630c4f-7674-40ce-a2f2-abcc72a8babf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_ADDRESS1_ENG_F00I1MT</value>
      <webElementGuid>658e3056-8f6d-4b62-9b95-f13234c0ebec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>House No / Flat No</value>
      <webElementGuid>1af8571b-bc4d-4423-b6dc-6b8efcba074b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>House No / Flat No</value>
      <webElementGuid>2fd733fe-b58e-4796-94b4-1a1d4ce5b001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>House No / Flat No</value>
      <webElementGuid>0d97fe97-402f-4c22-8328-ff5b8f01af8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_ADDRESS1_ENG_F00I1MT&quot;)</value>
      <webElementGuid>887e73d0-9837-4a71-88c7-0d3ff2dc5b44</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_ADDRESS1_ENG_F00I1MT']</value>
      <webElementGuid>d1a95115-7f0b-4ffc-91b0-55c76b9601bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addressSectionTbl_Id_ENG_F00I1MT']/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>66a26fdb-31bb-4c64-b50b-9bfc6c904865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>239ee452-cfa0-48ee-8a43-79602247d445</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.ADDRESS1_ENG' and @id = 'addressCO_ADDRESS1_ENG_F00I1MT' and @title = 'House No / Flat No']</value>
      <webElementGuid>a326d114-f2e2-49d8-8c0e-958dfd230330</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
