<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Short Name_fomCO.cifVO.SHORT_NAME_ENG</name>
   <tag></tag>
   <elementGuidId>26eb126a-3f70-4ec1-8210-c1f7c19ec2d6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifVO_SHORT_NAME_ENG_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cifVO_SHORT_NAME_ENG_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d308d3e1-8c05-4e0f-8553-cc3b718805e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a55a48eb-dd50-40a5-9df8-bb6c8f75ef2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>7ca9f29b-112d-4c79-9e48-b1fe00a14952</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.SHORT_NAME_ENG</value>
      <webElementGuid>6aafdc72-64c4-4f9d-9c2c-6849d680123d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>fc99ba72-a86e-4796-9857-876c7bb7646d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>7f49f1ca-fb87-4b9a-bda3-b0bd13dfb3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_SHORT_NAME_ENG_F00I1MT</value>
      <webElementGuid>5bd9b1a3-3d12-4dc3-a6f0-2f6467f700f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>fomNameAddressTabBriefName_onChange();</value>
      <webElementGuid>35c0c259-287e-4ef0-9c05-663285133dfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Short Name</value>
      <webElementGuid>54113d27-69f3-4e86-a336-177f16bbae72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Short_name_eng_key</value>
      <webElementGuid>ff10aaf0-a6c2-4ca6-a64d-a085d98f5cb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Short Name</value>
      <webElementGuid>0f9ef4be-b43d-4e8a-8356-9b8b5de07b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_SHORT_NAME_ENG_F00I1MT&quot;)</value>
      <webElementGuid>5b8b210c-93cb-41c0-a1cc-15fbc2cc06ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifVO_SHORT_NAME_ENG_F00I1MT']</value>
      <webElementGuid>05110b74-dcf4-44b8-8423-981f0f68b498</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel2']/div[3]/table/tbody/tr[3]/td[2]/input[2]</value>
      <webElementGuid>e7b3b6e8-e463-49bd-bca9-15f759e9f380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td[2]/input[2]</value>
      <webElementGuid>1ac4a672-140b-4e05-a481-69b924a566ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifVO.SHORT_NAME_ENG' and @id = 'cifVO_SHORT_NAME_ENG_F00I1MT' and @title = 'Short Name']</value>
      <webElementGuid>53a6a132-e0c3-4181-a7e1-00183642baa8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
