<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile No (2)_addressCO.OTHER_TEL</name>
   <tag></tag>
   <elementGuidId>3e462ce8-8ec4-4cd1-b6c8-1bde21990214</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_OTHER_TEL_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressCO_OTHER_TEL_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>45b00837-e186-4eca-acc1-1591df10d595</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40cd67fc-5dec-4d94-8c37-0eccffa588f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e635ebb5-0b74-49db-8fad-558cd30e918f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.OTHER_TEL</value>
      <webElementGuid>577a64b8-877e-49f3-bd2e-574cf6bb366a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>8a56d248-8261-476f-b076-f2a02e59bf97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>59e83371-46f3-410d-a57d-370b162c2c4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_OTHER_TEL_F00I1MT</value>
      <webElementGuid>41d42b95-dce3-4582-acec-43ab4400afaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_OTHER_TEL_F00I1MT:fomCO.addressField</value>
      <webElementGuid>1d6005d3-ce83-48aa-9184-1b76dc22c6d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>3e186c18-5743-40be-a622-ef0dddb63999</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_OTHER_TEL_F00I1MT</value>
      <webElementGuid>c794a8c3-2f6c-4d88-a58d-01c589b75105</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Mobile No (2)</value>
      <webElementGuid>daebf444-7315-473d-afe0-4e4d4c56b734</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Mobile No (2)</value>
      <webElementGuid>a8b7d746-713f-492c-ab23-fa42288736f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>8ab41b72-c6b2-4fd6-9a34-712edc664c20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mobile No (2)</value>
      <webElementGuid>33303f2b-5d0c-4d90-bbbf-457da3fc9465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_OTHER_TEL_F00I1MT&quot;)</value>
      <webElementGuid>3bee28e7-655a-447e-9a86-c9b55d3c5789</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_OTHER_TEL_F00I1MT']</value>
      <webElementGuid>255e5ddd-5ec2-4c3c-a160-f7de24ac1708</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addrTbl_F00I1MT']/tbody/tr[3]/td[2]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>c4e189ae-f4e2-41ce-a8d0-b9b1e3c86788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[5]/td[2]/input</value>
      <webElementGuid>4d4bafd7-1ac0-4c97-89be-55a59bdb9779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.OTHER_TEL' and @id = 'addressCO_OTHER_TEL_F00I1MT' and @title = 'Mobile No (2)']</value>
      <webElementGuid>8ab6c706-e743-4bd8-9153-d1712450c52c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
