<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Phone No Res_addressCO.TEL</name>
   <tag></tag>
   <elementGuidId>d2c9e42a-e9d9-468f-bd19-ba4962dde3fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_TEL_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressCO_TEL_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>519d54ac-ca7d-4fc6-84ea-60a759dc4ef0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>faec8b76-125e-4cfb-bcbf-aa7f0ec32823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c8fc7968-8a3c-4c98-9ce3-81b99fec1831</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.TEL</value>
      <webElementGuid>63eb132e-26f0-49e9-917f-21faa72802e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>78f2d30d-9682-4370-9470-f8acfb858c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>8f1189f1-c7db-4c7f-b73b-80a29a6201de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_TEL_F00I1MT</value>
      <webElementGuid>cd24f56f-ffb9-4c80-969d-0c5c1a19d056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>eb62ce0d-2b72-4fd8-bf8c-1aaa29fcbd17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_TEL_F00I1MT:fomCO.addressField</value>
      <webElementGuid>a7a04095-1374-43fa-8886-3114c9f4629e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>af4bd742-e10c-4e5d-9cab-115b3cdcba54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_TEL_F00I1MT</value>
      <webElementGuid>38532b94-95ac-42f2-af3b-eaef6432a5aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Phone No Res.</value>
      <webElementGuid>d725288b-ffca-4ae2-ba15-151962c8fc54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Phone No Res.</value>
      <webElementGuid>c294531f-4e9a-4013-9253-b003cb18ee6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>462b34d9-0c8b-4c11-82e4-3a82b179b8af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Phone No Res.</value>
      <webElementGuid>db753ee5-0720-4d79-917e-3323aa7b107c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_TEL_F00I1MT&quot;)</value>
      <webElementGuid>51509fea-0cde-4eec-ba2e-4da273d8bd41</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_TEL_F00I1MT']</value>
      <webElementGuid>70c445e6-ea09-453b-ba31-f5d41461b4ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addrTbl_F00I1MT']/tbody/tr[3]/td[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>977c7afa-80a9-4e72-859c-d00cc3cd62fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[2]/td[2]/input</value>
      <webElementGuid>17a2b105-b3d2-49c2-93ff-d6632ba0a5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.TEL' and @id = 'addressCO_TEL_F00I1MT' and @title = 'Phone No Res.']</value>
      <webElementGuid>e15b2ef2-86af-4ec2-a3c5-9c63e3015ebd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
