<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__fomCO.cifVO.BIRTH_DATE</name>
   <tag></tag>
   <elementGuidId>1231cd41-b01f-4a80-9b6f-0cf99443b51e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cifVO_BIRTH_DATE_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cifVO_BIRTH_DATE_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f4632d53-beb9-4b3b-b2b3-c57ac5a13d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7a3a473b-793d-4cf8-a826-e2d4aecd2ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f8bbf63a-0e5e-4635-9d43-503b7faf672a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.BIRTH_DATE</value>
      <webElementGuid>076b9e13-ac1f-4b2c-91d3-3ceeae35e43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>12px</value>
      <webElementGuid>cc61edd6-67de-41f0-bbc8-d0bb9eeed879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input ui-state-focus ui-corner-all path-text-size hasDatepicker</value>
      <webElementGuid>0d045497-60af-415c-8dbc-42958f298e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_BIRTH_DATE_F00I1MT</value>
      <webElementGuid>1b30b90f-6eb6-4e2e-973b-2e66a8a98815</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>cifVO_BIRTH_DATE_F00I1MT:fomCO.cifVO.BIRTH_DATE</value>
      <webElementGuid>f9b0fe37-2ca7-4fd7-a0a8-ec28722a25da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateBirthDate</value>
      <webElementGuid>576865e4-7524-4dcc-affe-b278d883ee13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.cifVO.BIRTH_DATE:cifVO_BIRTH_DATE_F00I1MT,fomCO.cifVO.ID_DELIVERY_DATE:cifVO_ID_DELIVERY_DATE_F00I1MT,fomCO.cifVO.TYPE:cifVO_TYPE_F00I1MT,fomCO.cifVO.CIF_TYPE:lookuptxt_cifVO_CIF_TYPE_F00I1MT</value>
      <webElementGuid>98268edd-32ee-45b8-8e8e-55addad823df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>eb745751-c406-43b1-8f21-2a89476da6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Date_of_Birth_key</value>
      <webElementGuid>54b8900a-8e7a-4efc-952d-07cd498ba251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Date of Birth</value>
      <webElementGuid>ba26f173-db60-4d0f-a8b0-c4b6a5973bbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>a3382856-f104-4239-97dd-251fba33c10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_BIRTH_DATE_F00I1MT&quot;)</value>
      <webElementGuid>749c9ff3-74a6-4557-9866-5ecdea1839c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cifVO_BIRTH_DATE_F00I1MT']</value>
      <webElementGuid>221224f2-f5c3-4042-aa0c-f38896438bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel1']/div[3]/table/tbody/tr[6]/td[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>7f6ecf95-11c3-4b15-8c04-5abbadfcaa0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/div/table/tbody/tr/td[2]/input</value>
      <webElementGuid>cc0a7a3f-1934-4c94-9589-ab50f665876a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'fomCO.cifVO.BIRTH_DATE' and @id = 'cifVO_BIRTH_DATE_F00I1MT' and @title = 'Date of Birth']</value>
      <webElementGuid>fdcba98e-40b9-4d52-91c8-5bf625bd4e0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
