<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Mobile No (1)_addressCO.MOBILE</name>
   <tag></tag>
   <elementGuidId>32bd349d-7d99-4571-9301-ae7ff598def2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='addressCO_MOBILE_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressCO_MOBILE_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7fd6cdf6-4af2-4fb6-9744-2dc09ccb8e81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>50172652-8f31-46f0-a3e6-3ff34c3406a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>1cfe0281-07d9-4f80-8f91-0746f01e31b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.MOBILE</value>
      <webElementGuid>06844d80-af6a-470d-a5bb-28f041b5ab47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>84b436db-cdfb-4ee6-a7af-f8f35bdab9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>19</value>
      <webElementGuid>fd8d41b8-3482-4508-ba51-eba89c8d1ed4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_MOBILE_F00I1MT</value>
      <webElementGuid>a16f9eff-b326-409b-8bc7-d2794c5e6f9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>mode</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>01d5a8b7-7647-45e0-8cae-edb100eb3524</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>nbformat</name>
      <type>Main</type>
      <value>###</value>
      <webElementGuid>aa97e3c5-ddb1-4916-a324-fcf1b276ea9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>noformat</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>a2dcf898-7719-4e0d-a1a7-4beff1c8999f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>zeronotallowed</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d5d58485-140a-44cc-b324-21a979d01c24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decimalsepa</name>
      <type>Main</type>
      <value>.</value>
      <webElementGuid>1465f22c-631c-4d98-888d-d419733fbe5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>groupsepa</name>
      <type>Main</type>
      <value>,</value>
      <webElementGuid>c8cacdea-fbdd-481c-8010-c30a7948e3ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_MOBILE_F00I1MT:fomCO.addressField</value>
      <webElementGuid>a515c983-ee0d-4acf-9bd1-f8305a2b8884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>25b4ad47-2651-43bb-80e6-1c8a75285b38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_MOBILE_F00I1MT</value>
      <webElementGuid>10efb13b-4048-42e5-b9f0-e5f1f4d97099</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Mobile No (1)</value>
      <webElementGuid>5a860192-a863-462d-908b-815f3eb02108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Mobile No (1)</value>
      <webElementGuid>0a4cda42-9fd8-4541-8df1-e1b1b83cbdb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dir</name>
      <type>Main</type>
      <value>ltr</value>
      <webElementGuid>d350a3b4-5a44-4d1f-8164-a69aa089c771</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Mobile No (1)</value>
      <webElementGuid>bd527c30-9dec-4a7c-8ffe-5c6f61943889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_MOBILE_F00I1MT&quot;)</value>
      <webElementGuid>3b976797-a638-4a50-b286-419398aba444</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='addressCO_MOBILE_F00I1MT']</value>
      <webElementGuid>cc3f95c0-12d0-48f4-be02-828847e63603</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addrTbl_F00I1MT']/tbody/tr[3]/td[2]/table/tbody/tr[4]/td[2]/div/input</value>
      <webElementGuid>24e0db1c-dad5-4219-a88a-67b92e1eca5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/table/tbody/tr[4]/td[2]/div/input</value>
      <webElementGuid>02b31a84-daef-4e1f-957a-6f6de573b1f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'addressCO.MOBILE' and @id = 'addressCO_MOBILE_F00I1MT' and @title = 'Mobile No (1)']</value>
      <webElementGuid>34cee99f-ce95-4433-8118-cf335a1753a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
