<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_OK</name>
   <tag></tag>
   <elementGuidId>b39f84db-f766-4225-a7ff-7091233812ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='ok_F00I1MT']/span/label</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ok_F00I1MT > span.ui-button-text > label.path_btn_lbl_theme</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>df3dbcd9-2620-424e-8778-e577b674e414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>ok_F00I1MT</value>
      <webElementGuid>059d7c4f-b483-421c-8ad9-e6cb9150883e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>fc30571f-2157-443d-8fa8-f4c3df132688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK </value>
      <webElementGuid>202768f7-c46a-43de-8870-a22c34d1d414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ok_F00I1MT&quot;)/span[@class=&quot;ui-button-text&quot;]/label[@class=&quot;path_btn_lbl_theme&quot;]</value>
      <webElementGuid>41789c9a-93a3-4970-856c-f544802a88a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='ok_F00I1MT']/span/label</value>
      <webElementGuid>06b3c2be-3bd9-4230-998a-00cd87787dae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you a Close Business Associate with a politically exposed person (PEP)?'])[1]/following::label[1]</value>
      <webElementGuid>9da6bb60-1b14-4be3-9e3c-d3c26cb682b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Please Specify'])[1]/following::label[2]</value>
      <webElementGuid>89570fce-3244-43d4-9b56-4070f9eab057</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::label[1]</value>
      <webElementGuid>e1ae0974-d31f-42a4-9142-c872f63955f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OK']/parent::*</value>
      <webElementGuid>288cf811-f885-4f74-9228-4282238343ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button/span/label</value>
      <webElementGuid>4afa6d9e-f7d7-4d59-ab11-a7b2f81f03be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'OK ' or . = 'OK ')]</value>
      <webElementGuid>ff1dc682-504c-4c98-9426-99b3859097a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
