<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Save</name>
   <tag></tag>
   <elementGuidId>ed85038e-ac4a-4d2e-a323-d8b2768559a8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='fomMaintForm_F00I1MT_Save_key']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fomMaintForm_F00I1MT_Save_key</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>1aaa7377-fce6-459a-8bda-9d34b6b4c156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fomMaintForm_F00I1MT_Save_key</value>
      <webElementGuid>3c932de8-18cc-4afd-a5f7-bcb5e1314c6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>fom_Save_btn_F00I1MT</value>
      <webElementGuid>d8161680-88b5-473b-bbb7-e1ff6ba95e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>Save_key</value>
      <webElementGuid>96f5bc46-58e4-4e88-b785-7f6629f12843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>f16ca079-5feb-4049-be26-afa5696afacf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save </value>
      <webElementGuid>c7d1fa98-4687-4ac0-b255-1f783e259392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomMaintForm_F00I1MT_Save_key&quot;)</value>
      <webElementGuid>beab47b3-fed4-46ad-af4a-62eed72c2214</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='fomMaintForm_F00I1MT_Save_key']</value>
      <webElementGuid>93d61b78-4e16-4236-a93a-5ffa1c80bd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fom_Save_btn_F00I1MT']/span[2]/label</value>
      <webElementGuid>72405254-07d8-40e1-be43-14d75ca4d5c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Fields'])[2]/following::label[1]</value>
      <webElementGuid>637eab77-2184-4ad9-82c8-2127183efecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Team'])[1]/following::label[2]</value>
      <webElementGuid>4576a124-d082-4662-8ea6-7ca1530c257e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Copyright'])[1]/preceding::label[1]</value>
      <webElementGuid>fc7ee10a-9c54-4493-8608-795010401357</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Save']/parent::*</value>
      <webElementGuid>cc9b1726-5ae3-42a4-b3e8-aa9c124d06fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button/span[2]/label</value>
      <webElementGuid>607c9294-7a55-4497-b4a5-9666f00ccef1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'fomMaintForm_F00I1MT_Save_key' and (text() = 'Save ' or . = 'Save ')]</value>
      <webElementGuid>d09cecb8-bf97-4ecc-8d49-f84c7fb50c4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
