<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Validate</name>
   <tag></tag>
   <elementGuidId>4f82505e-3a5c-4acb-a5a8-4557f0919853</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='fomMaintForm_F00I1MT_Validate_key']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#fomMaintForm_F00I1MT_Validate_key</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>3c02d521-28a8-4a02-895d-76ec6911c5bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>fomMaintForm_F00I1MT_Validate_key</value>
      <webElementGuid>0204cc2d-e242-4e65-a10c-36c8b9d49566</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>fom_Validate_btn_F00I1MT</value>
      <webElementGuid>02589f12-beb7-4d9b-a8df-39cdd5fdbf51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>Validate_key</value>
      <webElementGuid>6a27e39e-4ed5-44bf-b6eb-e615782e78ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>40dc9916-9524-4484-b334-16b0bb304f70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Validate </value>
      <webElementGuid>6d7295ff-5eb9-47e7-bfe4-859d3fc879a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;fomMaintForm_F00I1MT_Validate_key&quot;)</value>
      <webElementGuid>4ed0f5d3-0a42-45c5-be33-7785619d7bb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='fomMaintForm_F00I1MT_Validate_key']</value>
      <webElementGuid>01e9f0be-c353-4004-a7a4-71051a27f870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='fom_Validate_btn_F00I1MT']/span[2]/label</value>
      <webElementGuid>eb020160-0b2d-4a6f-af4e-a60a14277179</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::label[1]</value>
      <webElementGuid>3167df7c-feb3-40d8-965c-bf2bcb6ebc7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Fields'])[3]/following::label[2]</value>
      <webElementGuid>63754ebc-4b42-411e-bde8-617e1120df09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='check_out_key'])[1]/preceding::label[1]</value>
      <webElementGuid>acbe30f3-428f-4f85-8757-8e1c24f04533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Validate']/parent::*</value>
      <webElementGuid>40c509b3-a445-491e-8034-aab18783fc47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span[2]/label</value>
      <webElementGuid>e347602b-395d-4607-ba0b-968ceb645196</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'fomMaintForm_F00I1MT_Validate_key' and (text() = 'Validate ' or . = 'Validate ')]</value>
      <webElementGuid>f7d2f227-f2c5-47ca-afbb-0f8e56fb8683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
