<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SingleDivorcedWidowedMarriedUnknown</name>
   <tag></tag>
   <elementGuidId>4c56abdd-edfa-44a4-9773-96158443a725</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cifVO_MARITAL_STATUS_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cifVO_MARITAL_STATUS_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>be87529f-cd98-4888-a3ea-59d6bbf3efe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.MARITAL_STATUS</value>
      <webElementGuid>8419b9b0-d761-44fa-8f05-e26b2802db18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>e454dd9a-6931-4332-8092-32d33a68ca09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_MARITAL_STATUS_F00I1MT</value>
      <webElementGuid>76181e6d-d390-4e39-a592-2a559077f847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listkey</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>343b0f6b-72a7-412e-be27-431ec744aaf0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listvalue</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>e5832545-bed2-486f-a196-315f90802173</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>initialvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>25ccf71c-853a-46f3-afdf-93a6f8e0288c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>prevvalue</name>
      <type>Main</type>
      <value>N</value>
      <webElementGuid>c18a3863-d5ad-418f-8834-96f16d820303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Marital Status</value>
      <webElementGuid>88a8b72a-17f4-4edc-8f8b-ac25cd99d8d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Marital_Status_key</value>
      <webElementGuid>d135b57e-be17-4fef-a88f-9c97324925e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Marital Status</value>
      <webElementGuid>7ba25003-bca0-4dc6-875e-1ca3a7322315</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>345792eb-56f0-4067-8978-0ddc7efa2e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SingleDivorcedWidowedMarriedUnknown</value>
      <webElementGuid>d7a51597-2f4e-4844-a680-2fc8554cacd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_MARITAL_STATUS_F00I1MT&quot;)</value>
      <webElementGuid>c0633ed1-ab1f-472e-8775-43c5298cae2a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cifVO_MARITAL_STATUS_F00I1MT']</value>
      <webElementGuid>d9a99145-c378-4906-bb0a-2896970b9680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel1']/div[3]/table/tbody/tr[9]/td[3]/select</value>
      <webElementGuid>687effde-a1d5-4605-8799-322fcdedde62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[6]/following::select[1]</value>
      <webElementGuid>a19a326b-0cf7-4e8d-9b5d-5ae1352dc12c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/preceding::select[1]</value>
      <webElementGuid>0222e124-2906-499a-9e2b-16913fc99867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/select</value>
      <webElementGuid>4aabf10f-dde1-426f-871f-4d5b9e0d2dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fomCO.cifVO.MARITAL_STATUS' and @id = 'cifVO_MARITAL_STATUS_F00I1MT' and @title = 'Marital Status' and (text() = 'SingleDivorcedWidowedMarriedUnknown' or . = 'SingleDivorcedWidowedMarriedUnknown')]</value>
      <webElementGuid>2ce31e6b-c68c-40ba-ad1a-abec61f16c2f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
