<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo</name>
   <tag></tag>
   <elementGuidId>335e0326-d784-4ae9-a048-b467d41874c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='us_acc_holder_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#us_acc_holder_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2f3e3321-03a8-4255-86ed-73c6e5407f63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>us_acc_holder</value>
      <webElementGuid>6305e4aa-29f8-4718-8e7b-8cb9c96e3acc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>d2385ed2-4a9e-41a5-865b-13b1225caa7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>us_acc_holder_F00I1MT</value>
      <webElementGuid>bd4a8d0b-e213-440b-9add-be542aa7f3ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listkey</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>2d902500-b837-4603-a404-14998dea10f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listvalue</name>
      <type>Main</type>
      <value>descValue</value>
      <webElementGuid>f9111eb9-a700-4a6d-8562-8b3b4f805ac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>042aee1e-7d11-4ed2-8da0-129898ecb283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>callDependency(&quot;us_acc_holder_F00I1MT:criteria.elemHm.us_acc_holder&quot;,&quot;/imal_core_portal/path/dynamicScreen/dynDependencyAction_dynDependenciesProcess?&quot;,&quot;screenId:~CONST_4,elementId:~CONST_us_acc_holder,criteria.elemHm.us_acc_holder:us_acc_holder_F00I1MT,criteria.elemHm.dyn_cif_type:dyn_cif_type_F00I1MT&quot;,&quot;us_acc_holder_F00I1MT&quot;,&quot;&quot;)</value>
      <webElementGuid>37603a59-3c71-42b0-90f7-d1955dad0163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>us_acc_holder_F00I1MT:criteria.elemHm.us_acc_holder</value>
      <webElementGuid>98ea3190-fd03-4f3d-8c07-00ec1c40ed91</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/dynamicScreen/dynDependencyAction_dynDependenciesProcess?</value>
      <webElementGuid>08324c8f-04db-49f2-9f38-7baf5658eb95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>screenId:~CONST_4,elementId:~CONST_us_acc_holder,criteria.elemHm.us_acc_holder:us_acc_holder_F00I1MT,criteria.elemHm.dyn_cif_type:dyn_cif_type_F00I1MT</value>
      <webElementGuid>5307a19d-a1aa-4f5d-92cf-e809e0fdecd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>9cb1fd50-0ce1-4aab-9b6e-7f59b7e888b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;us_acc_holder_F00I1MT&quot;)</value>
      <webElementGuid>19d204d3-1e8a-4fc5-968e-73256d98977c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='us_acc_holder_F00I1MT']</value>
      <webElementGuid>52365285-2248-4247-a026-4d5679473de8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dynScreen_4_FormId_F00I1MT_DivId']/select[4]</value>
      <webElementGuid>189210de-0af4-4fa0-bc4c-206bc6c01fdf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::select[1]</value>
      <webElementGuid>9bfa4bc3-4eba-4a48-9951-ee3b033af9ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::select[1]</value>
      <webElementGuid>007eb95c-d7d4-41d7-a197-7c67b892036e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[4]</value>
      <webElementGuid>0a6c8b8c-f790-450a-a8cf-7622d736c251</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'us_acc_holder' and @id = 'us_acc_holder_F00I1MT' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>702fea80-8085-48a2-af7d-0f5e5e8f3111</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
