<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_YesNo_1</name>
   <tag></tag>
   <elementGuidId>aebb3cfc-a2f7-4537-a7c8-5033b24400a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='pep_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pep_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>abd2717d-26b7-47c9-ac5a-bc83c3fc2e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>pep</value>
      <webElementGuid>ec3ef16b-3605-4e08-b23a-1bec0a7306ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>a4231b64-b8b3-46f6-9fbe-a84354768ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pep_F00I1MT</value>
      <webElementGuid>e767b1c9-c351-482c-982a-f78e6245eca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listkey</name>
      <type>Main</type>
      <value>code</value>
      <webElementGuid>3180b861-e600-4164-b715-84702dc33578</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listvalue</name>
      <type>Main</type>
      <value>descValue</value>
      <webElementGuid>afdfa73d-91f6-49a1-b43b-d7bf9540c626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>404bf089-7a58-47af-91e8-29915f696db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>callDependency(&quot;pep_F00I1MT:criteria.elemHm.pep&quot;,&quot;/imal_core_portal/path/dynamicScreen/dynDependencyAction_dynDependenciesProcess?&quot;,&quot;screenId:~CONST_2,elementId:~CONST_pep,criteria.elemHm.pep:pep_F00I1MT,criteria.elemHm.politically_exposed:politically_exposed_F00I1MT,criteria.elemHm.salutation:salutation_F00I1MT,criteria.elemHm.related_politically:related_politically_F00I1MT,criteria.elemHm.relativity:relativity_F00I1MT&quot;,&quot;pep_F00I1MT&quot;,&quot;&quot;)</value>
      <webElementGuid>81c57b17-b9e5-495a-9342-031a699dc32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>pep_F00I1MT:criteria.elemHm.pep</value>
      <webElementGuid>15e791af-ac02-46c9-b333-d2f3785f5de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/dynamicScreen/dynDependencyAction_dynDependenciesProcess?</value>
      <webElementGuid>8dbdf8f0-9152-4fd6-be35-c9df702df5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameters</name>
      <type>Main</type>
      <value>screenId:~CONST_2,elementId:~CONST_pep,criteria.elemHm.pep:pep_F00I1MT,criteria.elemHm.politically_exposed:politically_exposed_F00I1MT,criteria.elemHm.salutation:salutation_F00I1MT,criteria.elemHm.related_politically:related_politically_F00I1MT,criteria.elemHm.relativity:relativity_F00I1MT</value>
      <webElementGuid>fdcb0633-3cd0-497b-9b8d-bc15ad41f291</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>YesNo</value>
      <webElementGuid>0e1df5e1-acdc-442e-9486-33dee37dfbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pep_F00I1MT&quot;)</value>
      <webElementGuid>0e2ee665-954b-4cdf-aef1-7fdb9ffc8c82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='pep_F00I1MT']</value>
      <webElementGuid>1fdc238c-21b0-477b-9c00-b60bdef8d36f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dynScreen_2_FormId_F00I1MT_DivId']/select[3]</value>
      <webElementGuid>048f26ae-bbb9-45bf-81d1-e673c33be734</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/following::select[1]</value>
      <webElementGuid>4fea8783-16b4-419b-b8b1-22bd91dccf46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/following::select[1]</value>
      <webElementGuid>17e432cb-40a9-452f-b7f3-fddb5bfceb62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[3]</value>
      <webElementGuid>c6de1c7c-90d0-44d4-b482-8e672df79a02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'pep' and @id = 'pep_F00I1MT' and (text() = 'YesNo' or . = 'YesNo')]</value>
      <webElementGuid>6a82a176-777a-4d60-be95-36ccf72034fd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
