<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FemaleMaleNA</name>
   <tag></tag>
   <elementGuidId>8055d7c8-40e6-4267-9226-2b3823c3a739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cifVO_SEXE_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cifVO_SEXE_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6b27d0bb-d6a9-4411-b71f-aafef7a204a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>fomCO.cifVO.SEXE</value>
      <webElementGuid>d918cb98-dc77-4c8a-b798-9c5fe4839b7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>selectCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>c018a624-05da-4ec5-9bd1-f05689970c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cifVO_SEXE_F00I1MT</value>
      <webElementGuid>0f3c77d6-fffa-4085-9b4f-2acc4d7458f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listkey</name>
      <type>Main</type>
      <value>key</value>
      <webElementGuid>0b2f4000-ec67-41f8-8285-80b627a5bcb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>listvalue</name>
      <type>Main</type>
      <value>value</value>
      <webElementGuid>2a96e2c4-fb25-4831-880e-1b736046676b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>initialvalue</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>1be356ef-843a-425a-961e-7afe968a02d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>02cacbf5-6fb9-4569-a4f6-04ee559634e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Gender_key</value>
      <webElementGuid>6889b450-baca-46b0-8ad9-b074627653cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Gender</value>
      <webElementGuid>0249a43f-05f4-4376-b25b-d295c1d491e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>e44da5cb-6c8d-43ba-8432-222c9f742fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FemaleMaleN/A</value>
      <webElementGuid>50af730c-bb99-4fb7-b900-5ca667ca13e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cifVO_SEXE_F00I1MT&quot;)</value>
      <webElementGuid>74ac15ef-e593-4a4b-ad9e-14c2b0fc0b09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cifVO_SEXE_F00I1MT']</value>
      <webElementGuid>4cdff3c8-6b76-4945-8eaf-5746021ad768</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='MarketedByTabInfo_pannel1']/div[3]/table/tbody/tr[10]/td[2]/select</value>
      <webElementGuid>83311dcc-51c4-4aa2-bf60-716d4b40e49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[7]/following::select[1]</value>
      <webElementGuid>017324f2-f9e2-4aa6-a755-dca244c9455a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Language'])[2]/preceding::select[1]</value>
      <webElementGuid>b5a79eab-3fc9-490e-b1c1-2b1c2d259de4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Intraday-Excess Limit'])[1]/preceding::select[2]</value>
      <webElementGuid>6460796a-f8c7-4154-8398-e6482ceaf705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[2]/select</value>
      <webElementGuid>4ce08a3c-8db1-47a2-b276-39ed6f2fa5c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'fomCO.cifVO.SEXE' and @id = 'cifVO_SEXE_F00I1MT' and @title = 'Gender' and (text() = 'FemaleMaleN/A' or . = 'FemaleMaleN/A')]</value>
      <webElementGuid>21f9e22f-81f7-4361-852c-ce70879a57cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
