<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Postal Code_ui-icon ui-icon-search liv_897e1e</name>
   <tag></tag>
   <elementGuidId>e95e89b9-852c-4023-92c4-aa3778925196</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanLookup_addressCO_POSTAL_CODE_F00I1MT']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spanLookup_addressCO_POSTAL_CODE_F00I1MT > span.ui-icon.ui-icon-search.live-search-ui.ui-state-disabled</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>60321106-2fe2-41ef-9991-7d89d6a35aa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-search live-search-ui ui-state-disabled</value>
      <webElementGuid>e05fb123-4fff-4baa-823f-ddc84cc47c33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanLookup_addressCO_POSTAL_CODE_F00I1MT&quot;)/span[@class=&quot;ui-icon ui-icon-search live-search-ui ui-state-disabled&quot;]</value>
      <webElementGuid>ab613b94-51ab-4884-8776-815773a12073</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='spanLookup_addressCO_POSTAL_CODE_F00I1MT']/span</value>
      <webElementGuid>4307bdac-e49d-4bb3-af36-a093dc036dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[8]/td[2]/div/table/tbody/tr/td/div/span/span</value>
      <webElementGuid>a3913121-14a0-4937-a607-62748be384bd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
