<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Postal Code_ui-icon ui-icon-search liv_dc6434</name>
   <tag></tag>
   <elementGuidId>6b801213-dd42-4e9c-8efd-2ad7d3eba0f8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[@id='spanLookup_addressCO_POSTAL_CODE_F00I1MT']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#spanLookup_addressCO_POSTAL_CODE_F00I1MT > span.ui-icon.ui-icon-search.live-search-ui</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f13e103b-340a-461f-ace9-04676fa0c225</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-icon ui-icon-search live-search-ui</value>
      <webElementGuid>0ecdf17f-09be-4023-adfe-a0701097a64a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;spanLookup_addressCO_POSTAL_CODE_F00I1MT&quot;)/span[@class=&quot;ui-icon ui-icon-search live-search-ui&quot;]</value>
      <webElementGuid>1afdbf51-cf86-4498-8a7e-8dc7515c4ed9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//span[@id='spanLookup_addressCO_POSTAL_CODE_F00I1MT']/span</value>
      <webElementGuid>dd8652d3-5aec-4735-bc5c-31e0e3247717</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[3]/table/tbody/tr[8]/td[2]/div/table/tbody/tr/td/div/span/span</value>
      <webElementGuid>a763e229-6268-4765-b627-311e3ad10fa5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
