<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Central Post Office</name>
   <tag></tag>
   <elementGuidId>78b79be4-66ae-4cc7-a874-8d37a8865230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9f73be58-81dc-4f63-aaf2-7ae8b219824b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>590d1d1b-f2da-411d-a6e2-1f84eb50a856</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Central Post Office</value>
      <webElementGuid>51d59112-3a71-4a90-be34-077a4c6a103d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>4d417ec8-44eb-4055-a732-ecd67c81bf10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_addressCO_POSTAL_CODE_F00I1MT_BRIEF_NAME_ENG</value>
      <webElementGuid>07b67ca3-4305-44b8-9d16-37d5c210d3d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG</value>
      <webElementGuid>d890328b-7ea6-4f0a-bc1e-2eb027d3602c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Central Post Office</value>
      <webElementGuid>0ea9cfba-ddf6-411d-981d-cbbeb0bc8b9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG&quot;)</value>
      <webElementGuid>613d5d10-fefa-465a-aab3-cc19692a9cd0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG']</value>
      <webElementGuid>3cc9b480-5b67-4f3c-8a06-946ddf0658b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[4]</value>
      <webElementGuid>3c739393-5c4a-4e6b-989d-869f3d76a0aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Region'])[2]/following::td[9]</value>
      <webElementGuid>b9b37578-4651-4897-891f-7169a517b751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Additional Reference'])[4]/following::td[9]</value>
      <webElementGuid>d5a5f831-6024-4ea7-a9c0-d13329a56b79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Post Office'])[2]/preceding::td[1]</value>
      <webElementGuid>bab70e88-b5f0-4a79-9334-0f351305c74c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Central Post Office'])[3]/preceding::td[2]</value>
      <webElementGuid>af47de0e-a44a-466d-951e-2a0b83eabb60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Central Post Office']/parent::*</value>
      <webElementGuid>95a019a2-7009-4e8c-bd0f-d2736f2d6731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[24]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>680ec448-32f2-4cba-863a-a0d3986b1e7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Central Post Office' and @id = 'td_gridtab_addressCO_POSTAL_CODE_F00I1MT_1_BRIEF_NAME_ENG' and (text() = 'Central Post Office' or . = 'Central Post Office')]</value>
      <webElementGuid>6e9d8c2a-94f2-4ff6-aa4c-92e3179cb3f5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
