<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Muscat</name>
   <tag></tag>
   <elementGuidId>ebff5fd0-b323-4658-99f2-87588f2f5e43</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>53f66dd5-0166-4746-92a1-0ceb51b156ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>e9faa674-7a91-4c80-8607-3dfb373e8d56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Muscat</value>
      <webElementGuid>7199acd4-4cd8-4c84-8120-0957ce55c88a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>7e144946-0134-4662-8205-5cd64790e7f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_addressCO_POBOX_AREA_F00I1MT_BRIEF_DESC_ENG</value>
      <webElementGuid>de5a5835-46ab-4f60-9a3d-451cc7b57d21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>1d72dfa6-b462-4524-b91a-621d1a981d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Muscat</value>
      <webElementGuid>1f15cbaa-8e4a-40db-b357-86974496ec47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>d21ae0bf-1506-4341-8218-92a4b7b587bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>ecd43c3a-5c93-48de-81fc-9e8230678093</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[3]</value>
      <webElementGuid>5ffb1efc-ff7c-4c35-ac4e-6bc6e7727ea5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الوصف الكامل'])[3]/following::td[7]</value>
      <webElementGuid>1b08897a-979c-4047-a2bc-e67fefda9f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Long Description'])[3]/following::td[7]</value>
      <webElementGuid>e01fc2e7-f770-4906-a3df-8f2d79da154f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='مسقط'])[1]/preceding::td[1]</value>
      <webElementGuid>f86f21f4-5461-4297-9115-fc4a831aa06c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Muscat'])[2]/preceding::td[2]</value>
      <webElementGuid>591d883d-6326-4be5-b230-db2b7ada8ecd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Muscat']/parent::*</value>
      <webElementGuid>fcbd3ae6-1bf6-4a6b-bf08-9f07f4d0b37c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>f3bb277d-3e5a-4696-984b-b81c4eabadd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'Muscat' and @id = 'td_gridtab_addressCO_POBOX_AREA_F00I1MT_1_BRIEF_DESC_ENG' and (text() = 'Muscat' or . = 'Muscat')]</value>
      <webElementGuid>58adb908-4877-4818-ac66-fa7dee4424ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
