<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_OMN</name>
   <tag></tag>
   <elementGuidId>4c14a1eb-c4e0-4b40-ac8a-e3a211e6b904</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>5af8cf44-2523-4797-b699-b3d2f500425e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>65d2a693-236f-4292-ac7e-8a626a145666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>OMN</value>
      <webElementGuid>0d9ccf4a-962d-4204-a334-659bbaecd1c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Brief Description</value>
      <webElementGuid>4ccef06c-b992-484b-9344-ae6c06b40e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>gridtab_countryOfIssuance_F00I1MT_BRIEF_DESC_ENG</value>
      <webElementGuid>d6bb7535-1327-4d96-80b6-dfe23e45f167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG</value>
      <webElementGuid>6dec0eae-cd18-419a-8fcd-89218ce894a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OMN</value>
      <webElementGuid>dd5e3999-4336-42fc-9387-cff2cb282bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG&quot;)</value>
      <webElementGuid>59012586-3fe3-43a3-8c1b-a382da5ff4ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG']</value>
      <webElementGuid>22cc6c19-a018-4353-9c5a-8de09559e773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//tr[@id='1']/td[2])[2]</value>
      <webElementGuid>27a40ad2-0376-473d-8a03-e75b8638fbe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ISO Code'])[1]/following::td[9]</value>
      <webElementGuid>d3825878-db0f-476c-9f70-9501f33c35b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Telephone Format'])[1]/following::td[9]</value>
      <webElementGuid>639f0d01-079b-4063-9500-feb5dad08705</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='عمان'])[1]/preceding::td[1]</value>
      <webElementGuid>becc847e-d8e4-4217-8c48-7231f87924fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Oman'])[1]/preceding::td[2]</value>
      <webElementGuid>bd3b888c-ad24-4643-9535-4230b3cc0e43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='OMN']/parent::*</value>
      <webElementGuid>bcc08d13-3240-4d74-81c5-e0a04f5a9324</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[20]/div/div[3]/div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>8b5444bc-064d-443e-8ff5-faa8419735f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = 'OMN' and @id = 'td_gridtab_countryOfIssuance_F00I1MT_1_BRIEF_DESC_ENG' and (text() = 'OMN' or . = 'OMN')]</value>
      <webElementGuid>6e1a174d-a5f3-4f1a-b06d-1262e5487519</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
