<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Email_addressCO.EMAIL</name>
   <tag></tag>
   <elementGuidId>4d057f02-f641-4f0b-9ae0-28fe2e8e2ad6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='addressCO_EMAIL_F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#addressCO_EMAIL_F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>ccdd7f71-122d-4d76-9542-43b932384240</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addressCO.EMAIL</value>
      <webElementGuid>de527f81-20bd-43e2-9c31-478de12dcf8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path-theme-cust-input textCompSize ui-state-focus ui-corner-all textCompSize ui-state-focus ui-corner-all</value>
      <webElementGuid>47243ca3-afb3-40f4-8de8-3ff69eae16c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>addressCO_EMAIL_F00I1MT</value>
      <webElementGuid>777d10a2-0568-48b9-ab5f-2fc162f1910d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>255</value>
      <webElementGuid>5eb69ae2-b18c-42d4-b1e9-c24eed5a1a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>validateEmail('F00I1MT')</value>
      <webElementGuid>217c3c09-20d9-4be1-a7ff-853727d0c67a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabeltext</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>a26ec673-28a3-4c64-a909-82dced4de184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>overridelabelkey</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>f2c0e348-809c-4b7f-8dc5-ff63c7b2c8de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependency</name>
      <type>Main</type>
      <value>addressCO_EMAIL_F00I1MT:fomCO.addressField</value>
      <webElementGuid>f1123ed9-417a-48d6-8066-2058cd336a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>dependencysrc</name>
      <type>Main</type>
      <value>/imal_core_portal/path/fom/FOMValidate_validateSpecialCharInFields</value>
      <webElementGuid>94d182c7-ca4a-4b65-b68d-cd1b76fa367c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parameter</name>
      <type>Main</type>
      <value>fomCO.addressField:addressCO_EMAIL_F00I1MT</value>
      <webElementGuid>38111dfe-8b41-4633-a773-9abd97723a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Email</value>
      <webElementGuid>e0466b85-6cd8-490c-8a34-3b148400a43b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;addressCO_EMAIL_F00I1MT&quot;)</value>
      <webElementGuid>c3edaa27-b304-4f04-b6d0-0f7361c29dfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='addressCO_EMAIL_F00I1MT']</value>
      <webElementGuid>65d0ed04-d409-455f-bf07-1d5396e51765</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='addrTbl_F00I1MT']/tbody/tr[3]/td[2]/table/tbody/tr[7]/td[2]/textarea</value>
      <webElementGuid>d4101877-4a7a-4b36-bf89-9ffa1fe909fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[7]/td[2]/textarea</value>
      <webElementGuid>0528cfa4-c858-4f0b-80c4-527cb974864c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'addressCO.EMAIL' and @id = 'addressCO_EMAIL_F00I1MT' and @title = 'Email']</value>
      <webElementGuid>8e774fa3-3908-40c8-86d0-23c4b34b7280</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
