<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Maintenance</name>
   <tag></tag>
   <elementGuidId>5fb45670-e861-43ae-bed9-a09cb2b055d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='F00I1MT']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#F00I1MT</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7279f813-0ba8-48fc-8fef-a07f5190e9ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>F00I1MT</value>
      <webElementGuid>a9595d68-7f1a-45c5-a5c6-d05f9aa2c86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>035da85d-2f09-4370-8737-f32a1ad131f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:addMenuTab('F00I1MT','Maintenance','RET','F00I1' )</value>
      <webElementGuid>6d14c27e-a738-477e-837f-579db61b7dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Maintenance	</value>
      <webElementGuid>65d7ff15-fbac-4e8c-98d4-35123cbfce93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;F00I1MT&quot;)</value>
      <webElementGuid>0d4d8cca-2760-41b8-b518-8d01326cbc63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='F00I1MT']</value>
      <webElementGuid>b0b1980b-8c9b-4c14-a63d-fb7c9774d701</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_selenuimF00I1MT']/li/a</value>
      <webElementGuid>c27a58f3-5cbc-4dda-b58f-ce045b8417ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Front Office Management'])[1]/following::a[1]</value>
      <webElementGuid>c38a0bfb-fe7e-495a-9fd8-1e854833c09e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[2]/following::a[1]</value>
      <webElementGuid>44f1f63f-23e5-42c6-b33d-8cde5691801a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Apply Suspend'])[1]/preceding::a[1]</value>
      <webElementGuid>aab2b96b-6ed6-4697-b0cc-9118fb52f175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[12]</value>
      <webElementGuid>7be67d69-dae6-499f-b63a-d3585616a911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li/a</value>
      <webElementGuid>d2c09aca-c2ba-4e2b-9ba9-e194c712b7db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'F00I1MT' and @href = '#' and (text() = 'Maintenance	' or . = 'Maintenance	')]</value>
      <webElementGuid>593d22e2-6298-48bd-a215-b856dfeb6ca9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
