<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_Front Office Management</name>
   <tag></tag>
   <elementGuidId>76b7ca44-d314-4be6-9a0b-3822c1eb9c3e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='_selenuimF00I1']/h3</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>h3.h3_F00I1.accordionheader.rootheaderappMenu.ui-widget-header</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>3a253104-4117-47f6-97da-10fe2eb46ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h3_F00I1 accordionheader rootheaderappMenu ui-widget-header</value>
      <webElementGuid>6c24d409-ee88-4e8a-a216-af7a30503a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>headerindex</name>
      <type>Main</type>
      <value>1h</value>
      <webElementGuid>53f9e95c-a7fd-45a3-8865-4aaaa10a1659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Front Office Management</value>
      <webElementGuid>c597fc04-b4bc-484e-b0ed-740d8db377f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_selenuimF00I1&quot;)/h3[@class=&quot;h3_F00I1 accordionheader rootheaderappMenu ui-widget-header&quot;]</value>
      <webElementGuid>263f22e0-474f-4c79-9859-6f49b9a67923</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_selenuimF00I1']/h3</value>
      <webElementGuid>cedccf30-6103-4532-92a0-0329f55ff55f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[2]/following::h3[1]</value>
      <webElementGuid>498abb74-55f3-4f42-815e-e5b27189433d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Accounts'])[1]/following::h3[1]</value>
      <webElementGuid>7af0ad1d-0030-4d89-9900-c934c37b2890</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Front Office Management'])[2]/preceding::h3[1]</value>
      <webElementGuid>9bd414df-683a-4a16-aea9-541472cba2ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/h3</value>
      <webElementGuid>d68bfdde-82e9-40a6-b7c0-77ffa1e5bae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'Front Office Management' or . = 'Front Office Management')]</value>
      <webElementGuid>97eae70f-b6c0-49e7-877b-ee5f937bc282</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
