<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Login</name>
   <tag></tag>
   <elementGuidId>bec9a26a-6676-4d54-97ec-4eadba047ea3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[@onclick='javascript:login();']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>17d8df57-b846-41fb-9b51-b75ccec96097</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>align</name>
      <type>Main</type>
      <value>center</value>
      <webElementGuid>e2631403-4514-45bd-aff0-aba66384e030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>javascript:login();</value>
      <webElementGuid>bd2023f5-188c-498d-b3c5-0e3c06c9a884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Login </value>
      <webElementGuid>0ae59072-3685-4267-a7ae-463d9d6837b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;loginElementsToBeHidden&quot;)/table[1]/tbody[1]/tr[2]/td[2]</value>
      <webElementGuid>018d6d90-9263-4823-8bd2-bb0b13b8a4d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@onclick='javascript:login();']</value>
      <webElementGuid>cb99d3a7-4cce-4a14-86ef-21de8763257e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='loginElementsToBeHidden']/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>68db0833-48d3-497b-a46a-cec62d5f95f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Virtual Keyboard'])[1]/following::td[1]</value>
      <webElementGuid>29b99487-142c-4f78-af40-8451eea7cd8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Password'])[1]/following::td[5]</value>
      <webElementGuid>7ffbad84-bde2-4540-9a1a-26555f11c0a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='iMAL*CSM 14.6.0.0 Build 470'])[1]/preceding::td[2]</value>
      <webElementGuid>13875f05-427c-44a2-8702-2c58e8c6fefd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>b77c1c06-8e7d-43d5-8c5b-f64da504b20c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = ' Login ' or . = ' Login ')]</value>
      <webElementGuid>dbafe2c3-bf88-4f71-941c-5e52219a026d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
