<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Brief Description_BRANCH_CODE</name>
   <tag></tag>
   <elementGuidId>2c70dae6-e407-4c3d-8d11-f9427879d540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gridtab_BRANCH_CODE_gs_BRANCH_CODE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gridtab_BRANCH_CODE_gs_BRANCH_CODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>402686e9-ea29-4901-b6a8-2d665467875b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ed1e9b97-59cd-4a13-9186-7cdee8d96a5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BRANCH_CODE</value>
      <webElementGuid>e3f6a04c-17bc-4efd-98f9-73170b78f39b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gridtab_BRANCH_CODE_gs_BRANCH_CODE</value>
      <webElementGuid>8db63c00-c0c0-4302-a542-75be9898dc30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gridtab_BRANCH_CODE_gs_BRANCH_CODE&quot;)</value>
      <webElementGuid>4a26f853-7aaf-431f-a338-2d39fbbc8fab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gridtab_BRANCH_CODE_gs_BRANCH_CODE']</value>
      <webElementGuid>08a93cc8-e12e-4c04-916e-33d4b5d9be68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_gridtab_BRANCH_CODE']/div[2]/div/table/thead/tr[2]/th/div/input</value>
      <webElementGuid>174f40c8-a483-48f6-a290-29a36c480749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th/div/input</value>
      <webElementGuid>389f6385-b4c1-4a57-ba73-a03d61dfa433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'BRANCH_CODE' and @id = 'gridtab_BRANCH_CODE_gs_BRANCH_CODE']</value>
      <webElementGuid>73a3224f-b3c9-48d7-b452-957d733b010f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
