<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__CIF_SUB_NO</name>
   <tag></tag>
   <elementGuidId>f58f9a36-60ac-48a2-9a83-4004fce5bbcc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='generalAccountsGridTbl_Id_A002AU_gs_amfVO.CIF_SUB_NO']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>12744c14-99f4-4e0f-a202-b2bf666977ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2234f713-8cb9-4faf-9d29-ec5448459417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CIF_SUB_NO</value>
      <webElementGuid>4e2c6501-93e0-4550-a9ea-969ff21dadca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generalAccountsGridTbl_Id_A002AU_gs_amfVO.CIF_SUB_NO</value>
      <webElementGuid>badaa8f1-9829-41e6-9d42-e8fae18f8abc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generalAccountsGridTbl_Id_A002AU_gs_amfVO.CIF_SUB_NO&quot;)</value>
      <webElementGuid>4bcd5c73-270d-4f53-aca1-28350dd66c17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='generalAccountsGridTbl_Id_A002AU_gs_amfVO.CIF_SUB_NO']</value>
      <webElementGuid>47cd42af-adf8-4c55-afa3-c8458eff4342</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_generalAccountsGridTbl_Id_A002AU']/div[2]/div/table/thead/tr[2]/th[4]/div/input</value>
      <webElementGuid>6fc59898-8f29-423b-9c9e-e1ffc7719b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[4]/div/input</value>
      <webElementGuid>543a974e-51d1-40b0-bee3-bd264456b293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'CIF_SUB_NO' and @id = 'generalAccountsGridTbl_Id_A002AU_gs_amfVO.CIF_SUB_NO']</value>
      <webElementGuid>9357d4cc-bd11-4863-b682-fbab9727b261</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
