<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_183 Do you want to Print confirmation_70fca4</name>
   <tag></tag>
   <elementGuidId>f331cf2c-a4b1-46a6-8c99-a2dfdb8fb28d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_popup_path_sol_confirm</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_popup_path_sol_confirm']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a4fc5080-c267-4d83-b485-e985334746dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce8d176a-3e08-44b6-b646-d58a67fb9e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_popup_path_sol_confirm</value>
      <webElementGuid>5ea288e3-951b-4dce-b393-9b3152bbdd45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fg-button ui-button ui-corner-all ui-button-text ui-widget ui-state-default ui-button-text-only</value>
      <webElementGuid>f03cb459-f624-4028-b092-81b7e28fd02d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Cancel</value>
      <webElementGuid>b7bd7355-a037-440f-93bf-e065838ebfe6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_popup_path_sol_confirm&quot;)</value>
      <webElementGuid>270a824a-3d1a-403f-ad7c-9ad93f96ee9d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_popup_path_sol_confirm']</value>
      <webElementGuid>6a7b9d3a-be22-4192-865b-7553571d8d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div__popup_path_sol_confirm']/center/input[2]</value>
      <webElementGuid>2af80cfa-7129-426b-801b-6bbac464893c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//center/input[2]</value>
      <webElementGuid>d9eb3cb7-cd29-4d28-9381-7bd2ce664029</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_popup_path_sol_confirm']</value>
      <webElementGuid>b463d2bb-265b-40e3-bbc1-96afa47ecf4a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
