<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_Authorize</name>
   <tag></tag>
   <elementGuidId>9c51c218-338c-4203-b590-34ef24105a17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#generalAccountForm_A002AU_Authorize_key</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='generalAccountForm_A002AU_Authorize_key']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>c0118167-3914-4265-9df9-0679375629c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>generalAccountForm_A002AU_Authorize_key</value>
      <webElementGuid>c32926bf-9efd-4cac-9a31-6096e4f2a71b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>gaAuthorize_A002AU</value>
      <webElementGuid>f5f5b89c-7789-4996-9887-1a43a413eb10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>labelkey</name>
      <type>Main</type>
      <value>Authorize_key</value>
      <webElementGuid>97c1a2ac-9fba-4f61-b593-d91424b6bd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>path_btn_lbl_theme</value>
      <webElementGuid>d929d563-c87a-4711-ada3-9e1ea4142366</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Authorize </value>
      <webElementGuid>e53f80a7-97a1-4361-821e-6e25092424fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;generalAccountForm_A002AU_Authorize_key&quot;)</value>
      <webElementGuid>4ca412d3-e6fb-4c33-b9e7-6e28bdc51ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='generalAccountForm_A002AU_Authorize_key']</value>
      <webElementGuid>9ca3d280-45f7-47e6-a4cf-04b10ee1d931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='gaAuthorize_A002AU']/span[2]/label</value>
      <webElementGuid>969f43f6-7f1c-4cee-8042-93c1f3319d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Charges Waiver'])[1]/following::label[1]</value>
      <webElementGuid>40bfb8ac-6ca0-40f8-b85e-771723676f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KYC Details'])[1]/following::label[2]</value>
      <webElementGuid>3c034b37-ad20-4791-8d63-8198dc32faee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reject'])[1]/preceding::label[1]</value>
      <webElementGuid>f6c98599-2719-4897-9d45-588c6c0e90b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/button/span[2]/label</value>
      <webElementGuid>6a70159a-3181-4a1c-8eb6-2bf0978923de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@id = 'generalAccountForm_A002AU_Authorize_key' and (text() = 'Authorize ' or . = 'Authorize ')]</value>
      <webElementGuid>5133ef1a-fc48-470d-9f7f-abde46663668</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
