<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_512</name>
   <tag></tag>
   <elementGuidId>63fb4bef-4cf8-47b1-9649-86346b89de73</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_generalAccountsGridTbl_Id_A002AU_1_amfVO.CURRENCY_CODE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>2a7af97c-3230-4afb-ac93-669da3a8f13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>c632609d-1213-4191-ae1c-9cf2159bb9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>d7408cc9-cd75-468c-ba33-17f77efc86f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>006a47ea-aa42-45e8-a6ef-e4ca35fb7aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>CY</value>
      <webElementGuid>84b0c3fe-f1e3-45af-956e-26c5b2f776a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>generalAccountsGridTbl_Id_A002AU_amfVO.CURRENCY_CODE</value>
      <webElementGuid>49dbb577-b3a6-4ac2-bb21-51f1251876df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_generalAccountsGridTbl_Id_A002AU_1_amfVO.CURRENCY_CODE</value>
      <webElementGuid>6cbfb996-161e-48d0-869e-612f3b9fa6f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>512</value>
      <webElementGuid>c5b3f694-cc5d-4823-bd57-355d5c9cb1f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_generalAccountsGridTbl_Id_A002AU_1_amfVO.CURRENCY_CODE&quot;)</value>
      <webElementGuid>f054e230-7810-4d1d-a34e-2ca92dc9760b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_generalAccountsGridTbl_Id_A002AU_1_amfVO.CURRENCY_CODE']</value>
      <webElementGuid>072b2384-9314-4d2e-a4be-9ab00e2b20af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[2]</value>
      <webElementGuid>56a77637-a3a8-4cde-9b8e-7a63c6783545</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='الإسم الكامل بالعربية'])[1]/following::td[15]</value>
      <webElementGuid>8fc349ca-6727-4db2-baab-c5bc1447f1f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Short Name Arab'])[1]/following::td[15]</value>
      <webElementGuid>69e0b8cf-aef9-416c-a3be-b3c0f13341fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ANU'])[1]/preceding::td[7]</value>
      <webElementGuid>91967d4e-c0d2-4d67-a8f5-d6fb37d3fb97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='KUTTAN'])[1]/preceding::td[8]</value>
      <webElementGuid>d989d75d-c991-4546-b286-654c822fd290</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='512']/parent::*</value>
      <webElementGuid>20a6bb7e-3b55-48e0-a5df-ca96d17eb120</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>7bef6d64-fd10-4299-a5f1-213e95d6d81d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '512' and @id = 'td_generalAccountsGridTbl_Id_A002AU_1_amfVO.CURRENCY_CODE' and (text() = '512' or . = '512')]</value>
      <webElementGuid>23eff1e5-5704-4089-bd40-56a914af2f77</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
