<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trade Date_statusDesc</name>
   <tag></tag>
   <elementGuidId>a574dacc-537f-4936-87bc-13957c779103</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transferCashGridTbl_Id_L0VVAP_gs_statusDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transferCashGridTbl_Id_L0VVAP_gs_statusDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5c9145a0-dfac-4fa4-ae0d-2c4805d47b63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae75d363-7d44-43c7-a348-0cbc083b0d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statusDesc</value>
      <webElementGuid>3d877ab3-3c6d-4894-8e02-96c2400df170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transferCashGridTbl_Id_L0VVAP_gs_statusDesc</value>
      <webElementGuid>06f50355-223b-441d-8e10-ada3c4024434</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferCashGridTbl_Id_L0VVAP_gs_statusDesc&quot;)</value>
      <webElementGuid>f5e77b0b-b332-4736-a98a-5fa3bacca8b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transferCashGridTbl_Id_L0VVAP_gs_statusDesc']</value>
      <webElementGuid>5474723b-6f0c-4bfe-8374-15efa66887d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_transferCashGridTbl_Id_L0VVAP']/div[2]/div/table/thead/tr[2]/th[6]/div/input</value>
      <webElementGuid>e041844a-bf1b-48fb-858f-00f1c6849fa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/div/input</value>
      <webElementGuid>a6632b43-69bc-492e-bb48-fc459f27bb93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'statusDesc' and @id = 'transferCashGridTbl_Id_L0VVAP_gs_statusDesc']</value>
      <webElementGuid>7e6b855e-b831-49d5-9877-03fe8d85baf6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
