<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_7133</name>
   <tag></tag>
   <elementGuidId>f11d43a3-8226-4575-abd8-3196e84db49c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_transferCashGridTbl_Id_L0VVAP_1_trxNo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_transferCashGridTbl_Id_L0VVAP_1_trxNo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>60a5cb4e-ff6c-45c5-9ed5-9e08bfc3cd0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>7ca84870-d942-4a0a-afc0-0b985869a8b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>8df8b2bd-a302-4e69-b669-2e3f6f10accc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>7133</value>
      <webElementGuid>ef03d725-e897-4015-a0fd-8aa853e79a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>Trx No</value>
      <webElementGuid>448f82ba-64f0-4e0f-85c5-989b72995bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>transferCashGridTbl_Id_L0VVAP_trxNo</value>
      <webElementGuid>6230a2f7-45ca-4168-b35d-4fd076ce794b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_transferCashGridTbl_Id_L0VVAP_1_trxNo</value>
      <webElementGuid>74ea3227-dff6-4f1c-bbc3-c092c031efba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>7133</value>
      <webElementGuid>8fe6019f-36ba-482d-a5dd-02b5fade77ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_transferCashGridTbl_Id_L0VVAP_1_trxNo&quot;)</value>
      <webElementGuid>8ee55867-bf0b-4563-a6be-5bca8f2758f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_transferCashGridTbl_Id_L0VVAP_1_trxNo']</value>
      <webElementGuid>cc9c45a5-3083-4103-b8cc-bcdfdbbfb74d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td</value>
      <webElementGuid>a728e06c-8ee2-4c5e-9865-c9e6a281f5b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trade Date'])[1]/following::td[8]</value>
      <webElementGuid>a99ce62d-78f2-451b-8a09-4a33fc14d684</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::td[8]</value>
      <webElementGuid>0cc56ddb-e34e-448a-81c5-ae8f13b57836</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[1]/preceding::td[2]</value>
      <webElementGuid>cddf69a6-059e-4296-a870-c37fe7588a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[2]/preceding::td[4]</value>
      <webElementGuid>2d76744b-9ef4-46f0-a565-fc6907e08a0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='7133']/parent::*</value>
      <webElementGuid>b516de08-e3ce-49d1-80f6-5993e235d9db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td</value>
      <webElementGuid>217a98fd-3024-4756-b422-592b8132ca9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '7133' and @id = 'td_transferCashGridTbl_Id_L0VVAP_1_trxNo' and (text() = '7133' or . = '7133')]</value>
      <webElementGuid>219f0071-abbd-464f-a681-8a9548e13568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
