<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_1905 Operation generated Transaction _8d9e4b</name>
   <tag></tag>
   <elementGuidId>eb3ba9ed-6856-4caf-9eb0-60bec05feb9e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#_popup_path_sol_ok</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='_popup_path_sol_ok']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3f764913-c38a-4e3e-af38-00ac83570eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>438c2dcd-4d24-4921-a2f9-c462d978e7be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>_popup_path_sol_ok</value>
      <webElementGuid>e49e8201-d28d-43da-83cc-fb7722a9dd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text fg-button ui-button ui-corner-all ui-widget ui-state-default ui-button-text-only</value>
      <webElementGuid>6c2eef93-259c-44d0-8125-1d8a84bd0e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Ok</value>
      <webElementGuid>1e6dbd5d-f935-495d-92e6-4cf9dc6caab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;_popup_path_sol_ok&quot;)</value>
      <webElementGuid>19877740-8c2b-49cf-a410-98a4aad2f417</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='_popup_path_sol_ok']</value>
      <webElementGuid>5cf28933-cbe4-41d7-a136-d488151213da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='div__popup_path_sol_ok']/center/input</value>
      <webElementGuid>aecf7984-25eb-4cae-be69-47cb322a3423</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[22]/center/input</value>
      <webElementGuid>331e8815-9c7e-45db-a0a3-35dd09115792</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'button' and @id = '_popup_path_sol_ok']</value>
      <webElementGuid>2af5d71e-e37f-4b8b-adc3-1cf44fb9c2fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
