<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Trade Date_statusDesc</name>
   <tag></tag>
   <elementGuidId>5316c377-6620-48c0-9fce-9e8bd07517c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#transferCashGridTbl_Id_L0VVAP_gs_statusDesc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='transferCashGridTbl_Id_L0VVAP_gs_statusDesc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>54736d41-68ba-4567-bd95-566677d31220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5174d451-a975-415c-a1c3-7a54935a7d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>statusDesc</value>
      <webElementGuid>617ba197-1a43-458f-9e71-9f3c6a67648b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>transferCashGridTbl_Id_L0VVAP_gs_statusDesc</value>
      <webElementGuid>1e85772f-a155-4c2a-91ce-aed39029dc16</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;transferCashGridTbl_Id_L0VVAP_gs_statusDesc&quot;)</value>
      <webElementGuid>48e55933-979b-47a6-8dcd-bae607872bd6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='transferCashGridTbl_Id_L0VVAP_gs_statusDesc']</value>
      <webElementGuid>77c06aaa-b183-44ae-8bd1-d3a28ad17e00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gview_transferCashGridTbl_Id_L0VVAP']/div[2]/div/table/thead/tr[2]/th[6]/div/input</value>
      <webElementGuid>51e7255b-2d7f-4313-bef2-56ce5af705c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//th[6]/div/input</value>
      <webElementGuid>85fa81b1-e8bb-4222-ab0c-8c6314a39773</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'statusDesc' and @id = 'transferCashGridTbl_Id_L0VVAP_gs_statusDesc']</value>
      <webElementGuid>0e706958-18f4-4f70-a1ef-e6de99056e81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
