<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_1</name>
   <tag></tag>
   <elementGuidId>31cb7f09-efbf-4a95-b364-d8507ee60f3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#td_transferCashGridTbl_Id_L0VVAP_1_tellerCode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='td_transferCashGridTbl_Id_L0VVAP_1_tellerCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>9cb4a22b-1beb-4039-abf0-1c7d7ca36a25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>gridcell</value>
      <webElementGuid>b8d5d19f-2752-47a9-9288-155234f5d41e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>right </value>
      <webElementGuid>75985c1b-46e8-4822-a54e-33ae7f577a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5eca902f-500a-4265-ad02-596b278d9003</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tdlabel</name>
      <type>Main</type>
      <value>From Vault</value>
      <webElementGuid>3c2471b5-2a98-44a2-94a9-c666d5fa01d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>transferCashGridTbl_Id_L0VVAP_tellerCode</value>
      <webElementGuid>112cf3d7-ea24-46c9-8d50-95548458f591</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>td_transferCashGridTbl_Id_L0VVAP_1_tellerCode</value>
      <webElementGuid>a43e40a1-ccfe-4767-924e-232e06e97a27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>340af293-c4af-4cba-8c7e-f3188123b2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;td_transferCashGridTbl_Id_L0VVAP_1_tellerCode&quot;)</value>
      <webElementGuid>ee5d7536-0f19-43a0-98fd-909b4c585650</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='td_transferCashGridTbl_Id_L0VVAP_1_tellerCode']</value>
      <webElementGuid>f419e607-19a6-4b32-9e6c-8a432721b177</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//tr[@id='1']/td[2]</value>
      <webElementGuid>c46368ef-eb19-4ec6-879c-efee845c143e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Trade Date'])[1]/following::td[9]</value>
      <webElementGuid>0587ddac-131a-4897-ac4a-c5285698f266</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::td[9]</value>
      <webElementGuid>ed32af78-2b47-4222-ab43-b01d9d577361</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[1]/preceding::td[1]</value>
      <webElementGuid>a8599864-1b15-4895-a984-882bf297da4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TELLER'])[2]/preceding::td[3]</value>
      <webElementGuid>b732a9d2-e706-4fb4-b4a1-397fb5db5735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='1']/parent::*</value>
      <webElementGuid>e93d0d63-5db0-4ea8-8278-f2d631d54aba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/table/tbody/tr[2]/td[2]</value>
      <webElementGuid>1b09f15e-5d84-44fc-9bd7-0666c491a90e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@title = '1' and @id = 'td_transferCashGridTbl_Id_L0VVAP_1_tellerCode' and (text() = '1' or . = '1')]</value>
      <webElementGuid>85274dd9-e8ba-411a-9737-df04dcb7f15a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
