<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>td_Password</name>
   <tag></tag>
   <elementGuidId>756ba10f-6f6a-49c8-bb21-177ce60ca947</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#test1</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//td[@id='test1']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>912662ab-8d9d-4341-9d7d-a645e5a4fbff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>test1</value>
      <webElementGuid>90a89364-f2ad-44c1-ad13-b30526f682a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fldDataLeft</value>
      <webElementGuid>7cecda6b-f2d4-4135-b555-6ea1eb23ab0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Password </value>
      <webElementGuid>27b5ba72-42b4-49d3-baa5-d0d92bed5830</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;test1&quot;)</value>
      <webElementGuid>4f346a5b-94c3-4174-8e92-2db290f37a6f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//td[@id='test1']</value>
      <webElementGuid>25529f12-11db-49ca-a34f-87362f67d292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='loginForm']/table/tbody/tr/td/table/tbody/tr/td[2]/table/tbody/tr[2]/td[2]/table/tbody/tr[8]/td</value>
      <webElementGuid>22c6a460-5818-49a6-9f23-8cc18cfa0432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='User Name'])[1]/following::td[2]</value>
      <webElementGuid>20126933-c3be-4370-8355-dd767d7d3022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Virtual Keyboard'])[1]/preceding::td[3]</value>
      <webElementGuid>206dd533-cb16-4bf4-b90b-55f1b8dd5d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[8]/td</value>
      <webElementGuid>16dfb599-e7b1-468b-a6cc-d09c6acc2176</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[@id = 'test1' and (text() = ' Password ' or . = ' Password ')]</value>
      <webElementGuid>d87cf8ce-8653-48c3-8184-372e1756ff5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
